/* Run: serve the repo root (python3 -m http.server 8765), then: node qa/v415/browser_erp_link.js  (needs the playwright package)
   Real Chromium check of vrt_erp_link_v1.html with REAL PROD data (sewing backup, production plan, orders backup) and the page's own
   isolated synthetic ERP files. No real ERP export was available → real-data comparison stays NOT TESTED; this run checks the mechanics:
   page loads with no errors, reads PROD read-only (no new module DBs), demo isolation, import → mapping → preview → commit, re-import
   idempotence, compare tabs render, daily report draft, Telegram modal, cloud push/pull against a mock GAS, EN/KM language switch. */
const { chromium } = require('playwright');const fs=require('fs'),path=require('path');
const DL=process.env.VRT_DL||'/mnt/user-data/uploads/Downloads/',ROOT=path.resolve(__dirname,'../..')+'/',BASE=process.env.VRT_BASE_URL||'http://127.0.0.1:8765/',OUT=process.env.VRT_SHOTS||path.resolve(__dirname,'../../../shots_v415')+'/';
fs.mkdirSync(OUT,{recursive:true});
const out=[];const test=async(name,fn)=>{try{const d=await fn();out.push({name,status:'PASS',detail:d});console.log('PASS',name,'·',d)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}};
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}).catch(()=>chromium.launch());
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(page.url().split('/').pop()+': '+e.message));page.on('dialog',d=>d.accept());
 // ── seed real PROD data
 await page.goto(BASE+'production_plan_capacity_v1.html',{waitUntil:'load'});await page.waitForTimeout(800);await page.setInputFiles('#fileInput',DL+'Production  Plan From July Until  Dec_2026 (1).xlsx');await page.waitForTimeout(2500);await page.evaluate(()=>confirmPlanImport512());await page.waitForTimeout(800);
 await page.goto(BASE+'sewing_v5.html',{waitUntil:'load'});await page.waitForTimeout(1000);await page.setInputFiles('input[type=file][accept=".json"]',DL+'sewing_backup_2026-09-28.json');await page.waitForTimeout(3500);
 await page.goto(BASE+'orders_v3.html',{waitUntil:'load'});await page.waitForTimeout(1200);try{await page.setInputFiles('#ri',DL+'orders_v3_backup_2026-09-30.json');await page.waitForTimeout(3000)}catch(e){console.log('orders restore skipped:',e.message)}
 const dbsBefore=(await page.evaluate(async()=>(await indexedDB.databases()).map(d=>d.name).sort()));
 // ── the page
 await page.goto(BASE+'vrt_erp_link_v1.html',{waitUntil:'load'});await page.waitForTimeout(2500);
 await test('Page loads with real PROD data, read-only (no new module DBs besides VRT_ERPLink), no page errors',async()=>{const st=await page.evaluate(async()=>{await VRT_LOCAL_READY;const P=ERPLINK.PROD;return {sewing:P.sewing.length,plan:P.plan.length,orders:P.orders.length,shipping:P.shipping.length,latest:P.latest,kpis:document.querySelectorAll('#srcKpis .kpi').length}});
   const dbsAfter=(await page.evaluate(async()=>(await indexedDB.databases()).map(d=>d.name).sort()));const added=dbsAfter.filter(n=>!dbsBefore.includes(n));if(added.some(n=>!/^VRT_ERPLink$|SmartSync/.test(n)))throw new Error('unexpected DBs '+added.join(','));if(!(st.sewing>1000&&st.plan>500))throw new Error('PROD not read '+JSON.stringify(st));if(errors.length)throw new Error(errors.join(' | '));
   await page.screenshot({path:OUT+'01_erplink_status.png',fullPage:true});return 'sewing '+st.sewing+' · plan '+st.plan+' · orders '+st.orders+' · shipping '+st.shipping+' · new DBs '+added.join(',')});
 await test('T01-style demo isolation: synthetic rows render in the compare tabs but are never stored (IndexedDB empty) and the banner is shown',async()=>{await page.evaluate(()=>ERPLINK.loadDemo());await page.waitForTimeout(600);const r=await page.evaluate(async()=>{const rows=document.querySelectorAll('#ordTbl tbody tr.click').length;const stored=(await VRTProdStorage.all('VRT_ERPLink','erp_orders')).length;const banner=document.getElementById('demoBanner').classList.contains('on');const cloud=ERPLINK.cloudRecords().length;return {rows,stored,banner,cloud,sum:ERPLINK.CMP.orders.summary}});
   if(!(r.rows>=3&&r.stored===0&&r.banner&&r.cloud===0))throw new Error(JSON.stringify(r));await page.screenshot({path:OUT+'02_erplink_demo_orders.png',fullPage:true});await page.evaluate(()=>ERPLINK.clearDemo());return 'demo rows '+r.rows+' · stored 0 · cloud records 0 · states '+JSON.stringify(r.sum)});
 // ── import flow with the synthetic ERP CSV (a real file goes through the very same path)
 const f=path.resolve(OUT,'TEST_erp_orders.csv');const f2=path.resolve(OUT,'TEST_erp_shipments.csv');{const vm=require('vm');const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(ROOT+'vrt-erp-link-core-v1.js','utf8')+';this.__s=VRTErpLink.sampleFiles()',c);fs.writeFileSync(f,c.__s.orders.text);fs.writeFileSync(f2,c.__s.ship.text)}
 await test('Import: file → dataset detected → mapping shown (required marked) → preview counts → commit; stored rows + batch + mapping template',async()=>{await page.evaluate(()=>showTab('import'));await page.setInputFiles('#fileIn',f);await page.waitForTimeout(800);
   const m=await page.evaluate(()=>({ds:document.getElementById('dsSel').value,req:document.querySelectorAll('#mapGrid label.req').length,tpl:document.getElementById('mapTpl').textContent,card:document.getElementById('mapCard').style.display}));if(m.ds!=='order_line'||m.req<2)throw new Error(JSON.stringify(m));
   await page.evaluate(()=>{document.getElementById('confirmBy').value='QA';previewImport()});await page.waitForTimeout(500);const pv=await page.evaluate(()=>document.getElementById('prevSummary').innerText.replace(/\s+/g,' ').slice(0,160));await page.screenshot({path:OUT+'03_erplink_import_preview.png',fullPage:true});
   await page.evaluate(()=>commitImport());await page.waitForTimeout(1200);const st=await page.evaluate(async()=>({stored:(await VRTProdStorage.all('VRT_ERPLink','erp_orders')).length,imports:ERPLINK.DB.imports.length,maps:ERPLINK.DB.mappings.length,first:ERPLINK.DB.imports[0]}));
   if(st.stored!==4||st.imports!==1||st.maps!==1||st.first.added!==4)throw new Error(JSON.stringify(st));return 'preview "'+pv+'" → stored 4 · batch added 4 · template v'+(await page.evaluate(()=>ERPLINK.DB.mappings[0].version))});
 await test('T03 re-import of the same file (and the mapping template is auto-applied): added 0 / same 4, nothing grows',async()=>{await page.evaluate(()=>showTab('import'));await page.setInputFiles('#fileIn',f);await page.waitForTimeout(800);const tpl=await page.evaluate(()=>document.getElementById('mapTpl').className);await page.evaluate(()=>previewImport());await page.waitForTimeout(400);await page.evaluate(()=>commitImport());await page.waitForTimeout(1000);
   const st=await page.evaluate(async()=>({stored:(await VRTProdStorage.all('VRT_ERPLink','erp_orders')).length,b:ERPLINK.DB.imports[0]}));if(st.stored!==4||st.b.added!==0||st.b.same!==4)throw new Error(JSON.stringify(st));return 'template '+tpl+' · stored 4 · added 0 same 4'});
 await test('Shipment file import + compare tabs render with real PROD rows (states shown, NOT TESTED label present)',async()=>{await page.evaluate(()=>showTab('import'));await page.setInputFiles('#fileIn',f2);await page.waitForTimeout(800);const ds=await page.evaluate(()=>document.getElementById('dsSel').value);if(ds!=='shipment_line')throw new Error('dataset '+ds);await page.evaluate(()=>previewImport());await page.waitForTimeout(400);await page.evaluate(()=>commitImport());await page.waitForTimeout(1000);
   await page.evaluate(()=>showTab('orders'));await page.waitForTimeout(600);const o=await page.evaluate(()=>({rows:document.querySelectorAll('#ordTbl tbody tr').length,asOf:document.getElementById('ordAsOf').textContent,kpis:document.querySelectorAll('#ordKpis .kpi').length}));await page.screenshot({path:OUT+'04_erplink_orders.png',fullPage:true});
   await page.evaluate(()=>showTab('ship'));await page.waitForTimeout(600);const s=await page.evaluate(()=>({rows:document.querySelectorAll('#shipTbl tbody tr').length,asOf:document.getElementById('shipAsOf').textContent}));await page.screenshot({path:OUT+'05_erplink_ship.png',fullPage:true});
   if(!/待驗收|NOT TESTED/.test(o.asOf))throw new Error('acceptance label missing');return 'orders rows '+o.rows+' · ship rows '+s.rows+' · '+o.asOf.slice(0,80)});
 await test('Daily report draft renders for the previous workday from real sewing data; missing sections say 未齊; copy/export/version work',async()=>{await page.evaluate(()=>showTab('daily'));await page.waitForTimeout(800);const r=await page.evaluate(async()=>{const t=document.getElementById('dailyText').textContent;await saveDailyVersion();return {t,date:document.getElementById('dailyDate').value,versions:ERPLINK.DB.reports.length,metrics:ERPLINK.DAILY.report.metrics}});
   await page.screenshot({path:OUT+'06_erplink_daily.png',fullPage:true});if(!/VRT 生產早報/.test(r.t)||r.versions!==1)throw new Error(JSON.stringify(r).slice(0,300));return r.date+' · sewn '+r.metrics.sewn+' · '+r.t.split('\n')[3].slice(0,90)});
 await test('Telegram modal: ✈️ button opens, lists periods that hold ERP rows, preview text is the shared erplink builder',async()=>{await page.click('#vrtTgFab');await page.waitForTimeout(900);const r=await page.evaluate(()=>({open:document.getElementById('vrtTgModal').classList.contains('open'),opts:document.getElementById('vrtTgPeriod').options.length,txt:document.getElementById('vrtTgPreview').textContent.slice(0,120)}));await page.screenshot({path:OUT+'07_erplink_telegram.png'});await page.evaluate(()=>VRTTelegram.close());if(!r.open||!/ERP 對照/.test(r.txt))throw new Error(JSON.stringify(r));return 'periods '+r.opts+' · '+r.txt.replace(/\n/g,' ')});
 await test('Cloud: push → pull round trip against the real GAS code (v4.5, in-memory harness behind a route stub) keeps 4 orders + 2 shipments; second push uploads 0',async()=>{
   const {createGas}=require(ROOT+'qa/v41/gas_harness');const g=createGas();
   await page.route('https://script.google.com/**',async route=>{const req=route.request();const r=await g.fetch(req.url(),{method:req.method(),body:req.postData()||undefined});await route.fulfill({status:200,contentType:'application/json',body:await r.text()})});
   const r=await page.evaluate(async()=>{VRTPlatform.setGasUrl('https://script.google.com/macros/s/MOCK_ERPLINK/exec');const p1=await ERPLINK.cloudPush(true);await VRTProdStorage.replaceAll('VRT_ERPLink','erp_orders',[]);await ERPLINK.load();const before=ERPLINK.DB.orders.length;const pl=await ERPLINK.cloudPull(true);const after=ERPLINK.DB.orders.length;const p2=await ERPLINK.cloudPush(true);return {p1:p1&&p1.uploaded,before,after,ship:ERPLINK.DB.ship.length,pl:pl&&pl.downloaded,p2:p2&&p2.uploaded,p2ok:p2&&p2.ok,p2no:p2&&p2.noChange}});
   await page.unroute('https://script.google.com/**');const m=g.ctx.readSmartManifest_('erplink');const buckets=m?Object.keys(m.buckets):[];
   if(!(r.before===0&&r.after===4&&r.ship===2&&r.p2===0&&r.p2no))throw new Error(JSON.stringify(r)+' buckets '+buckets.join(','));return 'push '+r.p1+' · wiped → pull '+r.pl+' → 4 orders / 2 ship · second push 0 (no change) · GAS buckets '+buckets.join(',')});
 await test('EN and KM: the shared language layer translates the page (few Chinese nodes left)',async()=>{const COLLECT=`(()=>{const CJK=/[\\u3400-\\u9fff]/;let n=0;const w=document.createTreeWalker(document.body,4);let t;while((t=w.nextNode())){const v=t.nodeValue;if(!v||!CJK.test(v))continue;let e=t.parentElement,skip=false;for(;e;e=e.parentElement){if(/^(SCRIPT|STYLE|TEXTAREA|PRE|CODE|NOSCRIPT)$/.test(e.tagName)||e.hasAttribute('data-no-i18n'))skip=true}if(!skip&&t.parentElement.offsetParent)n++}return n})()`;
   await page.evaluate(()=>showTab('status'));await page.evaluate(()=>VRTI18n.set('en'));await page.waitForTimeout(2500);const en=await page.evaluate(COLLECT);await page.screenshot({path:OUT+'08_erplink_en.png',fullPage:true});await page.evaluate(()=>VRTI18n.set('km'));await page.waitForTimeout(2500);const km=await page.evaluate(COLLECT);await page.screenshot({path:OUT+'09_erplink_km.png'});await page.evaluate(()=>VRTI18n.set('zh'));await page.waitForTimeout(600);
   if(en>8||km>8)throw new Error('Chinese nodes left en '+en+' km '+km);return 'Chinese nodes left · en '+en+' · km '+km});
 await test('No page errors during the whole run',async()=>{if(errors.length)throw new Error(errors.join(' | '));return 'clean'});
 const pass=out.filter(x=>x.status==='PASS').length;console.log(pass+'/'+out.length+' PASS');fs.writeFileSync(path.resolve(__dirname,'browser_erp_link_results.json'),JSON.stringify(out,null,1));await browser.close();process.exit(pass===out.length?0:1);
})().catch(e=>{console.error(e);process.exit(1)});
