(function(g){'use strict';const C=VRTData39,I=VRTImport40,S=VRTProdStorage,DB='VRT_FinalQC',el=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>n==null?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:2}),pct=n=>n==null?'—':fmt(n*100)+'%';
 let records=[],sources=[],tab='dashboard',preview=[],previewSources=[],settings=JSON.parse(localStorage.getItem('vrt_qc_settings')||'{"rejectTarget":0.05,"efficiencyTarget":0.45}');
 const tabs=[['dashboard','📊 儀表板'],['import','📥 匯入／比對'],['daily','📋 每日報告'],['weekly','📅 週統計'],['trend','📈 月年趨勢'],['defects','🔍 缺點／根因'],['efficiency','🎯 效率報表'],['scenario','📐 SMV 情境'],['records','✏ 資料管理'],['history','🗂 歷史／備份']];
 const message=(s,bad=false)=>{el('qcMessage').className=s?'alert'+(bad?' bad':''):'';el('qcMessage').textContent=s};
 function range(){const a=el('qcDate').value||new Date().toISOString().slice(0,10),p=el('qcPeriod').value,d=new Date(a+'T12:00:00'),b=new Date(d);if(p==='all')return['0000','9999'];if(p==='week'){d.setDate(d.getDate()-(d.getDay()+6)%7);b.setTime(d.getTime());b.setDate(b.getDate()+6)}if(p==='month'){d.setDate(1);b.setMonth(b.getMonth()+1,0)}if(p==='year'){d.setMonth(0,1);b.setMonth(11,31)}const local=x=>[x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-');return[local(d),local(b)]}
 function filtered(){const [a,b]=range(),line=el('qcLine').value,q=el('qcSearch').value.toLowerCase();return records.filter(r=>!r.deleted&&r.date>=a&&r.date<=b&&(!line||r.line===line)&&(!q||[r.customer,r.po,r.line,r.notes,...(r.styles||[]).map(s=>s.style)].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||a.line.localeCompare(b.line,undefined,{numeric:true}))}
 async function load(){records=await S.all(DB,'records',{keyPath:'id'});sources=await S.all(DB,'sources',{keyPath:'id'});const latest=records.filter(r=>!r.deleted).map(r=>r.date).sort().pop();el('qcDate').value=latest||new Date().toISOString().slice(0,10);refresh()}
 async function save(dirty=true){const db=await S.ensure(DB,{records:{keyPath:'id'},sources:{keyPath:'id'}});try{await new Promise((res,rej)=>{const tx=db.transaction(['records','sources'],'readwrite');for(const [name,rows] of [['records',records],['sources',sources]]){const store=tx.objectStore(name);store.clear();rows.forEach(r=>store.put(r))}tx.oncomplete=res;tx.onabort=tx.onerror=()=>rej(tx.error||new Error('QC 儲存失敗'))})}finally{db.close()}if(dirty)g.VRTProdAutoSync?.markDirty('qc','save');refresh()}
 function table(head,rows){return '<div class="table-wrap"><table><thead><tr>'+head.map(h=>'<th>'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
 function kpis(a){return '<div class="kpis">'+[['有產出線別',a.lines],['檢驗量',a.inspected],['Reject',a.rejected],['良品 Output',a.output],['Reject %',pct(a.rejectRate)],['加權效率',pct(a.efficiency)]].map(([k,v])=>'<div class="kpi"><b>'+escape(typeof v==='number'?fmt(v):v)+'</b><span class="muted">'+k+'</span></div>').join('')+'</div>'}
 function toolbar(){return '<div class="toolbar bar"><button class="primary" onclick="QC.edit()">＋ 新增日報</button><button onclick="QC.export()">匯出 Excel</button><button onclick="QC.export(true)">匯出 CSV</button><button onclick="print()">列印／PDF</button></div>'}
 function rowButtons(r){return '<button onclick="QC.detail(\''+r.id+'\')">明細</button> <button onclick="QC.edit(\''+r.id+'\')">編輯</button> <button class="danger" onclick="QC.remove(\''+r.id+'\')">刪除</button>'}
 function groups(rows,key){const map=new Map();rows.forEach(r=>{const k=key(r);if(!map.has(k))map.set(k,[]);map.get(k).push(r)});return [...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([key,rs])=>({key,...I.qcTotals(rs)}))}
 function lineTable(rows){return table(['日期','線別','款式','檢驗','Reject','Output','Reject %','效率','操作'],rows.map(r=>[escape(r.date),escape(r.line),escape((r.styles||[]).map(s=>s.style).join(', ')),fmt(r.inspected),fmt(r.rejected),fmt(r.output),pct(r.inspected?r.rejected/r.inspected:null),pct(r.attendanceMinutes?r.producedMinutes/r.attendanceMinutes:null),rowButtons(r)]))}
 function defects(rows){const m=new Map();rows.forEach(r=>(r.defects||[]).forEach(d=>{const k=d.code+'|'+d.name,mr=m.get(k)||{code:d.code,name:d.name,qty:0};mr.qty+=Number(d.qty)||0;m.set(k,mr)}));return [...m.values()].sort((a,b)=>b.qty-a.qty)}
 function bars(rows){const max=Math.max(1,...rows.map(r=>r.qty));return rows.map(r=>'<div class="chart-row"><span>'+escape(r.name)+'</span><div class="track"><span style="width:'+r.qty/max*100+'%"></span></div><b>'+fmt(r.qty)+'</b></div>').join('')}
 function refresh(){const keep=el('qcLine').value;el('qcLine').innerHTML='<option value="">全部線別</option>'+[...new Set(records.filter(r=>!r.deleted).map(r=>r.line))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(l=>'<option value="'+escape(l)+'">'+escape(l)+'</option>').join('');el('qcLine').value=keep;el('qcLocal').textContent='本機已保存 '+records.filter(r=>!r.deleted).length+' 份線別日報';el('qcTabs').innerHTML=tabs.map(([k,t])=>'<button class="'+(k===tab?'active':'')+'" onclick="QC.tab(\''+k+'\')">'+t+'</button>').join('');const rs=filtered(),a=I.qcTotals(rs);let html='';
 if(tab==='import'){html='<section class="card"><h2>匯入 Final QC 報告</h2><label class="drop" ondragover="event.preventDefault()" ondrop="event.preventDefault();QC.importFiles(event.dataTransfer.files)">選擇或拖入 Excel／CSV／Email<input type="file" multiple accept=".xlsx,.xls,.xlsb,.csv,.json,.eml,.msg" onchange="QC.importFiles(this.files);this.value=\'\'"></label><p class="muted">依每張 Line 分頁的實際日期讀取；Summary 與 SMV 表用作核對，不重複計入。相同日／線別更新保留歷史，匯入部分線別保留其他線。</p><button onclick="QC.included()">📎 匯入本版隨附 9/17 QC 報告</button><div id="qcPreview"></div></section>'}
 else if(tab==='history'){html=toolbar()+'<section class="card"><h2>完整備份與原始附件</h2><button onclick="QC.backup()">下載完整 JSON 備份</button><p>Excel／CSV 匯入與相同報表更新都保留來源和修改歷史。</p>'+table(['原始附件','大小','下載'],sources.map(s=>[escape(s.name),fmt(s.size/1024)+' KB','<button onclick="QC.source(\''+s.id+'\')">原始檔案</button>']))+'</section><section class="card"><h2>修改歷史</h2>'+table(['日期／線','歷史版本數','狀態','操作'],records.filter(r=>(r.history||[]).length||r.deleted).map(r=>[escape(r.date+' '+r.line),fmt(r.history?.length),r.deleted?'已刪除':'保留中','<button onclick="QC.detail(\''+r.id+'\')">查看歷史</button>']))+'</section>'}
 else if(!rs.length)html=toolbar()+'<section class="card empty">此期間沒有 QC 日報。請選擇其他日期，或至「匯入／比對」匯入附件。</section>';
 else if(tab==='records')html=toolbar()+kpis(a)+lineTable(rs);
 else if(tab==='weekly'||tab==='trend'){const gs=groups(rs,r=>tab==='weekly'?r.date:el('qcPeriod').value==='year'?r.date.slice(0,7):r.date);html=toolbar()+kpis(a)+'<section class="card"><h2>期間趨勢</h2>'+table(['日期','檢驗量','Reject','Output','Reject %','加權效率'],gs.map(x=>[escape(x.key),fmt(x.inspected),fmt(x.rejected),fmt(x.output),pct(x.rejectRate),pct(x.efficiency)]))+'</section><section class="card">'+bars(gs.map(x=>({name:x.key,qty:x.rejected})))+'</section>'}
 else if(tab==='defects'){const ds=defects(rs),sum=ds.reduce((s,x)=>s+x.qty,0);html=toolbar()+kpis(a)+'<section class="card"><h2>缺點分布與根因</h2><p>同一缺點代碼但不同名稱分開計算。缺點占比＝該缺點次數／全部缺點次數。</p>'+bars(ds.filter(r=>r.qty).slice(0,12))+table(['代碼','缺點','次數','缺點占比'],ds.map(x=>[escape(x.code),escape(x.name),fmt(x.qty),pct(sum?x.qty/sum:null)]))+'</section><section class="card"><h2>根因／改善紀錄</h2>'+table(['日期／線別','備註','編輯'],rs.map(r=>[escape(r.date+' '+r.line),escape(r.notes),rowButtons(r)]))+'</section>'}
 else if(tab==='efficiency'){html=toolbar()+kpis(a)+'<section class="card"><h2>效率與目標</h2><p>目標效率 '+pct(settings.efficiencyTarget)+' · Reject 上限 '+pct(settings.rejectTarget)+'</p>'+table(['線別','出勤分鐘','產出分鐘','效率','Reject %','狀態'],groups(rs,r=>r.line).map(x=>[escape(x.key),fmt(x.attendanceMinutes),fmt(x.producedMinutes),pct(x.efficiency),pct(x.rejectRate),(x.efficiency!=null&&x.efficiency<settings.efficiencyTarget||x.rejectRate>settings.rejectTarget)?'<span class="bad">需改善</span>':'<span class="ok">達標／無異常</span>']))+'</section>'}
 else if(tab==='scenario'){html=toolbar()+'<section class="card"><h2>SMV 情境比較</h2><p>僅試算本報告的 SMV 調整對效率的影響；不更改正式 SMV、原始產量或報表歷史。</p>'+table(['SMV 調整','試算產出分鐘','試算效率'],[0,-.1,-.15,-.2,-.35].map(x=>[pct(x),fmt(a.producedMinutes*(1+x)),pct(a.attendanceMinutes?a.producedMinutes*(1+x)/a.attendanceMinutes:null)]))+'</section>'}
 else{const bad=rs.filter(r=>r.inspected&&r.rejected/r.inspected>settings.rejectTarget);html=toolbar()+kpis(a)+(bad.length?'<div class="alert">Reject 超過 '+pct(settings.rejectTarget)+'：'+bad.map(r=>escape(r.line)).join('、')+'</div>':'')+'<div class="grid">'+rs.map(r=>'<section class="card"><div class="bar"><h2>'+escape(r.line)+'</h2><span class="muted">'+escape(r.date)+'</span></div><p>'+escape((r.styles||[]).map(s=>s.style).join(' · ')||'未生產')+'</p><p>檢驗 <b>'+fmt(r.inspected)+'</b> · Reject <b>'+fmt(r.rejected)+'</b> · Output <b>'+fmt(r.output)+'</b></p><p>Reject '+pct(r.inspected?r.rejected/r.inspected:null)+' · 效率 '+pct(r.attendanceMinutes?r.producedMinutes/r.attendanceMinutes:null)+'</p>'+(r.issues||[]).map(x=>'<p class="bad">'+escape(x)+'</p>').join('')+rowButtons(r)+'</section>').join('')+'</div>'}
 el('qcContent').innerHTML=html;
 }
 function dialog(title,html){el('qcDialogTitle').textContent=title;el('qcDialogBody').innerHTML=html;el('qcDialog').showModal()}
 function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function b64(buf){const bytes=new Uint8Array(buf),a=[];for(let i=0;i<bytes.length;i+=16384)a.push(String.fromCharCode(...bytes.subarray(i,i+16384)));return btoa(a.join(''))}
 async function importFiles(files){await g.VRT_LOCAL_READY;preview=[];previewSources=[];let warnings=[];try{for(const file of files){const buffer=await file.arrayBuffer();if(/\.json$/i.test(file.name)){const data=JSON.parse(new TextDecoder().decode(buffer));if(!Array.isArray(data.records))throw new Error('不是 QC 備份');data.records.forEach(I.validateQC);preview.push(...data.records);previewSources.push(...data.sources||[]);continue}const inputs=/\.(eml|msg)$/i.test(file.name)?await mailFiles(file,buffer):[{name:file.name,buffer}];for(const f of inputs){const wb=XLSX.read(new Uint8Array(f.buffer),{type:'array',raw:true,cellDates:false}),p=I.qc(wb,f.name);preview.push(...p.records);warnings.push(...p.warnings)}previewSources.push({id:'QCS-'+C.hash(b64(buffer)),name:file.name,size:buffer.byteLength,base64:b64(buffer)})}const diff=I.qcMerge(records,preview);const totals=I.qcTotals(preview);tab='import';refresh();el('qcPreview').innerHTML='<h2 style="margin-top:22px">解析與差異預覽</h2>'+kpis(totals)+'<p>新增 '+diff.added+' · 更新 '+diff.updated+' · 相同略過 '+diff.unchanged+'</p>'+warnings.map(w=>'<p class="bad">'+escape(w)+'</p>').join('')+table(['日期','線別','檢驗','Reject','Output'],preview.map(r=>[escape(r.date),escape(r.line),fmt(r.inspected),fmt(r.rejected),fmt(r.output)]))+'<div class="toolbar"><button class="primary" onclick="QC.commit()">確認儲存</button> <button onclick="QC.cancelImport()">取消</button></div>';message('解析完成，確認儲存後才會更新資料。')}catch(e){message('匯入失敗：'+e.message,true)}}
 async function commit(){const before=C.copy(records),beforeSources=C.copy(sources);try{const diff=I.qcMerge(records,preview);records=diff.records;sources=[...new Map([...sources,...previewSources].map(r=>[r.id,r])).values()];await save();el('qcDate').value=preview.map(r=>r.date).sort().pop()||el('qcDate').value;preview=[];previewSources=[];el('qcLine').value='';el('qcSearch').value='';el('qcPeriod').value='day';tab='daily';refresh();message('已儲存：新增 '+diff.added+'、更新 '+diff.updated+'、略過 '+diff.unchanged)}catch(e){records=before;sources=beforeSources;message('儲存失敗：'+e.message,true)}}
 async function mailFiles(file,buf){let out=[];if(/\.msg$/i.test(file.name)){const c=XLSX.CFB.read(new Uint8Array(buf),{type:'array'});for(let i=0;i<c.FullPaths.length;i++){if(!/__substg1.0_37010102$/.test(c.FullPaths[i]))continue;const root=c.FullPaths[i].replace(/__substg.*$/,''),find=code=>c.FileIndex[c.FullPaths.findIndex(p=>p===root+'__substg1.0_'+code)]?.content;const nameData=find('3707001F')||find('3704001F');const name=nameData?new TextDecoder('utf-16le').decode(new Uint8Array(nameData)).replace(/\0/g,''):'';if(/\.(xlsx?|xlsb|csv)$/i.test(name))out.push({name,buffer:new Uint8Array(c.FileIndex[i].content)})}}else{const text=new TextDecoder().decode(buf),boundary=text.match(/boundary\s*=\s*"?([^"\r\n;]+)/i)?.[1];if(!boundary)throw new Error('Email 缺少 MIME boundary');for(const part of text.split('--'+boundary)){const name=part.match(/(?:filename|name)\s*=\s*"?([^"\r\n;]+\.(?:xlsx?|xlsb|csv))/i)?.[1],body=part.split(/\r?\n\r?\n/).slice(1).join('\n\n');if(name&&/content-transfer-encoding:\s*base64/i.test(part))out.push({name,buffer:Uint8Array.from(atob(body.replace(/\s/g,'')),c=>c.charCodeAt(0))})}}if(!out.length)throw new Error('Email 沒有可辨識的 Excel 附件，請將 Excel 另存後匯入');return out}
 function detail(id){const r=records.find(r=>r.id===id);if(!r)return;dialog(r.date+' · '+r.line,kpis(I.qcTotals([r]))+'<p>來源 '+escape(r.sourceFile)+' · '+escape(r.sourceSheet)+'</p><p>'+escape(r.notes)+'</p><h2>款式／SMV／產出</h2>'+table(['款式','SMV','良品 Output','產出分鐘'],(r.styles||[]).map(s=>[escape(s.style),fmt(s.smv),fmt(s.output),fmt(s.minutes)]))+'<h2>時段檢驗</h2>'+table(['時段','檢驗','Reject'],(r.intervals||[]).map(x=>[escape(x.time),fmt(x.inspected),fmt(x.rejected)]))+'<h2>缺點與逐時分布</h2>'+table(['代碼','缺點','次數','時段'],(r.defects||[]).map(d=>[escape(d.code),escape(d.name),fmt(d.qty),escape((d.hourly||[]).filter(h=>h.qty).map(h=>h.time+': '+h.qty).join(' / '))]))+'<details><summary>修改歷史 '+(r.history||[]).length+'</summary>'+table(['版本','日期／時間','檢驗','Reject','操作'],(r.history||[]).map((h,i)=>[i+1,escape(h.updatedAt||h.date),fmt(h.inspected),fmt(h.rejected),'<button onclick="QC.restore(\''+id+'\','+i+')">恢復此版</button>']))+'</details>')}
 const detailSpecs={styles:[['style','款式','text'],['smv','SMV','number'],['output','Output','number']],defects:[['code','代碼','text'],['name','缺點名稱','text'],['qty','次數','number']],intervals:[['time','時段','text'],['inspected','檢驗量','number'],['rejected','Reject','number']]};
 function detailRow(kind,r={}){return '<tr data-qc-kind="'+kind+'">'+detailSpecs[kind].map(([k,label,type])=>'<td><input aria-label="'+label+'" data-field="'+k+'" type="'+type+'" step="any" min="0" value="'+escape(r[k]??'')+'"></td>').join('')+'<td><button type="button" class="danger" onclick="this.closest(\'tr\').remove()">刪除</button></td></tr>'}
 function detailEditors(r){return '<details><summary>款式、缺點與時段明細</summary>'+Object.keys(detailSpecs).map(kind=>'<section class="card"><h3>'+({styles:'款式產出',defects:'缺點明細',intervals:'時段檢驗'}[kind])+'</h3><div class="table-wrap"><table><thead><tr>'+detailSpecs[kind].map(x=>'<th>'+x[1]+'</th>').join('')+'<th>操作</th></tr></thead><tbody id="qcEdit-'+kind+'">'+(r[kind]||[]).map(x=>detailRow(kind,x)).join('')+'</tbody></table></div><button type="button" onclick="QC.addDetail(\''+kind+'\')">＋ 新增</button></section>').join('')+'</details>'}
 function readDetailEditors(form,prior){const out={};for(const kind of Object.keys(detailSpecs)){out[kind]=[...form.querySelectorAll('tr[data-qc-kind="'+kind+'"]')].map(tr=>{const r={};for(const [k,,type] of detailSpecs[kind]){const v=tr.querySelector('[data-field="'+k+'"]').value.trim();r[k]=type==='number'?C.number(v):v;if(type==='number'&&(r[k]==null||r[k]<0))throw new Error('請填寫有效的明細數量／SMV')}if(kind==='styles'){if(!r.style||!Number.isInteger(r.output))throw new Error('款式不可空白，Output 須為整數');r.minutes=r.smv*r.output}else if(kind==='defects'){if(!r.name||!Number.isInteger(r.qty))throw new Error('缺點名稱不可空白，次數須為整數');const old=(prior.defects||[]).find(d=>d.code===r.code&&d.name===r.name);r.hourly=old&&old.qty===r.qty?old.hourly:[]}else if(!r.time||r.rejected>r.inspected||!Number.isInteger(r.inspected)||!Number.isInteger(r.rejected))throw new Error('請核對時段及檢驗／Reject 件數');return r})}return out}
 function edit(id){const r=records.find(r=>r.id===id)||{date:el('qcDate').value,line:'',inspected:0,rejected:0,output:0},fields=[['date','日期','date'],['line','線別','text'],['customer','客戶','text'],['po','PO','text'],['inspected','檢驗量','number'],['rejected','Reject 件數','number'],['output','良品 Output','number'],['workers','出勤人數','number'],['attendanceMinutes','出勤分鐘','number'],['producedMinutes','產出分鐘','number']];dialog(id?'編輯日報':'新增日報','<form id="qcEditForm"><div class="fields">'+fields.map(([k,label,t])=>'<label>'+label+'<input name="'+k+'" type="'+t+'" step="any" '+(['date','line','inspected','rejected','output'].includes(k)?'required':'')+' value="'+escape(r[k]??'')+'"></label>').join('')+'</div><label>根因／改善／備註<textarea name="notes">'+escape(r.notes)+'</textarea></label>'+detailEditors(r)+'<button class="primary" type="submit">儲存</button></form>');el('qcEditForm').onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(e.target)),x={...r,...values};for(const [k,,t] of fields)if(t==='number')x[k]=C.number(x[k]);Object.assign(x,readDetailEditors(e.target,r));I.validateQC(x);if(x.output!==x.inspected-x.rejected)throw new Error('Output 應等於檢驗量減 Reject；請核對');if(x.styles.length){const out=x.styles.reduce((s,v)=>s+v.output,0);if(out!==x.output)throw new Error('款式 Output 加總與總數不符');x.producedMinutes=x.styles.reduce((s,v)=>s+v.minutes,0)}x.id='QC-'+C.hash([x.date,C.norm(x.line)]);if(records.some(z=>z.id!==id&&!z.deleted&&z.date===x.date&&C.norm(z.line)===C.norm(x.line)))throw new Error('此日期及線別已有日報，請編輯原紀錄');if(id)x.history=[...(r.history||[]),{...r,history:undefined}];x.updatedAt=new Date().toISOString();if(id&&x.id!==id){records[records.indexOf(r)]={...r,deleted:true,updatedAt:x.updatedAt};records.push(x)}else if(id)records[records.indexOf(r)]=x;else records.push(x);await save();el('qcDialog').close();message('已儲存')}catch(e){message(e.message,true);alert(e.message)}}}
 async function remove(id){if(!confirm('刪除此線別日報？原資料保留在歷史，可還原。'))return;const r=records.find(x=>x.id===id);r.history=[...(r.history||[]),{...r,history:undefined}];r.deleted=true;r.updatedAt=new Date().toISOString();await save()}
 function exportFile(csv=false){const rows=filtered().map(r=>({ID:r.id,Date:r.date,Line:r.line,Customer:r.customer||'',PO:r.po||'',Inspected:r.inspected,Rejected:r.rejected,Output:r.output,'Reject %':r.inspected?r.rejected/r.inspected:'','Attendance Minutes':r.attendanceMinutes,'Produced Minutes':r.producedMinutes,Notes:r.notes,'Record JSON':JSON.stringify({...r,history:[]})})),w=XLSX.utils.book_new();if(!rows.length)return message('此期間無資料可匯出');const sheet=XLSX.utils.json_to_sheet(rows);if(csv){const keys=Object.keys(rows[0]);download('VRT_QC_'+el('qcDate').value+'.csv','\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8')}else{XLSX.utils.book_append_sheet(w,sheet,'QC Records');XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(filtered().flatMap(r=>(r.styles||[]).map(s=>({Date:r.date,Line:r.line,...s})))),'Styles');XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(filtered().flatMap(r=>(r.defects||[]).map(d=>({Date:r.date,Line:r.line,Code:d.code,Defect:d.name,Qty:d.qty})))),'Defects');XLSX.writeFile(w,'VRT_QC_'+el('qcDate').value+'.xlsx')}}
 function settingsPanel(){dialog('目標與共用雲端設定','<form id="qcSettings"><label>共用 GAS URL<input name="url" value="'+escape(VRTPlatform.getGasUrl())+'" placeholder="/exec URL"></label><div class="fields"><label>Reject 上限 %<input name="reject" type="number" min="0" max="100" step="0.1" value="'+settings.rejectTarget*100+'"></label><label>效率目標 %<input name="eff" type="number" min="0" step="0.1" value="'+settings.efficiencyTarget*100+'"></label></div><button class="primary">儲存</button></form>');el('qcSettings').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{if(d.url.trim())VRTPlatform.setGasUrl(d.url);settings={rejectTarget:Number(d.reject)/100,efficiencyTarget:Number(d.eff)/100};localStorage.setItem('vrt_qc_settings',JSON.stringify(settings));el('qcDialog').close();refresh()}catch(e){alert(e.message)}}}
 const cloudRows=()=>records.concat(sources.map(s=>({id:s.id,_vrtEntity:'qc.source',_vrtValue:s})));
 async function sync(dir){await g.VRT_LOCAL_READY;const url=VRTPlatform.getGasUrl();if(!url){message('尚未找到共用 GS 連線設定，請在平台設定一次；QC 會自動沿用。',true);return false}try{let r;if(dir==='push')r=await VRTSmartSync.push({url,tool:'qc',records:cloudRows(),meta:{schemaVersion:40}});else r=await VRTSmartSync.pull({url,tool:'qc',localRecords:cloudRows(),meta:{schemaVersion:40},apply:async rows=>{const remote=rows.filter(r=>!r._vrtEntity),map=new Map(records.map(r=>[r.id,r]));for(const x of remote){const prior=map.get(x.id);if(!prior||String(x.updatedAt||'')>=String(prior.updatedAt||''))map.set(x.id,x)}records=[...map.values()];sources=[...new Map([...sources,...rows.filter(r=>r._vrtEntity==='qc.source').map(r=>r._vrtValue)].map(r=>[r.id,r])).values()];await save(false);return cloudRows()}});if(r.needsPull)message('雲端有變更，請先 Pull 後再 Push。');return r}catch(e){message('雲端 '+dir+' 失敗：'+e.message,true);throw e}}
 g.QC={refresh,tab:k=>{tab=k;if(k==='daily')el('qcPeriod').value='day';if(k==='weekly')el('qcPeriod').value='week';if(k==='trend')el('qcPeriod').value='month';refresh()},shift:n=>{const d=new Date(el('qcDate').value+'T12:00:00'),p=el('qcPeriod').value;if(p==='month'){d.setDate(1);d.setMonth(d.getMonth()+n)}else if(p==='year')d.setFullYear(d.getFullYear()+n);else d.setDate(d.getDate()+n*(p==='week'?7:1));el('qcDate').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');refresh()},importFiles,commit,addDetail:kind=>{el('qcEdit-'+kind).insertAdjacentHTML('beforeend',detailRow(kind))},cancelImport:()=>{preview=[];previewSources=[];refresh();message('已取消')},edit,detail,remove,export:exportFile,settings:settingsPanel,sync,backup:()=>download('VRT_QC_Backup.json',JSON.stringify({schemaVersion:40,records,sources},null,2)),source:id=>{const s=sources.find(s=>s.id===id);if(s)download(s.name,Uint8Array.from(atob(s.base64),c=>c.charCodeAt(0)),'application/octet-stream')},restore:async(id,i)=>{if(!confirm('恢復此歷史版本？'))return;const r=records.find(r=>r.id===id),x=C.copy(r.history[i]);x.id=id;x.deleted=false;x.updatedAt=new Date().toISOString();x.history=[...r.history,{...r,history:undefined}];records[records.indexOf(r)]=x;await save();el('qcDialog').close()},included:async()=>{try{const r=await fetch('release_sources/Final_QC_20260917.xlsx');if(!r.ok)throw new Error('HTTP '+r.status);const bytes=await r.arrayBuffer();await importFiles([{name:'Final_Qc_Inspection_Report_by_Line_as_of_17_September_2026.xlsx',arrayBuffer:async()=>bytes}])}catch(e){message(e.message,true)}},getState:()=>C.copy({records,sources}),applyRecords:async rows=>{records=I.qcMerge(records,rows).records;await save(false)}};
 g.VRT_LOCAL_READY=load().catch(e=>{message('讀取本機資料失敗：'+e.message,true);throw e});VRTProdAutoSync.install({key:'qc',lockKey:'qc',canSync:()=>!!VRTPlatform.getGasUrl(),pull:()=>sync('pull'),push:()=>sync('push'),watch:false,startDelay:1800});
})(window);
