(function(g){'use strict';
const C=VRTData39,I=VRTImport40,S=VRTProdStorage,DB='VRT_FinalQC',el=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),arg=s=>escape(JSON.stringify(s)),fmt=n=>n==null?'—':Number(n).toLocaleString('en-US',{maximumFractionDigits:2}),pct=n=>n==null?'—':fmt(n*100)+'%',lineName=s=>s==='SAMPLELINE'?'Sample Line':s;
let records=[],sources=[],tab='dashboard',preview=[],previewSources=[],previewWarnings=[],importResults=[],importing=false,saving=false,settings={rejectTarget:.05,efficiencyTarget:.45};
try{Object.assign(settings,JSON.parse(localStorage.getItem('vrt_qc_settings')||'{}'))}catch(_){}
const tabs=[['dashboard','📊 儀表板'],['import','📥 上傳報表'],['daily','📋 每日報告'],['weekly','📅 週統計'],['trend','📈 月年趨勢'],['defects','🎯 缺點＆根因'],['efficiency','📉 效率報表'],['scenario','📐 SMV 情境比較'],['validate','🔎 數據比對'],['styles','👕 款式追蹤'],['records','✏ 資料管理'],['report','📝 週報匯出'],['history','🗂 歷史／備份']];
const kindName=r=>({weekly:'週報',manual:'線上修訂',daily:'日報'}[r.reportKind]||'日報'),message=(s,bad=false)=>{el('qcMessage').className=s?'alert'+(bad?' bad':''):'';el('qcMessage').textContent=s};
function range(){const a=el('qcDate').value||new Date().toISOString().slice(0,10),p=el('qcPeriod').value,d=new Date(a+'T12:00:00'),b=new Date(d);if(p==='all')return['0000','9999'];if(p==='week'){d.setDate(d.getDate()-(d.getDay()+6)%7);b.setTime(d.getTime());b.setDate(b.getDate()+6)}if(p==='month'){d.setDate(1);b.setMonth(b.getMonth()+1,0)}if(p==='year'){d.setMonth(0,1);b.setMonth(11,31)}const local=x=>[x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-');return[local(d),local(b)]}
function filtered(){const [a,b]=range(),line=el('qcLine').value,q=el('qcSearch').value.toLowerCase();return records.filter(r=>!r.deleted&&r.date>=a&&r.date<=b&&(!line||r.line===line)&&(!q||[r.customer,r.po,r.line,r.notes,...(r.styles||[]).map(s=>s.style),...(r.defects||[]).filter(d=>d.qty>0).map(d=>d.name+' '+d.code)].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||a.line.localeCompare(b.line,undefined,{numeric:true}))}
async function load(){records=await S.all(DB,'records',{keyPath:'id'});sources=await S.all(DB,'sources',{keyPath:'id'});const latest=records.filter(r=>!r.deleted).map(r=>r.date).sort().pop();el('qcDate').value=latest||new Date().toISOString().slice(0,10);refresh()}
async function save(dirty=true){const db=await S.ensure(DB,{records:{keyPath:'id'},sources:{keyPath:'id'}});try{await new Promise((res,rej)=>{const tx=db.transaction(['records','sources'],'readwrite');for(const [name,rows] of [['records',records],['sources',sources]]){const store=tx.objectStore(name);store.clear();rows.forEach(r=>store.put(r))}tx.oncomplete=res;tx.onabort=tx.onerror=()=>rej(tx.error||new Error('QC 儲存失敗'))})}finally{db.close()}if(dirty)g.VRTProdAutoSync?.markDirty('qc','save');refresh()}
function table(head,rows){return '<div class="table-wrap" tabindex="0" role="region" aria-label="可左右捲動的資料表"><table><thead><tr>'+head.map(h=>'<th scope="col">'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+head.length+'" class="muted">此期間沒有明細</td></tr>')+'</tbody></table></div>'}
function kpis(a){return '<div class="kpis">'+[['檢驗線數',fmt(a.lines),'有檢驗紀錄'],['合計檢驗量',fmt(a.inspected),'件'],['不良件數',fmt(a.rejected),'Reject'],['實際產出',fmt(a.output),'Output'],['不良率',pct(a.rejectRate),'按件數加權'],['加權效率',pct(a.efficiency),a.efficiencyNeeded>a.efficiencyKnown?'分鐘完整 '+a.efficiencyKnown+'/'+a.efficiencyNeeded:'依出勤／產出分鐘']].map(([k,v,h])=>'<div class="kpi"><b>'+v+'</b><span>'+k+'</span><small>'+h+'</small></div>').join('')+'</div>'}
function toolbar(){return '<div class="toolbar"><button class="primary" onclick="QC.edit()">＋ 新增日報</button><button onclick="QC.export()">↓ Excel</button><button onclick="QC.export(true)">↓ CSV</button><button onclick="print()">列印／PDF</button><span class="muted">匯出目前篩選範圍 · 表格可左右滑動</span></div>'}
function rowButtons(r){return '<button onclick="QC.detail('+arg(r.id)+')">明細</button> <button onclick="QC.edit('+arg(r.id)+')">編輯</button> <button class="danger" onclick="QC.remove('+arg(r.id)+')">刪除</button>'}
function groups(rows,key){const map=new Map();rows.forEach(r=>{const k=key(r);if(!map.has(k))map.set(k,[]);map.get(k).push(r)});return [...map].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true})).map(([key,rs])=>({key,...I.qcTotals(rs)}))}
function eff(r){return r.attendanceMinutes>0&&r.producedMinutes!=null?r.producedMinutes/r.attendanceMinutes:r.reportedEfficiency??null}
function lineTable(rows){return table(['日期','線別','來源','款式','檢驗','不良','實際產出','未完成產出差額','不良率','效率','操作'],rows.map(r=>[escape(r.date),escape(lineName(r.line)),kindName(r),escape((r.styles||[]).map(s=>s.style).join(', ')||(r.reportKind==='weekly'?'週報未提供款式':'—')),fmt(r.inspected),fmt(r.rejected),fmt(r.output),fmt(r.inspected-r.rejected-r.output),pct(r.inspected?r.rejected/r.inspected:null),pct(eff(r))+(r.reportKind==='weekly'?' <span class="muted">原報</span>':''),rowButtons(r)]))}
function defects(rows){const m=new Map();rows.forEach(r=>(r.defects||[]).forEach(d=>{const k=d.code+'|'+d.name,mr=m.get(k)||{code:d.code,name:d.name,qty:0};mr.qty+=Number(d.qty)||0;m.set(k,mr)}));return [...m.values()].sort((a,b)=>b.qty-a.qty)}
function bars(rows){const max=Math.max(1,...rows.map(r=>r.qty));return rows.length?rows.map(r=>'<div class="chart-row"><span title="'+escape(r.name)+'">'+escape(r.name)+'</span><div class="track"><span style="width:'+Math.max(0,r.qty/max*100)+'%"></span></div><b>'+fmt(r.qty)+'</b></div>').join(''):'<p class="muted">此期間無缺點紀錄</p>'}
function section(title,body,extra=''){return '<section class="card"><div class="section-heading"><h2>'+title+'</h2>'+extra+'</div>'+body+'</section>'}
function chart(gs){if(!gs.length)return '';const width=680,height=190,left=52,right=16,top=16,bottom=32,max=Math.max(1,...gs.map(x=>x.inspected)),x=i=>left+(width-left-right)*(gs.length===1?.5:i/(gs.length-1)),y=v=>top+(height-top-bottom)*(1-v/max);let svg='<svg class="trend-chart" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="按日期排列的檢驗量與實際產出趨勢圖">';for(let i=0;i<=3;i++){const v=max*i/3;svg+='<line x1="'+left+'" x2="'+(width-right)+'" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#e2e6f0"/><text x="'+(left-8)+'" y="'+(y(v)+4)+'" text-anchor="end" fill="#6b7a9e" font-size="10">'+fmt(Math.round(v))+'</text>'}for(const [k,color] of [['inspected','#2563eb'],['output','#f59e0b']]){svg+='<polyline points="'+gs.map((r,i)=>x(i)+','+y(r[k])).join(' ')+'" fill="none" stroke="'+color+'" stroke-width="2.5"/>';gs.forEach((r,i)=>{svg+='<circle cx="'+x(i)+'" cy="'+y(r[k])+'" r="3.5" fill="'+color+'"><title>'+escape(r.key)+' '+(k==='inspected'?'檢驗':'產出')+' '+fmt(r[k])+'</title></circle>'})}gs.forEach((r,i)=>{if(i%Math.ceil(gs.length/8)===0||i===gs.length-1)svg+='<text x="'+x(i)+'" y="'+(height-9)+'" text-anchor="middle" fill="#6b7a9e" font-size="10">'+escape(r.key.length===10?r.key.slice(5):r.key)+'</text>'});return '<div class="chart-legend"><span><i style="background:#2563eb"></i>檢驗量</span><span><i style="background:#f59e0b"></i>實際產出</span></div>'+svg+'</svg>'}
function notices(a){return (a.reconciliationGap?'<div class="info">📦 檢驗扣除不良後，有 <b>'+fmt(a.reconciliationGap)+'</b> 件尚未列入實際產出。保留原報 Output；請查看半成品／未完成產出備註。</div>':'')+(a.efficiencyNeeded>a.efficiencyKnown?'<div class="info">部分週報沒有出勤與產出分鐘，加權效率暫不顯示。各線原報效率仍可查看；已有完整分鐘 '+a.efficiencyKnown+'／'+a.efficiencyNeeded+' 份。</div>':'')}
function lineCards(rs){return '<div class="grid">'+rs.map(r=>{const rate=r.inspected?r.rejected/r.inspected:null,e=eff(r),state=rate==null?'zero':rate>settings.rejectTarget?'lo':e!=null&&e<settings.efficiencyTarget?'md':'hi',styles=r.styles||[];return '<section class="line-card '+state+'"><div class="line-title"><h3>'+escape(lineName(r.line))+'</h3><span class="rate-badge" title="不良率">'+pct(rate)+'</span></div><span class="tag '+(r.reportKind||'daily')+'">'+kindName(r)+' · '+escape(r.date)+'</span><div class="line-stats"><div class="line-stat"><b>'+fmt(r.inspected)+'</b><span>🔎 檢驗量</span></div><div class="line-stat"><b>'+fmt(r.output)+'</b><span>📦 實際產出</span></div></div><div class="mini-row"><span>不良件數</span><strong class="bad">'+fmt(r.rejected)+' 件</strong></div><div class="mini-row"><span>'+(r.reportKind==='weekly'?'原報效率':'效率')+'</span><strong>'+pct(e)+'</strong></div><div class="eff-track"><i style="width:'+Math.min(100,Math.max(0,(e||0)*100))+'%"></i></div><div class="mini-row muted"><span>效率目標 '+pct(settings.efficiencyTarget)+'</span><span>不良上限 '+pct(settings.rejectTarget)+'</span></div><div class="line-styles"><span class="muted">'+(styles.length?'款式明細':r.reportKind==='weekly'?'週報未提供款式／人數':'未列款式')+'</span>'+styles.slice(0,5).map(s=>'<p><span>'+escape(s.style)+'</span><b>'+fmt(s.output)+' 件</b></p>').join('')+(styles.length>5?'<p class="muted">另有 '+(styles.length-5)+' 款，點明細查看</p>':'')+'</div>'+((r.issues||[]).length?'<div class="issue">'+escape(r.issues[0])+'</div>':'')+'<div class="line-buttons">'+rowButtons(r)+'</div></section>'}).join('')+'</div>'}
function renderImport(){return '<div class="import-intro"><div><h2>📥 上傳 QC 日報／週報</h2><p>讀取各線實際日期、檢驗量、不良、產出與缺點。支援 Final QC 線別日報與 Weekly End-Line 週報；重疊日期只保留一份計算資料，完整日報優先。</p></div><span class="import-mark">📊</span></div><div class="step-list"><span><b>1</b>選擇檔案</span><span><b>2</b>檢查筆數與差異</span><span><b>3</b>確認儲存</span></div><div class="g2"><section class="card"><div class="drop" ondragover="event.preventDefault();this.classList.add(\'drag\')" ondragleave="this.classList.remove(\'drag\')" ondrop="event.preventDefault();this.classList.remove(\'drag\');QC.importFiles(event.dataTransfer.files)"><div class="drop-icon">📊</div><h3>Excel／CSV 報表</h3><p>拖入檔案，或一次選擇多份日報與週報</p><input id="qcExcelFiles" type="file" multiple accept=".xlsx,.xls,.xlsb,.csv,.json" onchange="QC.onFileInput(this)"><button class="primary" onclick="QC.choose(\'qcExcelFiles\')" '+(importing?'disabled':'')+'>選擇 Excel／CSV 檔案</button><div class="file-status">.xlsx · .xls · .xlsb · .csv · JSON 備份</div></div></section><section class="card"><div class="drop" ondragover="event.preventDefault()" ondrop="event.preventDefault();QC.importFiles(event.dataTransfer.files)"><div class="drop-icon">✉️</div><h3>Email 郵件附件</h3><p>直接選擇 Outlook 郵件，自動讀取 Excel 附件</p><input id="qcMailFiles" type="file" multiple accept=".msg,.eml" onchange="QC.onFileInput(this)"><button onclick="QC.choose(\'qcMailFiles\')" '+(importing?'disabled':'')+'>選擇郵件檔案</button><div class="file-status">.msg · .eml</div></div></section></div><section class="card"><div class="section-heading"><h2>解析與差異預覽</h2><span class="muted">'+(importing?'讀取中…':importResults.length?importResults.length+' 個檔案':'尚未選擇檔案')+'</span></div><div id="qcPreview"></div></section><details><summary>本版隨附的 QC 原始報表</summary><div class="toolbar"><button onclick="QC.included(\'latest\')">匯入 9/22 日報</button><button onclick="QC.included(\'daily\')">匯入 9/19 日報</button><button onclick="QC.included(\'weekly\')">匯入 9/14–9/19 週報</button><button onclick="QC.included(\'previous\')">匯入 9/17 日報</button></div></details>'}
function previewHTML(){let html='<div class="file-list">'+importResults.map(r=>'<div class="file-row"><span>📄</span><div class="file-name">'+escape(r.name)+'<span class="muted">'+escape(r.detail||'等待讀取')+'</span></div><span class="status-tag '+(r.error?'error':'')+'">'+(r.error?'讀取失敗':r.pending?'處理中':r.count+' 份')+'</span></div>').join('')+'</div>';if(!preview.length)return html+'<p class="muted">'+(importing?'正在讀取報表，完成後將顯示筆數與來源。':importResults.length?'沒有可儲存的資料，請查看上方錯誤原因。':'選擇檔案後，在這裡核對日期、線別及資料差異。')+'</p>';const unique=I.qcMerge([],preview).records,diff=I.qcMerge(records,unique),tot=I.qcTotals(unique);html+='<div class="preview-actions"><strong>已解析 '+unique.length+' 份，尚待儲存</strong><button class="primary" onclick="QC.commit()" '+(importing||saving?'disabled':'')+'>✓ 確認儲存</button></div>'+kpis(tot)+'<div class="data-summary"><span>新增 <b>'+diff.added+'</b></span><span>更新 <b>'+diff.updated+'</b></span><span>相同略過 <b>'+diff.unchanged+'</b></span><span>保留較完整資料 <b>'+diff.protected+'</b></span></div>';
if(previewWarnings.length)html+='<details open><summary>來源核對提醒 '+previewWarnings.length+' 項</summary><div class="info">'+[...new Set(previewWarnings)].map(escape).join('<br>')+'</div></details>';
html+='<details><summary>展開 '+unique.length+' 份日期／線別明細</summary>'+table(['日期','線別','來源','檢驗','不良','實際產出','未完成產出差額'],unique.map(r=>[escape(r.date),escape(lineName(r.line)),kindName(r),fmt(r.inspected),fmt(r.rejected),fmt(r.output),fmt(r.inspected-r.rejected-r.output)]))+'</details><div class="preview-actions"><p>相同日／線別不重複計算；只匯入部分線別時，其他資料會保留。'+(importResults.some(r=>r.error)?'<b class="bad"> 失敗的檔案不會儲存。</b>':'')+'</p><button class="primary" onclick="QC.commit()" '+(importing||saving?'disabled':'')+'>✓ 確認儲存 '+unique.length+' 份</button><button onclick="QC.cancelImport()" '+(importing||saving?'disabled':'')+'>取消</button></div>';return html}
function validation(rows){const comparisons=rows.flatMap(r=>(r.sourceComparisons||[]).map(s=>({r,s}))),issues=rows.flatMap(r=>(r.issues||[]).map(text=>({r,text})));return section('日報／週報交叉比對','<p class="muted">依日期與線別比對；完整日報優先。下列來源只供核對，不會重複加總。</p>'+table(['日期／線別','採用來源','檢驗／不良／產出','比對來源','原報檢驗／不良／產出','核對結果'],comparisons.map(({r,s})=>[escape(r.date+' '+lineName(r.line)),kindName(r),[r.inspected,r.rejected,r.output].map(fmt).join(' / '),escape(s.sourceFile||kindName({reportKind:s.kind})),[s.inspected,s.rejected,s.output].map(fmt).join(' / '),['inspected','rejected','output'].every(k=>r[k]===s[k])?'<span class="ok">數量一致</span>':'<span class="bad">數量有差異 · 保留明細版本</span>'])))+section('原表日期、計算與明細核對',table(['日期／線別','核對提醒','操作'],issues.map(({r,text})=>[escape(r.date+' '+lineName(r.line)),'<div class="table-note">'+escape(text)+'</div>',rowButtons(r)])))}
function styleView(rows){const map=new Map();for(const r of rows)for(const s of r.styles||[]){const key=s.style+'|'+s.smv,x=map.get(key)||{style:s.style,smv:s.smv,output:0,minutes:0,lines:new Set(),dates:new Set()};x.output+=s.output;x.minutes+=s.minutes??s.output*s.smv;x.lines.add(lineName(r.line));x.dates.add(r.date);map.set(key,x)}return section('款式產出與報表 SMV','<p class="muted">報表 SMV 僅供 QC 產出分析；正式 IE／SMV 維持共用來源。週報未提供款式時，不補造款式產量。</p>'+table(['款式','參考 SMV','實際產出','產出分鐘','線別','報告天數'],[...map.values()].sort((a,b)=>b.output-a.output).map(s=>[escape(s.style),fmt(s.smv),fmt(s.output),fmt(s.minutes),escape([...s.lines].join('、')),s.dates.size])))}
function refresh(){const keep=el('qcLine').value;el('qcLine').innerHTML='<option value="">全部線別</option>'+[...new Set(records.filter(r=>!r.deleted).map(r=>r.line))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(l=>'<option value="'+escape(l)+'">'+escape(lineName(l))+'</option>').join('');el('qcLine').value=keep;const active=records.filter(r=>!r.deleted),latest=active.map(r=>r.date).sort().pop();el('qcLocal').textContent='本機已保存 '+active.length+' 份線別日報 · '+sources.length+' 個原始檔案';el('qcHReports').textContent=fmt(active.length);el('qcHDates').textContent=fmt(new Set(active.map(r=>r.date)).size);el('qcHLatest').textContent=latest||'—';el('qcTabs').innerHTML=tabs.map(([k,t])=>'<button class="'+(k===tab?'active':'')+'" aria-current="'+(k===tab?'page':'false')+'" onclick="QC.tab('+arg(k)+')">'+t+'</button>').join('');el('qcFilters').hidden=['import','history'].includes(tab);const rs=filtered(),a=I.qcTotals(rs),dates=range(),gs=groups(rs,r=>tab==='trend'&&el('qcPeriod').value==='year'?r.date.slice(0,7):r.date);el('qcRange').textContent=el('qcPeriod').value==='all'?'全部日期':dates[0]===dates[1]?dates[0]:dates.join(' ～ ');let html='';
if(tab==='import')html=renderImport();
else if(tab==='history')html=section('完整備份與原始附件','<div class="toolbar"><button class="primary" onclick="QC.backup()">↓ 完整 JSON 備份</button><button onclick="QC.tab(\'import\')">還原備份</button></div><p class="muted">原始附件、日報修訂及刪除歷史保留於本機資料庫，並使用共用雲端同步。</p>'+table(['原始附件','大小','下載'],sources.map(s=>[escape(s.name),fmt(s.size/1024)+' KB','<button onclick="QC.source('+arg(s.id)+')">下載原始檔案</button>'])))+section('修改與刪除歷史',table(['日期／線別','歷史版本','狀態','操作'],records.filter(r=>(r.history||[]).length||r.deleted).map(r=>[escape(r.date+' '+lineName(r.line)),fmt(r.history?.length),r.deleted?'已刪除':'保留中','<button onclick="QC.detail('+arg(r.id)+')">查看／還原</button>'])));
else if(!rs.length)html=toolbar()+'<section class="card empty"><span class="empty-icon">📊</span><h2>這個期間尚無 QC 報告</h2><p>匯入線別日報或週報，或切換到已有資料的日期。</p><button class="primary" onclick="QC.tab(\'import\')">📥 上傳報表</button> <button onclick="QC.showAll()">查看全部日期</button></section>';
else if(tab==='records')html=toolbar()+kpis(a)+notices(a)+section('線別日報管理',lineTable(rs));
else if(['weekly','trend','report'].includes(tab)){html=toolbar()+kpis(a)+notices(a)+'<div class="g2">'+section('檢驗與實際產出趨勢',chart(gs))+section('主要缺點',bars(defects(rs).filter(r=>r.qty).slice(0,7)))+'</div>'+section('每日統計',table(['日期','檢驗量','不良','實際產出','未完成產出差額','不良率','加權效率'],gs.map(x=>[escape(x.key),fmt(x.inspected),fmt(x.rejected),fmt(x.output),fmt(x.reconciliationGap),pct(x.rejectRate),pct(x.efficiency)])))+section('各線統計',table(['線別','檢驗量','不良','實際產出','不良率','加權效率'],groups(rs,r=>r.line).map(x=>[escape(lineName(x.key)),fmt(x.inspected),fmt(x.rejected),fmt(x.output),pct(x.rejectRate),pct(x.efficiency)])));if(tab==='report')html+=section('改善與原報備註',table(['日期／線別','備註'],rs.filter(r=>r.notes).map(r=>[escape(r.date+' '+lineName(r.line)),'<div class="table-note">'+escape(r.notes)+'</div>'])))}
else if(tab==='defects'){const ds=defects(rs).filter(r=>r.qty),sum=ds.reduce((s,x)=>s+x.qty,0);html=toolbar()+kpis(a)+'<div class="g2">'+section('主要缺點分布',bars(ds.slice(0,12)))+section('缺點占比','<p class="muted">一件衣服可能有多個缺點；缺點次數與不良件數分開計算。</p>'+table(['代碼','缺點','次數','占全部缺點'],ds.map(x=>[escape(x.code),escape(x.name),fmt(x.qty),pct(sum?x.qty/sum:null)])))+'</div>'+section('根因與改善紀錄',table(['日期／線別','根因／改善／備註','操作'],rs.map(r=>[escape(r.date+' '+lineName(r.line)),'<div class="table-note">'+escape(r.notes||'尚未填寫')+'</div>',rowButtons(r)])))}
else if(tab==='efficiency')html=toolbar()+kpis(a)+notices(a)+section('效率與目標','<div class="toolbar"><span>效率目標 <b>'+pct(settings.efficiencyTarget)+'</b> · 不良率上限 <b>'+pct(settings.rejectTarget)+'</b></span><button onclick="QC.settings()">調整目標</button></div>'+table(['線別','出勤分鐘','產出分鐘','加權效率','不良率','狀態'],groups(rs,r=>r.line).map(x=>[escape(lineName(x.key)),fmt(x.attendanceMinutes),fmt(x.producedMinutes),pct(x.efficiency),pct(x.rejectRate),x.efficiency==null?'<span class="muted">缺少完整分鐘</span>':x.efficiency<settings.efficiencyTarget||x.rejectRate>settings.rejectTarget?'<span class="bad">需改善</span>':'<span class="ok">達標</span>'])))+section('每日原報效率',lineTable(rs));
else if(tab==='scenario')html=toolbar()+notices(a)+section('SMV 情境比較','<p class="muted">依具備完整分鐘的 '+a.efficiencyKnown+' 份報告試算；不更改正式 SMV、原始產量或報表歷史。</p>'+table(['SMV 調整','試算產出分鐘','試算效率'],[0,-.1,-.15,-.2,-.35].map(x=>[pct(x),a.attendanceMinutes?fmt(a.producedMinutes*(1+x)):'—',pct(a.attendanceMinutes?a.producedMinutes*(1+x)/a.attendanceMinutes:null)])));
else if(tab==='validate')html=toolbar()+kpis(a)+notices(a)+validation(rs);
else if(tab==='styles')html=toolbar()+kpis(a)+styleView(rs);
else{const bad=rs.filter(r=>r.inspected&&r.rejected/r.inspected>settings.rejectTarget);html=toolbar()+kpis(a)+notices(a)+(bad.length?'<div class="alert">⚠ 不良率超過 '+pct(settings.rejectTarget)+'：'+bad.map(r=>escape((el('qcPeriod').value==='day'?'':r.date+' ')+lineName(r.line))).join('、')+'</div>':'');if(tab==='dashboard')html+='<div class="g2">'+section('各線不良件數',bars(groups(rs,r=>r.line).map(x=>({name:lineName(x.key),qty:x.rejected}))))+section('主要缺點',bars(defects(rs).filter(r=>r.qty).slice(0,7)))+'</div>';html+='<div class="section-heading"><h2>線別明細</h2><span class="muted">右上角顯示不良率 · 點明細查看逐時紀錄</span></div>'+lineCards(rs)}
el('qcContent').innerHTML='<div class="print-heading"><h1>VRT Final QC 品質檢驗報告</h1><p>'+escape(el('qcRange').textContent)+' · '+escape(el('qcLine').value||'全部線別')+'</p></div>'+html;
if(tab==='import')el('qcPreview').innerHTML=previewHTML();
}

 function dialog(title,html){el('qcDialogTitle').textContent=title;el('qcDialogBody').innerHTML=html;el('qcDialog').showModal()}
 function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function b64(buf){const bytes=new Uint8Array(buf),a=[];for(let i=0;i<bytes.length;i+=16384)a.push(String.fromCharCode(...bytes.subarray(i,i+16384)));return btoa(a.join(''))}
 async function importFiles(files){
  // FileList and DataTransfer.files are live. Capture synchronously, before any await/reset.
  const selected=Array.from(files||[]);
  if(importing||saving)return message('上一批報表仍在處理，請稍候。',true);
  if(!selected.length)return message('尚未選擇檔案，請按「選擇 Excel／CSV 檔案」或拖入報表。',true);
  importing=true;preview=[];previewSources=[];previewWarnings=[];importResults=selected.map(file=>({name:file.name,pending:true,count:0,detail:'等待讀取'}));tab='import';refresh();message('正在讀取 '+selected.length+' 個檔案…');
  try{await g.VRT_LOCAL_READY;
   for(let index=0;index<selected.length;index++){
    const file=selected[index],status=importResults[index];status.detail='正在解析';refresh();
    try{const buffer=await file.arrayBuffer();let parsed=[],extraSources=[],warnings=[],kinds=[];
     if(/\.json$/i.test(file.name)){const data=JSON.parse(new TextDecoder().decode(buffer));if(!Array.isArray(data.records))throw new Error('不是 QC 備份：找不到 records');data.records.forEach(I.validateQC);parsed=data.records;extraSources=(data.sources||[]).filter(s=>s.id&&s.base64);kinds=['JSON 備份'];}
     else{const inputs=/\.(eml|msg)$/i.test(file.name)?await mailFiles(file,buffer):[{name:file.name,buffer}];
      const errors=[];for(const f of inputs){try{const wb=XLSX.read(new Uint8Array(f.buffer),{type:'array',raw:true,cellDates:false}),p=I.qc(wb,f.name);parsed.push(...p.records);warnings.push(...p.warnings);kinds.push(p.kind==='weekly'?'線別週報':'線別日報／匯出資料')}catch(e){errors.push(f.name+'：'+e.message)}}
      if(!parsed.length)throw new Error(errors.join('；')||'找不到可匯入的線別資料');if(errors.length)warnings.push(...errors.map(s=>'郵件內附件略過：'+s));
     }
     if(!parsed.length)throw new Error('檔案沒有 QC 資料');if(!/\.json$/i.test(file.name)){const encoded=b64(buffer);extraSources.push({id:'QCS-'+C.hash(encoded),name:file.name,size:buffer.byteLength,base64:encoded})}
     preview.push(...parsed);previewSources.push(...extraSources);previewWarnings.push(...warnings);Object.assign(status,{pending:false,count:parsed.length,detail:[...new Set(kinds)].join('、')+' · '+[...new Set(parsed.map(r=>r.date))].sort().join('、')});
    }catch(e){Object.assign(status,{pending:false,error:true,count:0,detail:e.message||String(e)})}
    refresh();
   }
  }catch(e){message('讀取失敗：'+e.message,true);throw e}
  finally{importing=false;refresh()}
  const bad=importResults.filter(r=>r.error).length;
  message(preview.length?'解析完成：'+I.qcMerge([],preview).records.length+' 份日期／線別資料'+(bad?'；'+bad+' 個檔案失敗，詳見預覽':'')+'。請核對後按「確認儲存」。':'沒有讀到可匯入的資料，請查看檔名下方的錯誤原因。',!preview.length);
 }
 async function commit(){if(importing||saving)return;if(!preview.length)return message('沒有可儲存的資料，請先選擇報表。',true);saving=true;
  const before=C.copy(records),beforeSources=C.copy(sources),unique=I.qcMerge([],preview).records,hasWeekly=unique.some(r=>r.reportKind==='weekly');
  try{const diff=I.qcMerge(records,unique);records=diff.records;const sourceMap=new Map(sources.map(s=>[s.id,s]));for(const s of previewSources)if(!sourceMap.has(s.id))sourceMap.set(s.id,s);sources=[...sourceMap.values()];await save(!!(diff.added||diff.updated||sources.length!==beforeSources.length));
   el('qcDate').value=unique.filter(r=>!r.deleted).map(r=>r.date).sort().pop()||el('qcDate').value;preview=[];previewSources=[];previewWarnings=[];el('qcLine').value='';el('qcSearch').value='';el('qcPeriod').value=hasWeekly&&unique.some(r=>r.reportKind!=='weekly')?'all':hasWeekly?'week':'day';tab=hasWeekly?'weekly':'daily';message('已儲存：新增 '+diff.added+'、更新 '+diff.updated+'、相同略過 '+diff.unchanged+'。'+(diff.protected?'已保留 '+diff.protected+' 份較完整或已刪除的紀錄。':''));
  }catch(e){records=before;sources=beforeSources;message('儲存失敗，原資料已保留：'+e.message,true)}finally{saving=false;refresh()}
 }
 async function mailFiles(file,buf){let out=[];if(/\.msg$/i.test(file.name)){const c=XLSX.CFB.read(new Uint8Array(buf),{type:'array'});for(let i=0;i<c.FullPaths.length;i++){if(!/__substg1.0_37010102$/.test(c.FullPaths[i]))continue;const root=c.FullPaths[i].replace(/__substg.*$/,''),find=code=>c.FileIndex[c.FullPaths.findIndex(p=>p===root+'__substg1.0_'+code)]?.content;const nameData=find('3707001F')||find('3704001F');const name=nameData?new TextDecoder('utf-16le').decode(new Uint8Array(nameData)).replace(/\0/g,''):'';if(/\.(xlsx?|xlsb|csv)$/i.test(name))out.push({name,buffer:new Uint8Array(c.FileIndex[i].content)})}}else{const text=new TextDecoder().decode(buf),boundary=text.match(/boundary\s*=\s*"?([^"\r\n;]+)/i)?.[1];if(!boundary)throw new Error('Email 缺少 MIME boundary');for(const part of text.split('--'+boundary)){const name=part.match(/(?:filename|name)\s*=\s*"?([^"\r\n;]+\.(?:xlsx?|xlsb|csv))/i)?.[1],body=part.split(/\r?\n\r?\n/).slice(1).join('\n\n');if(name&&/content-transfer-encoding:\s*base64/i.test(part))out.push({name,buffer:Uint8Array.from(atob(body.replace(/\s/g,'')),c=>c.charCodeAt(0))})}}if(!out.length)throw new Error('Email 沒有可辨識的 Excel 附件，請將 Excel 另存後匯入');return out}
 function detail(id){const r=records.find(r=>r.id===id);if(!r)return;dialog(r.date+' · '+r.line,kpis(I.qcTotals([r]))+notices(I.qcTotals([r]))+'<p>來源 '+escape(r.sourceFile)+' · '+escape(r.sourceSheet)+'</p><p>'+escape(r.notes)+'</p><h2>款式／SMV／產出</h2>'+table(['款式','SMV','實際產出','產出分鐘'],(r.styles||[]).map(s=>[escape(s.style),fmt(s.smv),fmt(s.output),fmt(s.minutes)]))+'<h2>時段檢驗</h2>'+table(['時段','檢驗','Reject'],(r.intervals||[]).map(x=>[escape(x.time),fmt(x.inspected),fmt(x.rejected)]))+'<h2>缺點與逐時分布</h2>'+table(['代碼','缺點','次數','時段'],(r.defects||[]).map(d=>[escape(d.code),escape(d.name),fmt(d.qty),escape((d.hourly||[]).filter(h=>h.qty).map(h=>h.time+': '+h.qty).join(' / '))]))+validation([r])+'<details><summary>修改歷史 '+(r.history||[]).length+'</summary>'+table(['版本','日期／時間','檢驗','Reject','操作'],(r.history||[]).map((h,i)=>[i+1,escape(h.updatedAt||h.date),fmt(h.inspected),fmt(h.rejected),'<button onclick="QC.restore(\''+id+'\','+i+')">恢復此版</button>']))+'</details>')}
 const detailSpecs={styles:[['style','款式','text'],['smv','SMV','number'],['output','Output','number']],defects:[['code','代碼','text'],['name','缺點名稱','text'],['qty','次數','number']],intervals:[['time','時段','text'],['inspected','檢驗量','number'],['rejected','Reject','number']]};
 function detailRow(kind,r={}){return '<tr data-qc-kind="'+kind+'">'+detailSpecs[kind].map(([k,label,type])=>'<td><input aria-label="'+label+'" data-field="'+k+'" type="'+type+'" step="any" min="0" value="'+escape(r[k]??'')+'"></td>').join('')+'<td><button type="button" class="danger" onclick="this.closest(\'tr\').remove()">刪除</button></td></tr>'}
 function detailEditors(r){return '<details><summary>款式、缺點與時段明細</summary>'+Object.keys(detailSpecs).map(kind=>'<section class="card"><h3>'+({styles:'款式產出',defects:'缺點明細',intervals:'時段檢驗'}[kind])+'</h3><div class="table-wrap"><table><thead><tr>'+detailSpecs[kind].map(x=>'<th>'+x[1]+'</th>').join('')+'<th>操作</th></tr></thead><tbody id="qcEdit-'+kind+'">'+(r[kind]||[]).map(x=>detailRow(kind,x)).join('')+'</tbody></table></div><button type="button" onclick="QC.addDetail(\''+kind+'\')">＋ 新增</button></section>').join('')+'</details>'}
 function readDetailEditors(form,prior){const out={};for(const kind of Object.keys(detailSpecs)){out[kind]=[...form.querySelectorAll('tr[data-qc-kind="'+kind+'"]')].map(tr=>{const r={};for(const [k,,type] of detailSpecs[kind]){const v=tr.querySelector('[data-field="'+k+'"]').value.trim();r[k]=type==='number'?C.number(v):v;if(type==='number'&&(r[k]==null||r[k]<0))throw new Error('請填寫有效的明細數量／SMV')}if(kind==='styles'){if(!r.style||!Number.isInteger(r.output))throw new Error('款式不可空白，Output 須為整數');r.minutes=r.smv*r.output}else if(kind==='defects'){if(!r.name||!Number.isInteger(r.qty))throw new Error('缺點名稱不可空白，次數須為整數');const old=(prior.defects||[]).find(d=>d.code===r.code&&d.name===r.name);r.hourly=old&&old.qty===r.qty?old.hourly:[]}else if(!r.time||r.rejected>r.inspected||!Number.isInteger(r.inspected)||!Number.isInteger(r.rejected))throw new Error('請核對時段及檢驗／不良件數');return r})}return out}
 function edit(id){const r=records.find(r=>r.id===id)||{date:el('qcDate').value,line:'',inspected:0,rejected:0,output:0},fields=[['date','日期','date'],['line','線別','text'],['customer','客戶','text'],['po','PO','text'],['inspected','檢驗量','number'],['rejected','不良件數','number'],['output','實際產出','number'],['workers','出勤人數','number'],['attendanceMinutes','出勤分鐘','number'],['producedMinutes','產出分鐘','number']];
  dialog(id?'編輯線別日報':'新增線別日報','<div class="info">線上修訂會優先保留；重匯同日同線的報表可至「數據比對」核對。若有半成品而實際產出較少，請填寫原因。缺少分鐘／人數時可留白。</div><form id="qcEditForm"><div class="fields">'+fields.map(([k,label,t])=>'<label>'+label+'<input name="'+k+'" type="'+t+'" '+(t==='number'?'step="any" min="0"':'')+' '+(['date','line','inspected','rejected','output'].includes(k)?'required':'')+' value="'+escape(r[k]??'')+'"></label>').join('')+'</div><label>根因／改善／半成品／備註<textarea name="notes">'+escape(r.notes)+'</textarea></label>'+detailEditors(r)+'<button class="primary" type="submit">✓ 儲存日報</button></form>');
  el('qcEditForm').onsubmit=async e=>{e.preventDefault();if(saving)return;const before=C.copy(records);try{const values=Object.fromEntries(new FormData(e.target)),x={...r,...values};for(const [k,,t] of fields)if(t==='number')x[k]=C.number(x[k]);x.line=I.qcLine(x.line);x.reconciliationGap=x.inspected-x.rejected-x.output;Object.assign(x,readDetailEditors(e.target,r));I.validateQC(x);
   if(x.reconciliationGap&&!String(x.notes||'').trim())throw new Error('有 '+x.reconciliationGap+' 件未列為實際產出，請在備註說明半成品／未完成原因');
   if(x.styles.length){const out=x.styles.reduce((s,v)=>s+v.output,0);if(out!==x.output)throw new Error('款式產出加總與實際產出不符');x.producedMinutes=x.styles.reduce((s,v)=>s+v.minutes,0)}
   x.id=I.qcId(x);if(records.some(z=>z.id!==id&&!z.deleted&&z.id===x.id))throw new Error('此日期及線別已有日報，請編輯原紀錄');if(!id&&records.some(z=>z.id===x.id))throw new Error('此日／線別有刪除歷史，請從「歷史／備份」還原後編輯');
   x.reportKind='manual';x.issues=[];if(x.reconciliationGap)x.issues.push('尚未列為實際產出 '+x.reconciliationGap+' 件；請參照備註');const ds=x.defects.reduce((s,d)=>s+d.qty,0);if(x.defects.length&&ds!==x.rejected)x.issues.push('缺點次數 '+ds+' 與不良件數 '+x.rejected+' 不同，請核對');
   if(id)x.history=[...(r.history||[]),{...r,history:undefined}];x.updatedAt=new Date().toISOString();if(id&&x.id!==id){records[records.indexOf(r)]={...r,deleted:true,updatedAt:x.updatedAt,history:[...(r.history||[]),{...r,history:undefined}]};records.push(x)}else if(id)records[records.indexOf(r)]=x;else records.push(x);
   saving=true;await save();el('qcDate').value=x.date;el('qcDialog').close();message('已儲存 '+x.date+' '+lineName(x.line));refresh();
  }catch(err){records=before;message('儲存失敗：'+err.message,true);alert(err.message)}finally{saving=false}}
 }
 async function remove(id){if(saving||!confirm('刪除此線別日報？原資料保留在歷史，可還原。'))return;const before=C.copy(records),r=records.find(x=>x.id===id);if(!r)return;try{saving=true;r.history=[...(r.history||[]),{...r,history:undefined}];r.deleted=true;r.updatedAt=new Date().toISOString();await save();message('已刪除，原資料可在歷史紀錄還原。')}catch(e){records=before;message('刪除未儲存：'+e.message,true)}finally{saving=false;refresh()}}
 async function restore(id,i){if(saving||!confirm('恢復此歷史版本？'))return;const before=C.copy(records),r=records.find(r=>r.id===id);if(!r?.history?.[i])return;try{saving=true;const x=C.copy(r.history[i]);x.id=id;x.deleted=false;x.updatedAt=new Date().toISOString();x.history=[...r.history,{...r,history:undefined}];I.validateQC(x);records[records.indexOf(r)]=x;await save();el('qcDialog').close();message('已恢復歷史版本。')}catch(e){records=before;message('還原未儲存：'+e.message,true)}finally{saving=false;refresh()}}
 function exportFile(csv=false){const rows=filtered().map(r=>({ID:r.id,Date:r.date,Line:r.line,Customer:r.customer||'',PO:r.po||'',Inspected:r.inspected,Rejected:r.rejected,Output:r.output,'Reject %':r.inspected?r.rejected/r.inspected:'','Attendance Minutes':r.attendanceMinutes,'Produced Minutes':r.producedMinutes,'Report Kind':r.reportKind||'daily','Reconciliation Gap':r.inspected-r.rejected-r.output,'Reported Efficiency':r.reportedEfficiency??'',Notes:r.notes,'Record JSON':JSON.stringify({...r,history:[]})})),w=XLSX.utils.book_new();if(!rows.length)return message('此期間無資料可匯出');const sheet=XLSX.utils.json_to_sheet(rows);if(csv){const keys=Object.keys(rows[0]);download('VRT_QC_'+el('qcDate').value+'.csv','\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8')}else{XLSX.utils.book_append_sheet(w,sheet,'QC Records');XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(filtered().flatMap(r=>(r.styles||[]).map(s=>({Date:r.date,Line:r.line,...s})))),'Styles');XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(filtered().flatMap(r=>(r.defects||[]).map(d=>({Date:r.date,Line:r.line,Code:d.code,Defect:d.name,Qty:d.qty})))),'Defects');XLSX.writeFile(w,'VRT_QC_'+el('qcDate').value+'.xlsx')}}
 function settingsPanel(){dialog('目標與共用雲端設定','<form id="qcSettings"><label>共用 GAS URL<input name="url" value="'+escape(VRTPlatform.getGasUrl())+'" placeholder="/exec URL"></label><div class="fields"><label>Reject 上限 %<input name="reject" type="number" min="0" max="100" step="0.1" value="'+settings.rejectTarget*100+'"></label><label>效率目標 %<input name="eff" type="number" min="0" step="0.1" value="'+settings.efficiencyTarget*100+'"></label></div><button class="primary">儲存</button></form>');el('qcSettings').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{if(!Number.isFinite(Number(d.reject))||!Number.isFinite(Number(d.eff))||Number(d.reject)<0||Number(d.reject)>100||Number(d.eff)<0)throw new Error('請填寫有效的目標百分比');if(d.url.trim())VRTPlatform.setGasUrl(d.url);settings={rejectTarget:Number(d.reject)/100,efficiencyTarget:Number(d.eff)/100};localStorage.setItem('vrt_qc_settings',JSON.stringify(settings));el('qcDialog').close();refresh()}catch(e){alert(e.message)}}}
 const cloudSource=s=>({id:s.id,name:s.name,size:s.size,hash:s.hash||s.id,updatedAt:s.updatedAt||'',hasLocalAttachment:!!s.base64});const cloudRows=()=>records.concat(sources.map(s=>({id:s.id,_vrtEntity:'qc.source',_vrtValue:cloudSource(s)})));
 async function sync(dir){await g.VRT_LOCAL_READY;if(saving)return {ok:false,busy:true};const url=VRTPlatform.getGasUrl();if(!url){message('尚未找到共用 GS 連線設定，請在平台設定一次；QC 會自動沿用。',true);return false}const network={vrtTimeoutMs:90000,vrtRetryDelays:[5000,15000,45000],vrtOnRetry:(n,delay,e)=>{message('雲端忙碌，稍後自動重試 · '+Math.round(delay/1000)+'s');try{VRTSmartSync.status('push','雲端忙碌，稍後自動重試','warn')}catch(_){}}};try{let r;if(dir==='push')r=await VRTSmartSync.push({url,tool:'qc',records:cloudRows(),meta:{schemaVersion:43,sourceAttachmentPolicy:'metadata-only'},network});else r=await VRTSmartSync.pull({url,tool:'qc',localRecords:cloudRows(),meta:{schemaVersion:43,sourceAttachmentPolicy:'metadata-only'},apply:async rows=>{const remote=rows.filter(r=>!r._vrtEntity),map=new Map(records.map(r=>[r.id,r]));for(const x of remote){const prior=map.get(x.id);if(!prior||String(x.updatedAt||'')>=String(prior.updatedAt||''))map.set(x.id,x)}records=[...map.values()];const srcMap=new Map(sources.map(r=>[r.id,r]));for(const x of rows.filter(r=>r._vrtEntity==='qc.source').map(r=>r._vrtValue)){const old=srcMap.get(x.id)||{};srcMap.set(x.id,{...x,...old,base64:old.base64||''})}sources=[...srcMap.values()];await save(false);return cloudRows()},network});if(r.needsPull)message('雲端有變更，請先 Pull 後再 Push。');else if(dir==='push'&&r.ok)message('完成｜上傳 '+(r.uploaded||0)+'｜待上傳 0');return r}catch(e){const friendly=/HTML|503|502|504|aborted|timeout|service busy|non-JSON/i.test(e.message||'')?'雲端忙碌，稍後自動重試':('雲端 '+dir+' 失敗：'+e.message);message(friendly,true);throw e}}
 g.QC={refresh,tab:k=>{tab=k;if(k==='daily')el('qcPeriod').value='day';if(k==='weekly'||k==='report')el('qcPeriod').value='week';if(k==='trend')el('qcPeriod').value='month';refresh()},shift:n=>{const d=new Date(el('qcDate').value+'T12:00:00'),p=el('qcPeriod').value;if(p==='month'){d.setDate(1);d.setMonth(d.getMonth()+n)}else if(p==='year')d.setFullYear(d.getFullYear()+n);else d.setDate(d.getDate()+n*(p==='week'?7:1));el('qcDate').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');refresh()},importFiles,commit,onFileInput:input=>{const chosen=Array.from(input.files||[]);input.value='';return importFiles(chosen)},choose:id=>el(id).click(),showAll:()=>{el('qcPeriod').value='all';el('qcLine').value='';el('qcSearch').value='';refresh()},addDetail:kind=>{el('qcEdit-'+kind).insertAdjacentHTML('beforeend',detailRow(kind))},cancelImport:()=>{if(importing||saving)return;preview=[];previewSources=[];previewWarnings=[];importResults=[];refresh();message('已取消，本機資料未變動')},edit,detail,remove,export:exportFile,settings:settingsPanel,sync,backup:()=>download('VRT_QC_Backup.json',JSON.stringify({schemaVersion:42,records,sources},null,2)),source:id=>{const s=sources.find(s=>s.id===id);if(s)download(s.name,Uint8Array.from(atob(s.base64),c=>c.charCodeAt(0)),'application/octet-stream')},restore,included:async(kind='previous')=>{const name=kind==='latest'?'Final_QC_20260922.xlsx':kind==='daily'?'Final_QC_20260919.xlsx':kind==='weekly'?'QC_Weekly_20260914_19.xlsx':'Final_QC_20260917.xlsx';try{const r=await fetch('release_sources/'+name);if(!r.ok)throw new Error('HTTP '+r.status);const bytes=await r.arrayBuffer();await importFiles([{name,arrayBuffer:async()=>bytes}])}catch(e){message('無法讀取隨附報表：'+e.message,true)}},getState:()=>C.copy({records,sources}),getImportState:()=>C.copy({preview,warnings:previewWarnings,files:importResults,importing,saving}),applyRecords:async rows=>{records=I.qcMerge(records,rows).records;await save(false)}};
 g.VRT_LOCAL_READY=load().catch(e=>{message('讀取本機資料失敗：'+e.message,true);throw e});VRTProdAutoSync.install({key:'qc',lockKey:'qc',canSync:()=>!!VRTPlatform.getGasUrl(),pull:()=>sync('pull'),push:()=>sync('push'),watch:false,startDelay:1800});
})(window);
