/* Stage C: real module pipeline (importExcel → commit) with the newest files; second import must add nothing. */
const path=require('path'),fs=require('fs'),assert=require('assert');
const ROOT=path.resolve(__dirname,'../..'),BASE=path.resolve(__dirname,'../../../baseline/vrt-prod-main'),UP='/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/';
const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');
const out=[],add=async(name,fn)=>{try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}};
const file=(p,name)=>{const bytes=fs.readFileSync(p);return {name,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}};
(async()=>{
 // 1. Baseline (v4.0 importer) against the NEWEST files → proves the bug the user is hitting.
 const b=createRuntime(BASE+'/vrt_spare_parts_v2.html');b.load();await new Promise(r=>setTimeout(r,120));
 await add('BASELINE v4.0 importer on newest Needle file: fails or mis-reads (documents the current production bug)',async()=>{const I=b.ctx.VRTImport40,wb=b.ctx.XLSX.read(fs.readFileSync(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx'),{type:'buffer',raw:true,cellDates:true});let msg='';try{const p=I.dailyChanges(wb,'n.xlsx');const r=p.stockReports.find(x=>x.start==='2026-09-28');const dbx=r&&r.items.find(x=>x.name==='DBX1'&&x.size==='100/16');msg='parsed; 9-28 DBX1 100/16 read as stockLeft='+(dbx&&dbx.stockLeft)+' used='+(dbx&&dbx.used)+' balance='+(dbx&&dbx.balance)+' (truth: 560/20/540) lines='+JSON.stringify(p.needleChanges.filter(c=>c.date==='2026-09-28'&&/DBX1/.test(c.needleType)&&c.size==='100/16').map(c=>c.line+':'+c.qty))}catch(e){msg='threw: '+e.message}assert(/threw|used=(null|0|undefined)|Line 2:10/.test(msg),msg);return msg});
 await add('BASELINE v4.0 importer on newest Spare Part file (9-18+ new layout)',async()=>{const I=b.ctx.VRTImport40,wb=b.ctx.XLSX.read(fs.readFileSync(UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx'),{type:'buffer',raw:true,cellDates:true});let msg='';try{const p=I.dailyChanges(wb,'p.xlsx');const r=p.stockReports.find(x=>x.start==='2026-09-28');msg='parsed '+p.stockReports.length+' sheets; 9-28 '+(r?'present, hook used='+r.items[0].used+' balance='+r.items[0].balance+' (truth: issued 1 / closing 7)':'MISSING')}catch(e){msg='threw: '+e.message}return msg});
 b.close();
 // 2. New importer through the real module: import twice.
 const m=createRuntime(ROOT+'/vrt_spare_parts_v2.html');m.load();await new Promise(r=>setTimeout(r,120));
 const api=m.ctx.VRTParts39,state=()=>api.getState();
 const counts=()=>{const s=state();return {stock:s.maintenance.stockReports.length,needle:s.maintenance.needleChanges.length,part:s.maintenance.partChanges.length,hist:s.maintenance.editHistory.length,docs:s.maintenance.sourceDocuments.length}};
 let c0=counts();
 await add('Import newest Needle file (23 sheets) through importExcel → commit',async()=>{await m.ctx.importExcel(file(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'));const p=api.getPending();assert(p,'pending preview missing');assert.strictEqual(p.stockReports.length,23);const st=await api.commit();const c=counts();assert.strictEqual(c.stock-c0.stock,23);assert(c.needle>0);return JSON.stringify(st)+' → '+JSON.stringify(c)});
 const c1=counts();
 await add('Import the SAME Needle file again → 0 added, 0 updated, no history growth',async()=>{await m.ctx.importExcel(file(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'));const st=await api.commit();const c=counts();assert.deepStrictEqual({stock:c.stock,needle:c.needle,part:c.part,hist:c.hist},{stock:c1.stock,needle:c1.needle,part:c1.part,hist:c1.hist});assert.strictEqual(st.stock,0);assert.strictEqual(st.changes,0);return JSON.stringify(st)});
 await add('Import bundled OLD Needle file (overlapping 9-1…9-22, 9-17/9-18 restated) → overlapping identical days unchanged, restated days updated with history, no duplicate change rows',async()=>{const before=counts();await m.ctx.importExcel(file(BASE+'/release_sources/Needle_Change_202609.xlsx','Daily Needles Change Report (week-3).xlsx'));const st=await api.commit();const s=state(),c=counts();assert.strictEqual(c.stock,before.stock,'no new daily reports (all 19 days already exist)');const ids=s.maintenance.needleChanges.map(x=>x.id);assert.strictEqual(new Set(ids).size,ids.length,'duplicate change ids');const perDay={};s.maintenance.needleChanges.forEach(x=>perDay[x.date]=(perDay[x.date]||0)+1);const r18=s.maintenance.stockReports.find(x=>x.id==='NEEDLE-2026-09-18_2026-09-18');assert(r18.history&&r18.history.length>=1,'restated day keeps prior version');return JSON.stringify(st)+' · 9-18 history='+r18.history.length});
 await add('Import newest Spare Part file (15 sheets, reversed headers) then again → idempotent',async()=>{await m.ctx.importExcel(file(UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx','Daily Spare Part Change Report.xlsx'));const p=api.getPending();assert.strictEqual(p.stockReports.length,15);const st1=await api.commit();const c1=counts();await m.ctx.importExcel(file(UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx','Daily Spare Part Change Report.xlsx'));const st2=await api.commit();const c2=counts();assert.strictEqual(c2.stock,c1.stock);assert.strictEqual(c2.part,c1.part);assert.strictEqual(c2.hist,c1.hist);assert.strictEqual(st2.stock+st2.changes,0);return JSON.stringify(st1)+' then '+JSON.stringify(st2)});
 await add('All change records carry reasonClass; totals per class (needle)',async()=>{const s=state();const cls={};s.maintenance.needleChanges.forEach(x=>{cls[x.reasonClass||'missing']=(cls[x.reasonClass||'missing']||0)+x.qty});assert(!cls.missing);assert(cls.changeover>0);return JSON.stringify(cls)});
 await add('Render tabs after import (needlechange / partchange / needle / machine) without exceptions',async()=>{for(const t of ['needlechange','partchange','needle','machine','dashboard'])m.ctx.goTab(t,null);return 'ok'});
 m.close();
 fs.writeFileSync(path.resolve(__dirname,'stageC_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})();
