/* IE Line Balancing tab with real data: plan xlsx, sewing backup, needle changes, IE weekly + OBDs. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=process.env.VRT_ROOT||path.resolve(__dirname,'../..'),DL='/mnt/user-data/uploads/Downloads/';
const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');
const jf=p=>{const b=fs.readFileSync(p);return{name:path.basename(p),lastModified:0,text:async()=>b.toString('utf8'),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
// Parse plan + needle files with the real parsers in a plain Node context.
global.window=global;global.XLSX=require(ROOT+'/vendor/xlsx.full.min.js');require(ROOT+'/vrt-data-core-v39.js');require(ROOT+'/vrt-import-core-v40.js');
const needleParsed=global.VRTImport40.dailyChanges(XLSX.read(fs.readFileSync('/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx'),{type:'buffer',raw:true,cellDates:true}),'Daily Needles Change Report 24 to28 Sept.xlsx');
const partsParsed=global.VRTImport40.dailyChanges(XLSX.read(fs.readFileSync('/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/2127d3e5-Daily_Spare_Part_Change_Report.xlsx'),{type:'buffer',raw:true,cellDates:true}),'Daily Spare Part Change Report.xlsx');
const sewing=JSON.parse(fs.readFileSync(DL+'sewing_backup_2026-09-28.json','utf8')).daily;
(async()=>{
 // Plan records: run the plan module once to get sanitized records
 let planRecords=[];{const r=createRuntime(ROOT+'/production_plan_capacity_v1.html');r.ctx.confirm=()=>true;r.ctx.alert=()=>{};r.load();await new Promise(res=>setTimeout(res,300));await r.ctx.importFile(jf(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx'));await new Promise(res=>setTimeout(res,400));await r.ctx.confirmPlanImport512();planRecords=JSON.parse(r.run('JSON.stringify(DATA.records)'));r.close()}
 const r=createRuntime(ROOT+'/ie_smv_report_v2_1.html');r.ctx.confirm=()=>true;r.ctx.alert=()=>{};r.ctx.prompt=(m,d)=>d||'QA';r.saved=[];r.load();const X=r.ctx.XLSX;X.writeFile=(wb,name)=>r.saved.push({name,sheets:wb.SheetNames.slice(),rows:Object.fromEntries(wb.SheetNames.map(s=>[s,X.utils.sheet_to_json(wb.Sheets[s]).length]))});
 const app=r.ctx.VRT_IE_SMV_APP;await app.ready;const B=r.ctx.VRTIEBalancing;assert(B,'balancing module not loaded');
 await test('Seed PROD data into this browser: plan '+planRecords.length+', sewing '+sewing.length+', needle changes '+needleParsed.needleChanges.length,async()=>{await r.ctx.VRTProdStorage.replaceAll('VRT_ProductionPlan','plan_records',planRecords,{keyPath:'id'});await r.ctx.VRTProdStorage.replaceAll('VRT_SewingProduction','daily_records',sewing,{keyPath:'id'});const M={schemaVersion:3,invoiceSummaries:[],stockReports:needleParsed.stockReports,needleChanges:needleParsed.needleChanges,partChanges:partsParsed.partChanges,sourceDocuments:[],tombstones:[],editHistory:[]};await r.ctx.VRTDomain39.write('vrt_spareparts',{meta:{values:[{k:'maintenance39',v:M}]}});const d=await r.ctx.VRTDomain39.readDomain('spareparts');assert.equal(d.maintenance.needleChanges.length,needleParsed.needleChanges.length);return 'ok'});
 let cands=[];await test('Import IE weekly (approved) + 4 OBDs (all pending) without upload changes',async()=>{for(const f of [DL+'VRT_IE_Weekly_SMV_Update_Report_CN_EN_Approved_20260930.xlsx',DL+'ie smv chp new/with chip/Pending - OBD-A050-W-SP-CHP.xls',DL+'ie smv chp new/with chip/Pending - OBD-A318-W-SP-CHP.xls',ROOT+'/release_sources/OBD_5209_pending.xls',ROOT+'/release_sources/OBD_A2642K_pending.xls'])cands.push(...await app.parseFile(jf(f)));await app.importCandidates(cands);const s=app.getState();assert.equal(s.styles.length,4);assert(s.updates.length>=77);return 'styles 4 · updates '+s.updates.length+' · ops '+s.operations.length});
 await test('Tab renders; plan row auto-resolves an OBD only when the style matches; pending OBD → DRAFT / SIMULATION ONLY',async()=>{await B.load();const src=B.getSources();assert.equal(src.plan.length,planRecords.length);const p5209=src.plan.find(p=>/5209/.test(String(p.style)));const withObd=src.plan.map(p=>({p,o:B.obdFor(p)})).filter(x=>x.o);const anyPlan=src.plan.find(p=>p.month==='2026-09');B.select(anyPlan.id,'');B.setView('setup');r.run('window.__act="balancing"');B.render();const html=r.elements.get('content').innerHTML;assert(/Setup|款式排線/.test(html));const st=B.obdStatus(B.obdFor(anyPlan));return 'plan rows with a matching OBD: '+withObd.length+' ('+withObd.slice(0,4).map(x=>x.p.style+'→'+x.o.style).join(', ')+') · 5209 in plan: '+(p5209?p5209.line:'no')+' · first Sep row OBD: '+(B.obdFor(anyPlan)?B.obdFor(anyPlan).style+' '+st.label:'none')});
 await test('Balancing math for OBD 5209 (35 ops, SMV 13.81): required = SMV×output÷(minutes×eff); suggested = ceil; statuses by thresholds',async()=>{const src=B.getSources();const obd=src.ie.styles.find(s=>s.style==='5209');const plan=src.plan.find(p=>p.month==='2026-09'&&/Line 6/.test(p.line));B.select(plan.id,obd.id);B.setSim({output:300,minutes:480,ot:0,eff:0.45,manpower:29});const c=B.calc(obd,plan);assert.equal(c.rows.length,35);const expectedTotalRaw=13.81469387326389*300/(480*0.45);const sumRaw=c.rows.reduce((s,x)=>s+x.raw,0);assert(Math.abs(sumRaw-expectedTotalRaw)<0.01,'raw sum '+sumRaw+' vs '+expectedTotalRaw);const ex=c.rows.find(x=>x.smv>0);assert.equal(ex.suggested,Math.ceil(ex.raw-1e-9));assert(c.rows.every(x=>['Bottleneck','Balanced','Moderate','Underload','瓶頸','平衡','中等負載','低負載'].includes(x.status)));const st=B.obdStatus(obd);assert(!st.formal&&/DRAFT/.test(st.label));return 'Σraw '+sumRaw.toFixed(2)+' · suggested Σ '+c.suggested+' · assigned Σ '+c.assigned+' · bottlenecks '+c.bottlenecks+' · families '+c.machines.map(m=>m.family+':'+m.required).join(', ')+' · manpower calc '+c.manpowerCalc.total+' vs plan '+c.manpower});
 await test('Simulation: changing output / efficiency updates stations immediately; SN example 0.90 SMV × 600 ÷ (480×0.45) = 2.50 → 3',async()=>{const src=B.getSources();const obd=src.ie.styles.find(s=>s.style==='5209');B.setSim({output:600,eff:0.45,minutes:480,ot:0});const c=B.calc(obd,null);const raw=0.9*600/(480*0.45);assert(Math.abs(raw-2.5)<1e-9);B.setSim({output:300});const c2=B.calc(obd,null);assert(c2.suggested<=c.suggested);return 'example raw 2.50 → suggested 3 · Σsuggested @600='+c.suggested+' @300='+c2.suggested});
 await test('Target efficiency priority: user > recent actual (same style/line) > plan > 45% default (labelled)',async()=>{const src=B.getSources();B.setSim({eff:null});const plan=src.plan.find(p=>src.sewing.some(s=>s.styleNo&&String(p.style).toUpperCase().startsWith(String(s.styleNo).toUpperCase())&&/Line/.test(s.lineNo)&&s.lineNo===p.line&&s.efficiency>0))||src.plan[0];const e1=B.resolveEff(plan);B.setSim({eff:0.5});const e2=B.resolveEff(plan);assert.equal(e2.eff,0.5);B.setSim({eff:null});const e3=B.resolveEff({style:'ZZZ',line:'Line 99'});assert(/SIMULATION|模擬/.test(e3.source));return 'auto: '+pct(e1.eff)+' ('+e1.source+') · user: 50% · unknown style: '+pct(e3.eff)+' ('+e3.source+')'});
 await test('Every sub-view renders without exception (setup, balance, machine, manpower, changeover, pva, needle, master, weekly, report)',async()=>{const src=B.getSources();const obd=src.ie.styles.find(s=>s.style==='5209'),nxt=src.ie.styles.find(s=>s.style==='A2642K');const plan=src.plan.find(p=>p.month==='2026-09'&&/Line 6/.test(p.line));B.select(plan.id,obd.id);r.ctx.__sel=nxt.id;const errs=[];for(const v of ['setup','balance','machine','manpower','changeover','pva','needle','master','weekly','report']){try{B.setView(v);B.render();const html=r.elements.get('content').innerHTML;assert(html.length>200,'empty '+v);if(v==='balance')assert(/Bottleneck|瓶頸|Balanced|平衡/.test(html));if(v==='machine')assert(/Not linked|尚未建立機台配置/.test(html));if(v==='needle')assert(/Needles \/ 1,000|每千件/.test(html))}catch(e){errs.push(v+': '+e.message)}}assert(!errs.length,errs.join(' | '));return 'ok'});
 await test('Changeover 5209 → A2642K: similarity scores in [0,1], machine add/remove table, retained/new ops',async()=>{const src=B.getSources();const a=src.ie.styles.find(s=>s.style==='5209'),b=src.ie.styles.find(s=>s.style==='A2642K');const co=B.changeover(a,b);assert(co.machineSim>=0&&co.machineSim<=1&&co.opSim>=0&&co.opSim<=1);assert.equal(co.opRows.length,co.retainedOps+co.newOps);return 'machine sim '+pct(co.machineSim)+' · op sim '+pct(co.opSim)+' · retained '+co.retainedOps+' / new '+co.newOps+' · training '+co.training});
 await test('Needle history: Change Style never counted as failure; per-1,000 uses actual pieces or shows Insufficient data; link unique/ambiguous/unlinked',async()=>{const src=B.getSources();const plan={line:'Line 1',style:'GPRC393SF',startDate:'2026-09-01',endDate:'2026-09-28',po:'x'};B.select('','' );const nh=B.needleHistory(plan,B.calc(null,plan));assert(nh);const unplanned=(nh.cls.damage||0)+(nh.cls.broken||0);assert.equal(nh.per1000.unplanned==null?null:Math.round(nh.per1000.unplanned*1000),nh.pieces?Math.round(unplanned/nh.pieces*1000*1000):null);const conf={};nh.links.forEach(l=>conf[l.confidence]=(conf[l.confidence]||0)+1);assert(nh.hoursKnown===0);return 'Line 1 Sep: needles '+nh.total+' (changeover '+(nh.cls.changeover||0)+', unplanned '+unplanned+') · pieces '+nh.pieces+' · per1000 total '+(nh.per1000.total==null?'Insufficient data':nh.per1000.total.toFixed(1))+' · links '+JSON.stringify(conf)+' · machine hours known 0 → life hours = Insufficient data'});
 await test('Save assignment + alias + master + link → persisted in state.balancing, survives reload, packs into one ie_balancing bucket',async()=>{const src=B.getSources();const obd=src.ie.styles.find(s=>s.style==='5209');const plan=src.plan.find(p=>p.month==='2026-09'&&/Line 6/.test(p.line));B.select(plan.id,obd.id);B.setView('balance');B.render();
   const html=r.elements.get('content').innerHTML;const ids=[...html.matchAll(/data-bal-assign="([^"]+)"/g)].map(m=>m[1]);assert(ids.length===35,'assign inputs '+ids.length);
   const key=await B.saveAssignment({[ids[0]]:2});const s1=app.getState();const rec=(s1.balancing||[]).find(x=>x.kind==='assignment'&&x.id===key);assert(rec,'assignment not saved');assert.equal(rec.formal,false);assert.equal(rec.assigned[ids[0]],2);assert.equal(Object.keys(rec.assigned).length,1);
   await B.setAlias('Bt','Bartack');const s2=app.getState();assert((s2.balancing||[]).some(x=>x.kind==='alias'&&x.text==='Bt'&&x.family==='Bartack'));
   // the rendered balance table now shows the saved value and the alias affects familyOf
   B.render();assert(r.elements.get('content').innerHTML.includes('data-bal-assign="'+ids[0]+'" type="number" min="0" step="0.5" value="2"'),'saved value not rendered');assert.equal(B.familyOf('Bt'),'Bartack');
   const d=await r.ctx.VRTDomain39.readDomain('smv');const rows=r.ctx.VRTDomain39.pack('smv',d);const balRows=rows.filter(x=>x._vrtEntity==='ie.balancing');assert(balRows.length>=2);assert(balRows.every(x=>x._smartBucket==='ie_balancing'));const back=r.ctx.VRTDomain39.unpack('smv',rows,{});assert.equal(back.ie.balancing.length,balRows.length);const merged=r.ctx.VRTData39.mergeIE(back.ie,back.ie);assert.equal(merged.balancing.length,balRows.length);return 'balancing records '+balRows.length+' → bucket ie_balancing · mergeIE keeps '+merged.balancing.length});
 await test('Excel report A–H exports all sheets',async()=>{const src=B.getSources();const obd=src.ie.styles.find(s=>s.style==='5209');const plan=src.plan.find(p=>p.month==='2026-09'&&/Line 6/.test(p.line));B.select(plan.id,obd.id);const name=B.exportExcel();const f=r.saved.find(x=>x.name===name);assert(f&&f.sheets.length===8,JSON.stringify(f));return name+' · '+JSON.stringify(f.rows)});
 await test('Old PROD data untouched: styles / operations / updates counts unchanged after balancing use',async()=>{const s=app.getState();assert.equal(s.styles.length,4);assert.equal(s.operations.length,65);return 'styles 4 · ops 65 · updates '+s.updates.length});
 r.close();fs.writeFileSync(path.resolve(__dirname,'balancing_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
 function pct(v){return v==null?'—':(v*100).toFixed(0)+'%'}
})();
