const fs=require('fs'),path=require('path'),assert=require('assert');const ROOT=process.env.VRT_ROOT||path.resolve(__dirname,'../..'),DL='/mnt/user-data/uploads/Downloads/';
const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');
const jfile=(p,name)=>{const b=fs.readFileSync(p);return{name:name||path.basename(p),text:async()=>b.toString('utf8'),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
const bfile=(name,buf)=>({name,text:async()=>Buffer.from(buf).toString('utf8'),arrayBuffer:async()=>buf});
async function runtime(){const r=createRuntime(ROOT+'/production_plan_capacity_v1.html');r.ctx.confirm=()=>true;r.ctx.alert=()=>{};r.saved={};r.load();const X=r.ctx.XLSX;X.writeFile=(wb,name)=>{r.saved[name]=X.write(wb,{type:'buffer',bookType:'xlsx'})};r.ctx.URL.createObjectURL=b=>{r.lastBlob=b;return 'blob:x'};await new Promise(res=>setTimeout(res,300));if(r.ctx.VRT_LOCAL_READY)await r.ctx.VRT_LOCAL_READY;return r}
const q=(r,expr)=>JSON.parse(r.run('JSON.stringify('+expr+')'));
(async()=>{let pass=0,fail=0;const T=async(n,f)=>{try{const d=await f();pass++;console.log('PASS',n,'·',d)}catch(e){fail++;console.log('FAIL',n,'·',e.message)}};
 const r=await runtime();
 await T('import source Excel → 705',async()=>{await r.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx'));await new Promise(res=>setTimeout(res,400));await r.ctx.confirmPlanImport512();return q(r,'DATA.records.length')});
 await T('export XLSX → re-import own export → same 705 ids, preview says replace',async()=>{r.ctx.exportPlanXlsx();const buf=r.saved['VRT_PRODUCTION_PLAN.xlsx'];assert(buf,'no xlsx saved');const ids0=q(r,'DATA.records.map(x=>x.id).sort()');await r.ctx.importFile(bfile('VRT_PRODUCTION_PLAN.xlsx',buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength)));await new Promise(res=>setTimeout(res,400));const pend=q(r,'PLAN_PENDING512?{n:PLAN_PENDING512.recs.length,skip:PLAN_PENDING512.skip.length}:null');assert(pend&&pend.n===705,'pending '+JSON.stringify(pend));await r.ctx.confirmPlanImport512();const ids1=q(r,'DATA.records.map(x=>x.id).sort()');assert.deepStrictEqual(ids1,ids0);return 'ids identical, skipped '+pend.skip});
 await T('export CSV → re-import user\'s real VRT_PRODUCTION_PLAN.csv → 705 identical ids',async()=>{const ids0=q(r,'DATA.records.map(x=>x.id).sort()');await r.ctx.importFile(jfile(DL+'VRT_PRODUCTION_PLAN.csv'));await new Promise(res=>setTimeout(res,400));const pend=q(r,'PLAN_PENDING512?PLAN_PENDING512.recs.length:0');assert.equal(pend,705);await r.ctx.confirmPlanImport512();const ids1=q(r,'DATA.records.map(x=>x.id).sort()');assert.deepStrictEqual(ids1,ids0);return '705 ids identical'});
 await T('backup JSON → wipe → restore → 705 + versions kept',async()=>{r.ctx.planBackup();const blob=r.lastBlob;assert(blob,'no blob');const text=await blob.text();const d=JSON.parse(text);assert.equal(d.tool,'production_plan');assert.equal(d.records.length,705);r.run('DATA={records:[],source:"",savedAt:""}');await r.ctx.save();assert.equal(q(r,'DATA.records.length'),0);await r.ctx.planRestore({name:'VRT_production_plan_backup.json',text:async()=>text});await new Promise(res=>setTimeout(res,300));assert.equal(q(r,'DATA.records.length'),705);return 'restored 705 · versions '+q(r,'VERS.length')});
 await T('restore a wrong JSON → readable error, data untouched',async()=>{await r.ctx.planRestore({name:'x.json',text:async()=>'{"foo":1}'});assert.equal(q(r,'DATA.records.length'),705);return (r.elements.get('toast')||{}).textContent});
 r.close();console.log(pass+'/'+(pass+fail)+' PASS');process.exitCode=fail?1:0})();
