/* Stage B/C importer tests: old + new Needle / Spare Part layouts, idempotent re-import, mismatches. */
const path=require('path'),fs=require('fs'),assert=require('assert');
const ROOT=path.resolve(__dirname,'../..'),UP='/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/';
global.window=global;global.XLSX=require(ROOT+'/vendor/xlsx.full.min.js');
require(ROOT+'/vrt-data-core-v39.js');require(ROOT+'/vrt-import-core-v40.js');
const I=global.VRTImport40,C=global.VRTData39;
const read=(p,cellDates)=>XLSX.read(fs.readFileSync(p),{type:'buffer',raw:true,cellDates:!!cellDates});
const results=[];const T=(name,fn)=>{try{const d=fn();results.push({name,status:'PASS',detail:d});console.log('PASS',name,d?'· '+d:'')}catch(e){results.push({name,status:'FAIL',detail:e.message});console.log('FAIL',name,'·',e.message)}};
const byDate=(p,d)=>p.stockReports.find(r=>r.start===d);
const sum=(rows,k)=>rows.reduce((s,r)=>s+(Number(r[k])||0),0);

// ── NEW needle layout (user upload, 9-1 … 9-28; 9-19+ has Received column) ──
const needleNew=I.dailyChanges(read(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx',true),'Daily Needles Change Report 24 to28 Sept.xlsx');
T('New needle file: 23 daily sheets parsed, dates from tab names with year 2026',()=>{assert.strictEqual(needleNew.stockReports.length,23);const ds=needleNew.stockReports.map(r=>r.start);assert(ds.includes('2026-09-01')&&ds.includes('2026-09-14')&&ds.includes('2026-09-28'),ds.join(','));return ds[0]+' … '+ds.at(-1)});
T('New needle 9-28: Opening/Received/Issued/Closing columns detected (K:V lines)',()=>{const r=byDate(needleNew,'2026-09-28');assert.deepStrictEqual([r.layout.opening,r.layout.received,r.layout.issued,r.layout.closing,r.layout.remark],[3,4,5,6,7]);assert.strictEqual(Object.keys(r.layout.lines).length,12);assert.strictEqual(r.layout.lines[10],1);assert.strictEqual(r.layout.lines[21],12);const dbx=r.items.find(x=>x.name==='DBX1'&&x.size==='100/16');assert.strictEqual(dbx.openingQty,560);assert.strictEqual(dbx.issuedQty,20);assert.strictEqual(dbx.closingQty,540);assert.strictEqual(dbx.receivedQty,null);assert.strictEqual(dbx.arithmetic,'opening-issued');assert.strictEqual(dbx.reasonClass,'changeover');const l=Object.fromEntries(dbx.lineAllocations.map(a=>[a.line,a.qty]));assert.deepStrictEqual(l,{'Line 1':10,'Line 2':3,'Line 6':2,'Line 9':2,'Line 10':3});return 'DBX1 100/16 open 560 issued 20 close 540, lines '+JSON.stringify(l)});
T('New needle 9-19: Received 500 kept separately; opening-issued=closing still accepted',()=>{const r=byDate(needleNew,'2026-09-19');const dbx=r.items.find(x=>x.name==='DBX1'&&x.size==='100/16');assert.strictEqual(dbx.openingQty,620);assert.strictEqual(dbx.receivedQty,500);assert.strictEqual(dbx.issuedQty,10);assert.strictEqual(dbx.closingQty,610);assert.strictEqual(dbx.arithmetic,'opening-issued');assert.strictEqual(dbx.reasonClass,'damage');return 'rule='+r.layout.rule});
T('New needle 9-1: old layout inside same workbook (J:U lines), title date 2026-01-09 corrected to 2026-09-01 by tab',()=>{const r=byDate(needleNew,'2026-09-01');assert.deepStrictEqual([r.layout.opening,r.layout.issued,r.layout.closing,r.layout.remark],[3,4,5,6]);assert.strictEqual(r.layout.received,-1);assert.strictEqual(r.layout.lines[9],1);const w=needleNew.warnings.find(x=>/^9-1：.*日／月互換/.test(x));assert(w,'expected swap warning');const dcx=r.items.find(x=>x.name==='DCX27'&&x.size==='100/16');assert.strictEqual(dcx.issuedQty,10);assert.strictEqual(dcx.lineAllocations.reduce((s,a)=>s+a.qty,0),10);return w});
T('New needle totals: issued sum per sheet equals source totals row (9-28 = 50)',()=>{const r=byDate(needleNew,'2026-09-28');assert.strictEqual(sum(r.items,'issuedQty'),50);assert.strictEqual(sum(r.items,'openingQty'),7440);assert.strictEqual(sum(r.items,'closingQty'),7390);const bad=needleNew.warnings.filter(x=>/合計列/.test(x));assert.strictEqual(bad.length,0,bad.join(' | '));return 'no totals-row mismatch warnings'});
T('Needle change records: reasonClass classified; changeover not merged with damage',()=>{const cs=needleNew.needleChanges;const cls={};cs.forEach(c=>cls[c.reasonClass]=(cls[c.reasonClass]||0)+c.qty);assert(cls.changeover>0&&cls.damage>0);assert(cs.every(c=>c.needleType&&c.size&&c.qty>0&&/^Line \d+$|Unassigned/.test(c.line)));return JSON.stringify(cls)});

// ── OLD needle layout (bundled release_sources, 9-1 … 9-22 all old layout) ──
const needleOld=I.dailyChanges(read(path.resolve(__dirname,'../../../baseline/vrt-prod-main')+'/release_sources/Needle_Change_202609.xlsx',false),'Daily Needles Change Report (week-3).xlsx');
T('Old needle file (cellDates:false serial dates): 19 sheets, all old layout, same quantities as new file for overlapping days (9-17/9-18 were restated at source, excluded)',()=>{assert.strictEqual(needleOld.stockReports.length,19);for(const d of ['2026-09-01','2026-09-10']){const a=byDate(needleOld,d),b=byDate(needleNew,d);assert(a&&b,d);assert.strictEqual(sum(a.items,'issuedQty'),sum(b.items,'issuedQty'),d+' issued');assert.strictEqual(sum(a.items,'openingQty'),sum(b.items,'openingQty'),d+' opening')}return 'overlap 9-1/9-10/9-18 identical'});
T('Old vs new parser identity: same item IDs and change IDs for identical source rows (idempotent across file versions)',()=>{const a=byDate(needleOld,'2026-09-10'),b=byDate(needleNew,'2026-09-10');assert.deepStrictEqual(a.items.map(x=>x.id),b.items.map(x=>x.id));const ca=needleOld.needleChanges.filter(c=>c.date==='2026-09-10').map(c=>c.id).sort(),cb=needleNew.needleChanges.filter(c=>c.date==='2026-09-10').map(c=>c.id).sort();assert.deepStrictEqual(ca,cb);return ca.length+' change ids equal'});

// ── Spare parts: NEW (user upload 9-10 … 9-28; 9-18+ new layout with reversed header text) ──
const partsNew=I.dailyChanges(read(UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx',true),'Daily Spare Part Change Report.xlsx');
T('New parts file: 15 sheets, 9-10 (title 2026-10-09) corrected to 2026-09-10',()=>{assert.strictEqual(partsNew.stockReports.length,15);assert(byDate(partsNew,'2026-09-10'),'9-10 missing');assert(byDate(partsNew,'2026-09-28'),'9-28 missing');return partsNew.stockReports.map(r=>r.start.slice(5)).join(',')});
T('New parts 9-28: reversed header text (D says Closing, G says Opening) → numbers decide: D=opening, G=closing, warning issued, values untouched',()=>{const r=byDate(partsNew,'2026-09-28');assert.strictEqual(r.layout.opening,3);assert.strictEqual(r.layout.closing,6);assert.strictEqual(r.layout.issued,5);assert.strictEqual(r.layout.received,4);assert.strictEqual(r.layout.headerTextReversed,true);assert.strictEqual(r.layout.columnsSwapped,false);const hook=r.items.find(x=>/Single Needle Rotary Hook/.test(x.name));assert.strictEqual(hook.openingQty,8);assert.strictEqual(hook.issuedQty,1);assert.strictEqual(hook.closingQty,7);assert.strictEqual(hook.arithmetic,'opening-issued');assert.deepStrictEqual(hook.lineAllocations,[{line:'Line 3',qty:1}]);assert.strictEqual(hook.reasonClass,'unknown');const w=partsNew.warnings.find(x=>/^9-28：表頭/.test(x));assert(w,'expected header-text warning');return w});
T('New parts 9-28: totals row (851 / 6 / 845) matches detail sums',()=>{const r=byDate(partsNew,'2026-09-28');assert.strictEqual(sum(r.items,'openingQty'),851);assert.strictEqual(sum(r.items,'issuedQty'),6);assert.strictEqual(sum(r.items,'closingQty'),845);return '851/6/845'});
T('New parts 9-17 (old layout, Column1 stray header): Feed Dog 57-3=54, lines 4/6/8',()=>{const r=byDate(partsNew,'2026-09-17');const fd=r.items.find(x=>/Feed Dog 送布牙/.test(x.name));assert.strictEqual(fd.openingQty,57);assert.strictEqual(fd.issuedQty,3);assert.strictEqual(fd.closingQty,54);assert.deepStrictEqual(fd.lineAllocations.map(a=>a.line),['Line 4','Line 6','Line 8']);assert.strictEqual(r.layout.lines[9],1);return 'ok'});

// ── Spare parts OLD bundled file (9-10 … 9-18 old layout; 9-18 title '/9/2026' no day) ──
const partsOld=I.dailyChanges(read(path.resolve(__dirname,'../../../baseline/vrt-prod-main')+'/release_sources/Parts_Change_202609.xlsx',false),'Daily Spare Part Change Report.xlsx');
T('Old parts file: 8 sheets incl. 9-18 whose title has no day ("/9/2026") → date from tab',()=>{assert.strictEqual(partsOld.stockReports.length,8);assert(byDate(partsOld,'2026-09-18'));return partsOld.stockReports.map(r=>r.start.slice(5)).join(',')});
T('Old parts vs new parts overlapping day 9-17: both parse; source workbook was restated (rows 50+ renumbered) → differences are reported, not hidden',()=>{const a=byDate(partsOld,'2026-09-17'),b=byDate(partsNew,'2026-09-17');assert.strictEqual(a.items.length,80);assert.strictEqual(b.items.length,80);let sameId=0,changed=0;const mb=new Map(b.items.map(x=>[x.id,x]));for(const x of a.items){const y=mb.get(x.id);if(!y)continue;sameId++;if(x.openingQty!==y.openingQty||x.issuedQty!==y.issuedQty)changed++}assert(sameId>=40);const m=C.mergeReports(partsOld.stockReports,[b]);const merged=m.records.find(r=>r.id===b.id);assert(merged.history.length===1,'prior version kept in history');return sameId+' same IDs, '+changed+' restated quantities; mergeReports keeps prior version in history'});

// ── Idempotency: same file twice through the real mergeImport-equivalent (ids + fingerprints) ──
T('Same file parsed twice → identical fingerprints and change IDs (no duplicates on re-import)',()=>{const again=I.dailyChanges(read(UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx',true),'Daily Spare Part Change Report.xlsx');assert.deepStrictEqual(partsNew.stockReports.map(r=>[r.id,r.fingerprint]),again.stockReports.map(r=>[r.id,r.fingerprint]));assert.deepStrictEqual(partsNew.partChanges.map(c=>c.id),again.partChanges.map(c=>c.id));const m=C.mergeReports(partsNew.stockReports,again.stockReports);assert.strictEqual(m.unchanged,15);assert.strictEqual(m.added+m.updated,0);return 'mergeReports unchanged=15'});

// ── Synthetic edge cases ──
function synth(rows,opts){const wb=XLSX.utils.book_new();const head=opts.newLayout?['លរ No. 数字','ប្រភេទម្ជុល Needle Type 针型','ទំហំ SIZE 尺寸','Opening Balance','Received','Issued Needle','Closing Balance','Remark','','','Line# 1','Line# 2','Line# 3','Line# 4','Line# 5','Line# 6','Line# 7','Line# 8','Line# 9','Line# 10','Line# 11','Line# 12']:['លរ No. 数字','ប្រភេទម្ជុល Needle Type 针型','ទំហំ SIZE 尺寸','Stock Left','Issued Needle','Balance','Remark','','','Line# 1','Line# 2','Line# 3','Line# 4','Line# 5','Line# 6','Line# 7','Line# 8','Line# 9','Line# 10','Line# 11','Line# 12'];const aoa=[['','','Daily Needles Change Report','','','','',opts.title||'','','',''],head,...rows];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(aoa),opts.sheet||'9-3');return wb}
T('Edge: line allocation > issued → warning, row preserved, no invented line',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,10,90,'',null,null,5,8]],{title:'3/9/2026'}),'x.xlsx');const it=p.stockReports[0].items[0];assert.strictEqual(it.issuedQty,10);assert.strictEqual(it.lineAllocations.reduce((s,a)=>s+a.qty,0),13);assert(p.warnings.some(w=>/線別合計 13 大於發放 10/.test(w)));assert.strictEqual(p.needleChanges.length,2);return p.warnings[0]});
T('Edge: issued > allocated → Unassigned qty computed and flagged, not silently changed',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,10,90,'Damage',null,null,3]],{title:'3/9/2026'}),'x.xlsx');const it=p.stockReports[0].items[0];assert.strictEqual(it.unassignedQty,7);const u=p.needleChanges.find(c=>c.unassigned);assert(u&&u.qty===7&&u.line==='未分線 / Unassigned');assert(p.warnings.some(w=>/未分線 7/.test(w)));return 'unassigned 7'});
T('Edge: stock arithmetic mismatch → warning, source values kept',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,10,85,'',null,null,10]],{title:'3/9/2026'}),'x.xlsx');const it=p.stockReports[0].items[0];assert.strictEqual(it.arithmetic,'mismatch');assert.strictEqual(it.closingQty,85);assert(p.warnings.some(w=>/≠ 結存 85/.test(w)));return 'kept 100/10/85'});
T('Edge: received present, sheet follows opening+received-issued=closing → accepted with that rule',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,50,10,140,'',null,null,10]],{title:'3/9/2026',newLayout:true}),'x.xlsx');const it=p.stockReports[0].items[0];assert.strictEqual(it.arithmetic,'opening+received-issued');assert.strictEqual(it.receivedQty,50);assert.strictEqual(p.stockReports[0].layout.rule,'opening+received-issued');return 'rule detected'});
T('Edge: blank remark → reasonClass unknown; missing line allocation → total only + warning',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,10,90,'']],{title:'3/9/2026'}),'x.xlsx');const it=p.stockReports[0].items[0];assert.strictEqual(it.reasonClass,'unknown');assert.strictEqual(it.unassignedQty,10);assert.strictEqual(p.needleChanges.length,1);assert(p.needleChanges[0].unassigned);return 'unknown + unassigned 10'});
T('Edge: title without year and file name without year → current-year assumption is warned',()=>{const p=I.dailyChanges(synth([[1,'DBX1','90/14',100,10,90,'']],{title:'',sheet:'9-3'}),'needles.xlsx');assert(p.warnings.some(w=>/沒有年份/.test(w)));assert(/-09-03$/.test(p.stockReports[0].start));return p.stockReports[0].start});
T('Native export round-trip (Record ID / Date / Part Type) still works',()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{'Record ID':'PC-X','Date':'2026-09-05','Part Type':'Feed Dog','Size':'small','Line':'Line 2','Qty':2,'Reason':'Broken'}]),'Part Change');const p=I.dailyChanges(wb,'Part_Change.xlsx');assert.strictEqual(p.partChanges.length,1);assert.strictEqual(p.partChanges[0].reasonClass,'broken');return 'ok'});

fs.writeFileSync(path.resolve(__dirname,'importer_test_results.json'),JSON.stringify(results,null,2));
const fails=results.filter(r=>r.status==='FAIL').length;console.log('\n'+(results.length-fails)+'/'+results.length+' PASS');process.exitCode=fails?1:0;
