/* Real-data checks: restore Paul's backups into sewing / cutting / orders / plan, export, re-import source Excel, mock-GS roundtrip. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=process.env.VRT_ROOT||path.resolve(__dirname,'../..'),DL='/mnt/user-data/uploads/Downloads/',url='https://script.google.com/macros/s/MOCK_PROD/exec';
const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness'),{createGas}=require(ROOT+'/qa/v41/gas_harness');
const jfile=(p,name)=>{const b=fs.readFileSync(p);return{name:name||path.basename(p),text:async()=>b.toString('utf8'),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
const ev=f=>({target:{files:[f],value:''}});
async function runtime(html,gas){const r=createRuntime(ROOT+'/'+html);if(gas){r.ctx.fetch=gas.fetch;r.ctx.localStorage.setItem('vrt_portal_gas_url',url)}r.ctx.confirm=()=>true;r.ctx.alert=()=>{};r.ctx.pdfjsLib={GlobalWorkerOptions:{},getDocument:()=>({promise:Promise.reject(new Error('no pdf in harness'))})};r.saved=[];r.load();try{const proto=Object.getPrototypeOf(r.document.body);if(!proto.insertAdjacentHTML)proto.insertAdjacentHTML=function(pos,html){this.innerHTML=(pos==='afterbegin'||pos==='beforebegin')?html+this.innerHTML:this.innerHTML+html}}catch(_){}try{const X=r.ctx.XLSX;if(X)X.writeFile=(wb,name)=>{r.saved.push({name,sheets:wb.SheetNames.slice()})}}catch(_){}await new Promise(res=>setTimeout(res,200));if(r.ctx.VRT_LOCAL_READY)await r.ctx.VRT_LOCAL_READY;if(gas){r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(ROOT+'/vrt-smart-sync-v3.js','utf8'))}await new Promise(res=>setTimeout(res,300));return r}
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
const idbCount=async(r,db,store)=>{const d=r.dbs.get(db);if(!d)return -1;const s=d.stores.get(store);return s?s.values.size:-1};
(async()=>{
 // ── SEWING ───────────────────────────────────────────────────────────────
 await test('Sewing: restore real backup (5,009 daily rows) → dedupAndNorm count, eff handling, date range',async()=>{const r=await runtime('sewing_v5.html');try{const bk=JSON.parse(fs.readFileSync(DL+'sewing_backup_2026-09-28.json','utf8'));await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await new Promise(res=>setTimeout(res,500));const st=JSON.parse(r.run('JSON.stringify({n:DB.length,eff:EFF_DB.length,dates:DB.map(x=>x.date).sort(),srcs:DB.reduce((m,x)=>(m[x.tSrc||"?"]=(m[x.tSrc||"?"]||0)+1,m),{})})'));const n=st.n,eff=st.eff,dates=st.dates,srcs=st.srcs;return 'backup '+bk.daily.length+' → DB '+n+' (dedup removed '+(bk.daily.length-n)+') · eff '+eff+' · '+dates[0]+'…'+dates.at(-1)+' · tSrc '+JSON.stringify(srcs)}finally{r.close()}});
 await test('Sewing: exports (daily/weekly/records/monthly/yearly Excel, eff Excel, backup JSON) run without exceptions after restore',async()=>{const r=await runtime('sewing_v5.html');try{await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await new Promise(res=>setTimeout(res,300));const errs=[];for(const m of ['daily','weekly','records','monthly','yearly']){try{r.ctx.exportExcel(m)}catch(e){errs.push(m+': '+e.message)}}try{r.ctx.exportEffExcel&&r.ctx.exportEffExcel()}catch(e){errs.push('eff: '+e.message)}try{await r.ctx.backupData()}catch(e){errs.push('backup: '+e.message)}assert(!errs.length,errs.join(' | '));return 'ok'}finally{r.close()}});
 await test('Sewing: re-import source "Daily Production Output Report as of September" over restored data → same-day rows replaced, not duplicated',async()=>{const r=await runtime('sewing_v5.html');try{await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await new Promise(res=>setTimeout(res,300));const q=expr=>JSON.parse(r.run('JSON.stringify('+expr+')'));const before=q('DB.length'),beforeSep=q('DB.filter(x=>x.date>="2026-09-01").length');const f=jfile(DL+'Daily Production Output Report as of September, 2026.xlsx');let msg='';try{r.run('pendingFiles=[]');r.ctx.__f=f;r.run('pendingFiles.push(__f)');await r.ctx.doImport();await new Promise(res=>setTimeout(res,800));const pend=q('pendingRecs.length'),msgText=r.elements.get('importMsg')?.textContent||'';msg='pending '+pend+' · "'+msgText.slice(0,120)+'"';const cb=r.elements.get('sewImportConflictConfirm512');if(cb)cb.checked=true;await r.ctx.confirmImport()}catch(e){msg+=' · import threw: '+e.message}await new Promise(res=>setTimeout(res,500));const after=q('DB.length'),afterSep=q('DB.filter(x=>x.date>="2026-09-01").length');const dup=q('DB.length-new Set(DB.map(x=>[x.date,x.section,x.lineNo,x.styleNo,x.po,x.color,x.size,x.tSrc].join("|"))).size');assert.equal(dup,0,'duplicate keys '+dup);return msg+' · total '+before+'→'+after+' · Sep rows '+beforeSep+'→'+afterSep+' · duplicate keys 0'}finally{r.close()}});
 await test('Sewing: mock-GS push from device A, pull on device B → same row count; second push uploads 0',async()=>{const g=createGas(),a=await runtime('sewing_v5.html',g),b=await runtime('sewing_v5.html',g);try{await a.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await new Promise(res=>setTimeout(res,300));const q=(rt,expr)=>JSON.parse(rt.run('JSON.stringify('+expr+')'));const log=rt=>(rt.elements.get('vcProdLog')||rt.elements.get('vcLog')||{textContent:''}).textContent;await a.ctx.vcPush();const posts=g.calls.filter(c=>c.p&&c.p.action==='smartBucket').length,commits=g.calls.filter(c=>c.p&&c.p.action==='smartCommit').length,manifest=g.ctx.readSmartManifest_('sewing');assert(manifest,'no manifest after push · '+log(a).slice(-300));const buckets=Object.keys(manifest.buckets);await b.ctx.vcPull();await new Promise(res=>setTimeout(res,800));const na=q(a,'DB.length'),nb=q(b,'DB.length');assert.equal(nb,na,'B '+nb+' vs A '+na+' · '+log(b).slice(-300));const c0=g.calls.length;await a.ctx.vcPush();await b.ctx.vcPull();const extra=g.calls.slice(c0).filter(c=>c.p&&/^smart(Bucket|Commit)$/.test(c.p.action)).map(c=>c.p.action);return 'A '+na+' rows → '+posts+' bucket POSTs + '+commits+' commit, '+buckets.length+' buckets · B '+nb+' rows · unchanged re-sync transfers: '+(extra.length?extra.join(','):'none')}finally{a.close();b.close()}});
 // ── CUTTING ──────────────────────────────────────────────────────────────
 await test('Cutting: restore real backup (18,663 rows) → count, date range, sections',async()=>{const r=await runtime('cutting_v3.html');try{await r.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')));await new Promise(res=>setTimeout(res,500));const st=JSON.parse(r.run('JSON.stringify({n:CUT.length,dates:[CUT.map(x=>x.date).sort()[0],CUT.map(x=>x.date).sort().at(-1)],secs:CUT.reduce((m,x)=>(m[x.section||"?"]=(m[x.section||"?"]||0)+1,m),{}),dup:CUT.length-new Set(CUT.map(x=>[x.date,x.section,x.lineNo,x.styleNo].join("|"))).size})'));const n=st.n,dates=st.dates,secs=st.secs,dupKeys=st.dup;return 'CUT '+n+' · '+dates[0]+'…'+dates.at(-1)+' · sections '+JSON.stringify(secs)+' · rows sharing date|section|line|style: '+dupKeys}finally{r.close()}});
 await test('Cutting: every Excel export type runs (documents the weekly export crash if present)',async()=>{const r=await runtime('cutting_v3.html');try{await r.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')));await new Promise(res=>setTimeout(res,300));const errs=[];for(const t of ['daily','weekly','monthly','all','query','wip','styles']){try{r.ctx.xls(t)}catch(e){errs.push(t+': '+e.message)}}return (errs.length?'ERRORS → '+errs.join(' | '):'all export types ok')+' · saved: '+r.saved.map(x=>x.name).join(', ')}finally{r.close()}});
 // ── ORDERS ───────────────────────────────────────────────────────────────
 await test('Orders: restore real backup → store counts match file; restore twice → no growth',async()=>{const r=await runtime('orders_v3.html');try{const bk=JSON.parse(fs.readFileSync(DL+'orders_v3_backup_2026-09-30.json','utf8'));await r.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await new Promise(res=>setTimeout(res,500));const c1=[await idbCount(r,'FactoryDB','po_lines'),await idbCount(r,'FactoryDB','weekly_snapshots'),await idbCount(r,'FactoryDB','po_headers')];await r.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await new Promise(res=>setTimeout(res,500));const c2=[await idbCount(r,'FactoryDB','po_lines'),await idbCount(r,'FactoryDB','weekly_snapshots'),await idbCount(r,'FactoryDB','po_headers')];assert.deepEqual(c1,[bk.po_lines.length,bk.weekly_snapshots.length,bk.po_headers.length]);assert.deepEqual(c2,c1);return 'po_lines '+c1[0]+' · snapshots '+c1[1]+' · headers '+c1[2]+' · idempotent'}finally{r.close()}});
 await test('Orders: CSV exports run after restore',async()=>{const r=await runtime('orders_v3.html');try{await r.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await new Promise(res=>setTimeout(res,500));const errs=[];for(const fn of ['exportOrderLinesCsv','expMasterCsv','expPivot','expWeeklyCsv','expQcCsv','backup']){try{if(typeof r.ctx[fn]==='function')await r.ctx[fn]()}catch(e){errs.push(fn+': '+e.message)}}return errs.length?'ERRORS → '+errs.join(' | '):'ok'}finally{r.close()}});
 // ── PRODUCTION PLAN ──────────────────────────────────────────────────────
 await test('Plan: import source Excel (Production Plan From July Until Dec_2026) → records, months, Line 12 rule; then export CSV/XLSX; CSV re-import currently impossible',async()=>{const r=await runtime('production_plan_capacity_v1.html');try{await r.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx','Production  Plan From July Until  Dec_2026 (1).xlsx'));await new Promise(res=>setTimeout(res,500));const q=expr=>JSON.parse(r.run('JSON.stringify('+expr+')'));const pend=q('PLAN_PENDING512?PLAN_PENDING512.recs.length:0');assert(pend,'no pending: '+(r.elements.get('toast')?.textContent||''));await r.ctx.confirmPlanImport512();await new Promise(res=>setTimeout(res,300));const recs=q('DATA.records'),months={};recs.forEach(x=>months[x.month]=(months[x.month]||0)+1);const l12=recs.filter(x=>/12/.test(String(x.line))&&x.month>='2026-08').length;const csvRows=fs.readFileSync(DL+'VRT_PRODUCTION_PLAN.csv','utf8').split(/\r?\n/).filter(Boolean).length-1;let exp='';try{r.ctx.exportPlanCsv();r.ctx.exportPlanXlsx();exp='exports ok'}catch(e){exp='export threw: '+e.message}return 'records '+recs.length+' (your CSV export has '+csvRows+') · months '+JSON.stringify(months)+' · Line12 from Aug: '+l12+' · '+exp+' · saved '+r.saved.map(x=>x.name).join(',')}finally{r.close()}});
 // ── CLOUD ROUNDTRIPS for cutting / orders / plan ──
 async function roundtrip(name,html,tool,seed,pushFn,pullFn,countExpr){const g=createGas(),a=await runtime(html,g),b=await runtime(html,g);try{await seed(a);await new Promise(res=>setTimeout(res,400));const c0=g.calls.length;await pushFn(a);const posts=g.calls.slice(c0).filter(c=>c.p&&c.p.action==='smartBucket').length,manifest=g.ctx.readSmartManifest_(tool);assert(manifest,'no manifest after push');const buckets=Object.keys(manifest.buckets).length;await pullFn(b);await new Promise(res=>setTimeout(res,800));const q=(rt)=>JSON.parse(rt.run('JSON.stringify('+countExpr+')'));const na=q(a),nb=q(b);assert.equal(JSON.stringify(nb),JSON.stringify(na),'B '+JSON.stringify(nb)+' vs A '+JSON.stringify(na));const c1=g.calls.length;await pushFn(a);await pullFn(b);const extra=g.calls.slice(c1).filter(c=>c.p&&/^smart(Bucket|Commit)$/.test(c.p.action)).map(c=>c.p.action);return 'A '+JSON.stringify(na)+' → '+posts+' bucket POSTs, '+buckets+' buckets · B '+JSON.stringify(nb)+' · unchanged re-sync transfers: '+(extra.length?extra.join(','):'none')}finally{a.close();b.close()}}
 await test('Cutting: mock-GS roundtrip (18,663 rows)',()=>roundtrip('cutting','cutting_v3.html','cutting',async a=>{await a.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')))},a=>a.ctx.vcPush(),b=>b.ctx.vcPull(),'CUT.length'));
 await test('Orders: mock-GS roundtrip (549 lines + 3,602 weekly snapshots in meta)',()=>roundtrip('orders','orders_v3.html','orders',async a=>{await a.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')))},a=>a.ctx.ordCloudPush(),b=>b.ctx.ordCloudPull(),'[(APP.orders||[]).length,(APP.weekly||APP.snapshots||[]).length]'));
 await test('Plan: mock-GS roundtrip (705 records)',()=>roundtrip('prodplan','production_plan_capacity_v1.html','prodplan',async a=>{await a.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx','Production  Plan From July Until  Dec_2026 (1).xlsx'));await new Promise(res=>setTimeout(res,500));await a.ctx.confirmPlanImport512()},a=>a.ctx.cloudPush(true),b=>b.ctx.cloudPull(true),'DATA.records.length'));
 fs.writeFileSync(path.resolve(__dirname,'realdata_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');
})();
