/* Final QC v4.13: sewing-line Top-3 defect KPI import, separation from Final QC, comparison tab, idempotency, real-GS roundtrip. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'../..'),{createRuntime}=require(root+'/qa/v39/runtime_harness'),{createGas}=require(root+'/qa/v41/gas_harness');
const url='https://script.google.com/macros/s/MOCK_PROD/exec',UP='/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/';
const file=(p,name)=>{const b=fs.readFileSync(p);return{name,arrayBuffer:async()=>b}};
const kpiFile=()=>file(UP+'a727f1ff-VRT_Weekly_Top_3_defect_KPI__________21_25_SEP_2026.xlsx','VRT_Weekly_Top_3_defect_KPI_每周质量会议报告_21_25_SEP_2026.xlsx'),daily=()=>file(root+'/release_sources/Final_QC_20260919.xlsx','Final_QC_20260919.xlsx'),weekly=()=>file(root+'/release_sources/QC_Weekly_20260914_19.xlsx','QC_Weekly_20260914_19.xlsx');
async function runtime(gas){const r=createRuntime(root+'/vrt_final_qc_v1.html');if(gas)r.ctx.fetch=gas.fetch;r.load();await r.ctx.VRT_LOCAL_READY;if(gas){r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(root+'/vrt-smart-sync-v3.js','utf8'))}return r}
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,e.message)}}
const qc=r=>r.ctx.QC,st=r=>qc(r).getState(),app=r=>r.elements.get('qcContent').innerHTML;
(async()=>{
 await test('KPI workbook imports as sewingkpi: 54 date/line rows (12 empty template rows skipped), 5 days, 11 lines; Final QC records untouched (0)',async()=>{const r=await runtime();try{await qc(r).importFiles([kpiFile()]);const pre=qc(r).getImportState();assert.equal(pre.preview.length,0,'must not enter Final QC records');await qc(r).commit();const s=st(r);assert.equal(s.kpi.length,54);assert.equal(s.records.length,0);assert.equal(new Set(s.kpi.map(x=>x.date)).size,5);assert.equal(new Set(s.kpi.map(x=>x.line)).size,11);const t=r.ctx.VRTImport40.qcKpiTotals(s.kpi);assert.equal(t.output,21575);assert.equal(t.defects,1789);return 'output 21575 / defects 1789 / rate '+(t.rate*100).toFixed(2)+'%'}finally{r.close()}});
 await test('Same KPI file twice → 0 added, 0 updated, 66 unchanged; no history growth',async()=>{const r=await runtime();try{await qc(r).importFiles([kpiFile()]);await qc(r).commit();await qc(r).importFiles([kpiFile()]);const pre=qc(r).getImportState();assert.equal(pre.preview.length,0);await qc(r).commit();const s=st(r);assert.equal(s.kpi.length,54);assert(s.kpi.every(x=>!(x.history||[]).length));return 'idempotent'}finally{r.close()}});
 await test('KPI + Final QC daily + weekly coexist; compare tab joins by date/line; sewingkpi tab renders lines, days, Top defects',async()=>{const r=await runtime();try{await qc(r).importFiles([kpiFile(),daily(),weekly()]);await qc(r).commit();const s=st(r);assert.equal(s.kpi.length,54);assert(s.records.length>=78,'final qc records '+s.records.length);r.elements.get('qcPeriod').value='all';qc(r).tab('sewingkpi');let h=app(r);assert(/車縫缺點率/.test(h)&&/Line 7/.test(h)&&/Stain/.test(h),'kpi tab content');qc(r).tab('compare');h=app(r);assert(/日期 × 線別 比對/.test(h)&&/兩端/.test(h)||/缺車縫 KPI|缺 Final QC/.test(h),'compare content');const both=(h.match(/兩端一致|優先改善|回饋斷層|已修補/g)||[]).length;assert(both>0,'expected joined rows, got '+both);qc(r).tab('dashboard');const d=app(r);assert(!/車縫缺點率/.test(d),'Final QC dashboard must not mix KPI');return 'joined rows '+both}finally{r.close()}});
 await test('Final QC totals are not changed by KPI rows (qcTotals over records only); header shows KPI count separately',async()=>{const r=await runtime();try{await qc(r).importFiles([daily()]);await qc(r).commit();const before=r.ctx.VRTImport40.qcTotals(st(r).records);await qc(r).importFiles([kpiFile()]);await qc(r).commit();const after=r.ctx.VRTImport40.qcTotals(st(r).records);assert.deepStrictEqual(before,after);assert.equal(r.elements.get('qcHKpi').textContent,'54');return 'inspected '+after.inspected+' unchanged'}finally{r.close()}});
 await test('Delete + JSON backup/restore keep KPI rows; export on KPI tab produces KPI sheet',async()=>{const r=await runtime();try{await qc(r).importFiles([kpiFile()]);await qc(r).commit();const id=st(r).kpi[0].id;r.ctx.confirm=()=>true;await qc(r).remove(id);assert(st(r).kpi.find(x=>x.id===id).deleted);const backup=JSON.stringify({schemaVersion:413,records:[],kpi:st(r).kpi,sources:[]});const b=await runtime();try{await qc(b).importFiles([{name:'backup.json',arrayBuffer:async()=>Buffer.from(backup)}]);await qc(b).commit();assert.equal(st(b).kpi.length,54);assert(st(b).kpi.find(x=>x.id===id).deleted)}finally{b.close()}return 'restored 66 incl. deleted flag'}finally{r.close()}});
 await test('Real GS roundtrip: KPI rows travel in one month bucket (kpi_2026-09), second device receives 66 KPI + Final QC rows, unchanged re-sync transfers nothing',async()=>{const g=createGas(),a=await runtime(g),b=await runtime(g);try{await qc(a).importFiles([kpiFile(),daily()]);await qc(a).commit();const push=await qc(a).sync('push');assert(push.ok,JSON.stringify(push));const manifest=g.ctx.readSmartManifest_('qc');const buckets=Object.keys(manifest.buckets);assert(buckets.includes('p:kpi_2026-09'),buckets.join(','));assert.equal(manifest.buckets['p:kpi_2026-09'].count,54);const pull=await qc(b).sync('pull');assert(pull.ok);assert.equal(st(b).kpi.length,54);assert.equal(st(b).records.length,st(a).records.length);const again=await qc(b).sync('pull');assert.equal(again.downloaded||0,0);const p2=await qc(a).sync('push');assert.equal(p2.uploaded||0,0);return 'buckets '+buckets.length+' incl. p:kpi_2026-09 (54)'}finally{a.close();b.close()}});
 fs.writeFileSync(path.resolve(__dirname,'qc_kpi_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})();
