/* Spare parts cloud transport: request count before/after v4.13 bucketing, second-device roundtrip, no-change re-sync. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const UP='/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/',url='https://script.google.com/macros/s/MOCK_PROD/exec';
const file=(p,name)=>{const b=fs.readFileSync(p);return{name,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
async function runtime(root,gas){const {createRuntime}=require(root+'/qa/v39/runtime_harness');const r=createRuntime(root+'/vrt_spare_parts_v2.html');if(gas)r.ctx.fetch=gas.fetch;r.load();await new Promise(res=>setTimeout(res,150));await r.ctx.VRT_LOCAL_READY;if(gas){r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(root+'/vrt-smart-sync-v3.js','utf8'))}return r}
async function importBoth(r){for(const [f,n] of [[UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'],[UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx','Daily Spare Part Change Report.xlsx']]){await r.ctx.importExcel(file(f,n));await r.ctx.VRTParts39.commit()}}
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,e.message)}}
(async()=>{
 const NEW=path.resolve(__dirname,'../..'),OLD=path.resolve(__dirname,'../../../baseline/vrt-prod-main');
 const {createGas}=require(NEW+'/qa/v41/gas_harness');
 let oldBuckets=null;
 await test('BASELINE v4.8 transport: bucket count for the same two files (old parser reads them wrongly but still uploads)',async()=>{const g=createGas(),a=await runtime(OLD,g);try{await importBoth(a);const r=await a.ctx.cloudUpload(true);const posts=g.calls.filter(c=>c.p&&c.p.action==='smartBucket').length;const manifest=g.ctx.readSmartManifest_('spareparts');oldBuckets=Object.keys(manifest.buckets).length;return 'smartBucket POSTs '+posts+' · manifest buckets '+oldBuckets+' · uploaded '+r.uploaded}finally{a.close()}});
 await test('v4.13 transport: same data uploads in a few dozen month/week/hash buckets instead of one per row',async()=>{const g=createGas(),a=await runtime(NEW,g);try{await importBoth(a);const st=a.ctx.VRTParts39.getState();const r=await a.ctx.cloudUpload(true);assert(r&&r.ok,JSON.stringify(r));const posts=g.calls.filter(c=>c.p&&c.p.action==='smartBucket').length;const manifest=g.ctx.readSmartManifest_('spareparts'),keys=Object.keys(manifest.buckets);assert(keys.length<60,'too many buckets: '+keys.length);assert(keys.some(k=>/maint_needle_2026-09/.test(k))&&keys.some(k=>/maint_stock_2026-W3/.test(k)),keys.join(','));assert(oldBuckets==null||keys.length<oldBuckets/5,'expected ≥5× fewer buckets than baseline '+oldBuckets);return 'rows '+r.recordCount+' · smartBucket POSTs '+posts+' · manifest buckets '+keys.length+' (baseline '+oldBuckets+') · e.g. '+keys.filter(k=>/maint_/.test(k)).slice(0,4).join(', ')}finally{a.close()}});
 await test('Second device pull receives identical needle/part change rows and stock sheets; re-sync on both sides transfers nothing',async()=>{const g=createGas(),a=await runtime(NEW,g),b=await runtime(NEW,g);try{await importBoth(a);assert((await a.ctx.cloudUpload(true)).ok);const pull=await b.ctx.cloudDownload(true);assert(pull&&pull.ok,JSON.stringify(pull));const sa=a.ctx.VRTParts39.getState(),sb=b.ctx.VRTParts39.getState();const norm=m=>({n:m.needleChanges.map(x=>x.id).sort(),p:m.partChanges.map(x=>x.id).sort(),s:m.stockReports.map(x=>x.id+':'+x.fingerprint).sort(),d:m.sourceDocuments.map(x=>x.id).sort()});assert.strictEqual(JSON.stringify(norm(sb.maintenance)),JSON.stringify(norm(sa.maintenance)));const again=await b.ctx.cloudDownload(true);assert.equal(again.downloaded||0,0);const p2=await a.ctx.cloudUpload(true);assert.equal(p2.uploaded||0,0);return 'B has '+sb.maintenance.needleChanges.length+' needle + '+sb.maintenance.partChanges.length+' part changes, '+sb.maintenance.stockReports.length+' sheets; re-sync 0/0'}finally{a.close();b.close()}});
 await test('New daily import on device A after sync touches only the current month/week buckets',async()=>{const g=createGas(),a=await runtime(NEW,g);try{await importBoth(a);assert((await a.ctx.cloudUpload(true)).ok);const before=g.calls.length;a.ctx.VRTParts39.changeKind='needle';const M=a.ctx.VRTParts39.getState().maintenance;await a.ctx.VRTParts39.mergeImport({parts:[],txns:[],stockReports:[],needleChanges:[{id:'NC-test1',date:'2026-09-29',needleType:'DBX1',size:'90/14',line:'Line 2',qty:5,reason:'Broken',reasonClass:'broken',returned:null,remark:''}],partChanges:[],invoiceSummaries:[]});await a.ctx.saveAll(false);const r=await a.ctx.cloudUpload(true);const posts=g.calls.slice(before).filter(c=>c.p&&c.p.action==='smartBucket').map(c=>c.p.bucket);assert(r.ok&&r.uploaded>0);assert(posts.length<=3,'buckets touched: '+posts.join(','));return 'buckets touched: '+posts.join(', ')}finally{a.close()}});
 await test('Migration: cloud written by v4.8 (571 h: buckets) → v4.13 device pulls, re-imports newest files, pushes → manifest has only p: buckets, no data loss, third device matches',async()=>{const g=createGas(),a=await runtime(OLD,g);try{await importBoth(a);assert((await a.ctx.cloudUpload(true)).ok)}finally{a.close()}const b=await runtime(NEW,g);try{const pull=await b.ctx.cloudDownload(true);assert(pull&&pull.ok,JSON.stringify(pull).slice(0,200));const afterPull=b.ctx.VRTParts39.getState().maintenance;assert(afterPull.needleChanges.length>0);await importBoth(b);const push=await b.ctx.cloudUpload(true);if(push&&push.needsPull){await b.ctx.cloudDownload(true);const p2=await b.ctx.cloudUpload(true);assert(p2.ok,JSON.stringify(p2).slice(0,300))}else assert(push.ok,JSON.stringify(push).slice(0,300));const manifest=g.ctx.readSmartManifest_('spareparts'),keys=Object.keys(manifest.buckets);assert(!keys.some(k=>/^h:/.test(k)),'old per-row buckets remain: '+keys.filter(k=>/^h:/.test(k)).length);const sb=b.ctx.VRTParts39.getState().maintenance;const c=await runtime(NEW,g);try{assert((await c.ctx.cloudDownload(true)).ok);const sc=c.ctx.VRTParts39.getState().maintenance;assert.strictEqual(sc.needleChanges.length,sb.needleChanges.length);assert.strictEqual(sc.stockReports.length,sb.stockReports.length);return 'buckets after migration '+keys.length+' · needle '+sc.needleChanges.length+' · part '+sc.partChanges.length+' · sheets '+sc.stockReports.length}finally{c.close()}}finally{b.close()}});
 fs.writeFileSync(path.resolve(__dirname,'parts_cloud_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})();
