const RELEASE_ROOT=require('path').resolve(__dirname,'../..'),source=require('./inputs').source;const resultFile=name=>{const dir=require('path').join(__dirname,'results');require('fs').mkdirSync(dir,{recursive:true});return require('path').join(dir,name)};
const {createRuntime}=require('./runtime_harness');const fs=require('fs'),assert=require('assert');const rt=createRuntime(RELEASE_ROOT+'/vrt_spare_parts_v2.html'),out=[];const add=async(name,fn)=>{try{out.push({name,status:'PASS',detail:await fn()})}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.error(name,e.message)}};
(async()=>{try{rt.load();await new Promise(r=>setTimeout(r,80));const api=rt.ctx.VRTParts39;
await add('Spare parts startup restores required filter controls; all tabs render',async()=>{for(const id of ['fStore','fCat','fBrand','fSearch'])assert(rt.elements.has(id),id);for(const tab of ['dashboard','inventory','history','monthly','price','reports','machine','needle','needlechange']){rt.run(`goTab('${tab}')`);assert(rt.elements.get('app').innerHTML.length>100,tab)}return '9 render paths executed; simulated DOM (not layout)'});
const files=['VRT_YI_Spare_Parts_Price_Benchmark_Jan-Jun_2026_v2-1.xlsx','Sewing_Machine_Spareparts_Stock_Report_From_1_10_Of_September_2026 (2).xlsx','Needles Stock Report In July 2026.xlsx'];
async function importAll(){for(const name of files){await rt.ctx.importExcel({name,arrayBuffer:async()=>fs.readFileSync(source(name))});await api.commit()}}
await add('Real Excel preview > commit > IDB save > render',async()=>{await importAll();const d=api.getState();assert.equal(d.parts.length,86);assert.equal(d.txns.length,152);assert.equal(d.maintenance.stockReports.length,2);assert.equal(d.maintenance.sourceDocuments.length,3);assert.equal(d.maintenance.needleChanges.length,0);const db=await rt.ctx.VRTDomain39.readDomain('spareparts');assert.equal(db.txns.length,152);assert.equal(db.maintenance.stockReports[0].items.length,79);return '86 catalog / 152 transactions / 79 machine / 17 needle / 3 original files saved'});
await add('Repeat all three original files does not grow records or purchase totals',async()=>{const a=api.getState();await importAll();const b=api.getState();assert.equal(a.parts.length,b.parts.length);assert.equal(b.txns.length,152);assert.equal(b.txns.reduce((n,r)=>n+r.amount,0),14563.15);assert.equal(b.maintenance.stockReports.length,2);assert.equal(b.maintenance.editHistory.length,a.maintenance.editHistory.length);return 'no repeated stock or cost accumulation'});
await add('Stock and Needle Change online CRUD persists after reload',async()=>{api.editChange();const vals={date:'2026-09-13',needleType:'DBX1',size:'100/16',line:'9',machine:'SN-1',operator:'IE',reason:'Bent',qty:'2',returned:'2',remark:''};for(const [k,v]of Object.entries(vals))rt.elements.get('v39-'+k).value=v;await api.saveChange('');let d=api.getState();assert.equal(d.maintenance.needleChanges.length,1);const id=d.maintenance.needleChanges[0].id;api.editChange(id);rt.elements.get('v39-qty').value='3';await api.saveChange(id);assert.equal(api.getState().maintenance.needleChanges[0].qty,3);await rt.ctx.loadAll();assert.equal(api.getState().maintenance.needleChanges[0].qty,3);await api.deleteChange(id);assert.equal(api.getState().maintenance.needleChanges.length,0);assert(api.getState().maintenance.tombstones.some(x=>x.id===id));return 'Create 2 / Edit 3 / IDB reload / Delete tombstone; stock snapshot unchanged'});
await add('Excel exports include raw transactions and round-trip stock + needle schema',async()=>{let captured;rt.ctx.XLSX.writeFile=(wb)=>captured=wb;rt.ctx.exportExcel();assert(captured.Sheets['Inventory']);assert(captured.Sheets['Transaction Detail']);assert(captured.Sheets['Stock Snapshots']);assert(captured.Sheets['Needle Change']);const x=rt.ctx.VRTData39.parsePartsWorkbook(captured,'VRT_Maintenance.xlsx');assert.equal(x.parts.length,86);assert.equal(x.txns.length,152);assert.equal(x.stockReports.length,2);assert.equal(x.stockReports.find(r=>r.kind==='machine').items.length,79);return 'Inventory, transactions, both stock periods, Needle Change export schemas parse'});
}catch(e){out.push({name:'runtime startup',status:'FAIL',detail:e.stack});console.error(e.stack)}finally{rt.close();fs.writeFileSync(resultFile('maintenance_results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(out.some(x=>x.status==='FAIL'))process.exitCode=1}})();
