/* Deliberate DOM/IndexedDB simulation for executable logic checks. This is not a browser layout test. */
const fs=require('fs'),vm=require('vm'),path=require('path');
function createRuntime(htmlPath){
 const html=fs.readFileSync(htmlPath,'utf8'),elements=new Map(),dbs=new Map(),listeners={},timers=[];let suppress=false;
 function schedule(fn){const t=setTimeout(fn,0);timers.push(t);return t}
 class Element{constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.value='';this.dataset={};this.style={};this.children=[];this.options=[];this.events={};this.attributes={};this.classList={add(){},remove(){},toggle(){},contains(){return false}};this._html='';this.textContent='';this.contentWindow={postMessage(){},document:{}}}
  set innerHTML(t){this._html=String(t);parseElements(this._html);}
  get innerHTML(){return this._html} showModal(){this.open=true} close(){this.open=false}
  addEventListener(n,fn){(this.events[n]??=[]).push(fn)} appendChild(x){this.children.push(x);if(x.id)elements.set(x.id,x);return x} insertBefore(x){return this.appendChild(x)} remove(){} removeAttribute(k){delete this.attributes[k]} setAttribute(k,v){this.attributes[k]=String(v);if(k==='id'){this.id=v;elements.set(v,this)}} getAttribute(k){return this.attributes[k]??null} hasAttribute(k){return k in this.attributes} querySelector(s){const m=s.match(/^\[name=["'](.+?)["']\]$/);if(m){const v=this._html.match(new RegExp('<(input|select|textarea)\\b[^>]*name=["\\\']'+m[1]+'["\\\'][^>]*>([\\s\\S]*?)(?:<\\/\\1>|$)','i'));if(!v)return null;const el=new Element(v[1]);el.value=(v[0].match(/\bvalue=["']([^"']*)/)||[])[1]||'';if(v[1]==='select'){const opt=(v[2].match(/<option[^>]*selected[^>]*>/)||v[2].match(/<option[^>]*>/)||[])[0]||'';el.value=(opt.match(/value=["']([^"']*)/)||[])[1]||''}return el}return document.querySelector(s)} querySelectorAll(s){return document.querySelectorAll(s)} scrollIntoView(){} click(){} focus(){} getContext(){return {}} closest(){return null}}
 function parseElements(text){for(const m of text.matchAll(/<([a-z][\w-]*)\b([^>]*)>/gi)){const id=(m[2].match(/\bid=["']([^"']+)["']/)||[])[1];if(!id)continue;const x=new Element(m[1],id);for(const a of m[2].matchAll(/([\w-]+)=["']([^"']*)["']/g))x.attributes[a[1]]=a[2];x.value=x.attributes.value||'';const start=m.index+m[0].length,end=text.indexOf('</'+m[1]+'>',start);x._html=end>=0?text.slice(start,end):'';elements.set(id,x)}}
 parseElements(html);
 const document={head:new Element('head'),body:new Element('body'),documentElement:new Element('html'),readyState:'loading',getElementById:id=>elements.get(id)||null,createElement:t=>new Element(t),addEventListener(n,f){(listeners[n]??=[]).push(f)},querySelector(s){if(s[0]==='#')return elements.get(s.slice(1))||null;if(s==='.toolbar'||s==='.lang-group')return new Element();return null},querySelectorAll(s){if(s==='.import-card'){const m=(elements.get('modalRoot')?.innerHTML||'').split(/(?=<div class="import-card")/).filter(x=>x.startsWith('<div class="import-card'));return m.map(t=>{const e=new Element();e._html=t;return e})}return []}};
 const indexedDB={open(name,version){const q={};schedule(()=>{let db=dbs.get(name),upgrade=!db||version>db.version;if(db&&version&&version<db.version){q.error=new Error('VersionError');q.onerror?.();return}if(!db){db={name,version:version||1,stores:new Map()};dbs.set(name,db)}if(version)db.version=version;const d={get version(){return db.version},objectStoreNames:{contains:k=>db.stores.has(k),[Symbol.iterator]:function*(){yield*db.stores.keys()}},createObjectStore(k,opts){db.stores.set(k,{opts:opts||{},values:new Map(),seq:0});return {createIndex(){}}},close(){},transaction(names,mode){const tx={error:null,pending:0};const complete=()=>schedule(()=>{if(!tx.pending)tx.oncomplete?.()});tx.objectStore=k=>{const s=db.stores.get(k);if(!s)throw new Error('Missing store '+k);function req(fn){const r={};tx.pending++;schedule(()=>{try{r.result=fn();r.onsuccess?.({target:r})}catch(err){r.error=err;tx.error=err;r.onerror?.({target:r});tx.onerror?.()}finally{tx.pending--;complete()}});return r}return {put(row,key){return req(()=>{const x=structuredClone(row),kp=s.opts.keyPath;if(key===undefined){key=kp?x[kp]:undefined;if(key===undefined&&s.opts.autoIncrement)key=++s.seq;if(key===undefined)throw new Error('Missing IDB key');if(kp)x[kp]=key}s.values.set(key,x);return key})},add(row,key){return req(()=>{const x=structuredClone(row),kp=s.opts.keyPath;key=key??x[kp]??++s.seq;if(s.values.has(key))throw new Error('ConstraintError');if(kp)x[kp]=key;s.values.set(key,x);return key})},get(key){return req(()=>structuredClone(s.values.get(key)))},getAll(){return req(()=>structuredClone([...s.values.values()]))},delete(key){return req(()=>s.values.delete(key))},clear(){return req(()=>s.values.clear())}}};complete();return tx}};q.result=d;if(upgrade){q.transaction={abort(){}};q.onupgradeneeded?.({target:q})}q.onsuccess?.({target:q})});return q}};
 const storage=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}};
 const ctx={console,document,indexedDB,localStorage:storage(),sessionStorage:storage(),TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,Date,Blob,URL,URLSearchParams,Response,structuredClone,Map,Set,crypto:require('crypto').webcrypto,location:{href:'http://localhost/'+path.basename(htmlPath),pathname:'/'+path.basename(htmlPath),origin:'http://localhost',search:''},navigator:{onLine:false},CSS:{escape:x=>x},CustomEvent:class{constructor(type,opt){this.type=type;this.detail=opt?.detail}},fetch:async()=>{throw new Error('No live network in simulation')},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),setInterval:()=>0,clearInterval:()=>{},AbortController,setTimeout(fn,delay){if(delay>100)return 0;return schedule(fn)},clearTimeout,requestAnimationFrame:fn=>schedule(fn),confirm:()=>true,alert:()=>{},addEventListener(n,fn){(listeners['window:'+n]??=[]).push(fn)},dispatchEvent(){},scrollTo(){},open(){},postMessage(){},getComputedStyle(){return{getPropertyValue(){return '#fff'}}},Chart:class{destroy(){}},VRTProdAutoSync:{markDirty(){},install(){}},VRTSmartSync:{status(){}}};ctx.window=ctx;ctx.parent=ctx;for(const [id,elem] of elements)if(!(id in ctx))ctx[id]=elem;Object.defineProperty(ctx.document,'hidden',{value:false});vm.createContext(ctx);
 function run(code,filename){return vm.runInContext(code,ctx,{filename})}
 function load(){for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/type=["']application\/(?:ld\+)?json/.test(m[1]))continue;const src=(m[1].match(/\bsrc=["']([^"']+)/)||[])[1];if(src){if(/^https?:/.test(src)||/vrt-(smart|auto)-sync/.test(src))continue;run(fs.readFileSync(path.join(path.dirname(htmlPath),src.split('?')[0]),'utf8'),src)}else if(!/vrt-cloud-transport/.test(m[1]))run(m[2],'inline')}for(const fn of listeners.DOMContentLoaded||[])fn(); }
 return{ctx,document,elements,dbs,listeners,run,load,close(){timers.forEach(clearTimeout)}};
}
module.exports={createRuntime};
