/* v4.16 D1 — 生產日報: numbers computed by code (vrt-daily-report-v1.js), fixed bilingual layout, once per date, AI text checked
   number by number. Real data: sewing backup 2026-09-28 (5,009 rows), cutting backup 2026-09-30 (18,663 rows), plus the seeded mock
   GAS (orders / plan / spare parts / QC) for the page and the GAS job. No Google / Telegram / Claude network: UrlFetchApp is stubbed. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {runtime,jfile,ev,wait,ROOT,DL,seedAll}=require('../v414/seed_gas');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
require(ROOT+'/vrt-daily-report-v1.js');const R=globalThis.VRTDailyReport;require(ROOT+'/vrt-tg-summary-v1.js');const TGS=globalThis.VRTTgSummary;
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
const q=(r,code)=>JSON.parse(r.run('JSON.stringify('+code+')'));const workdays=(a,b)=>{let n=0;for(let d=a;d<=b;d=R.helpers.addDays(d,1))if(R.helpers.dowMon0(d)<6)n++;return n};
const SEW=JSON.parse(fs.readFileSync(DL+'sewing_backup_2026-09-28.json','utf8')).daily,CUT=JSON.parse(fs.readFileSync(DL+'cutting_backup_2026-09-30.json','utf8')).cutting;
/* synthetic full dataset for one day so every section of the report has data */
function synth(D){const prev=R.helpers.addDays(D,-1),lw=R.helpers.addDays(D,-7);const sew=[],cut=[],qc=[],needle=[],ship=[];
  const lines=['Line 1','Line 2','Line 3','Line 4'];const mk=(d,ln,p,pm,am,st)=>sew.push({date:d,section:'Garment',lineNo:ln,styleNo:st||'ST'+ln.slice(-1),pieces:p,workers:20,efficiency:Math.round(pm/am*100),producedMinutes:pm,attendedMinutes:am});
  lines.forEach((ln,i)=>{mk(D,ln,1000+i*100,(1000+i*100)*5,(i===3?12000:7000));mk(prev,ln,900+i*100,(900+i*100)*5,7000);mk(lw,ln,1200+i*100,(1200+i*100)*5,7000)});
  cut.push({date:D,section:'Garment',lineNo:'Table A',styleNo:'ST1',pieces:3000,src:'daily'},{date:D,section:'Garment',lineNo:'Weekly Report',styleNo:'ST1',pieces:99999,src:'ref'},{date:prev,section:'Garment',lineNo:'Table A',styleNo:'ST2',pieces:2500,src:'daily'});
  qc.push({date:D,line:'Line 1',reportKind:'daily',inspected:900,rejected:9,defects:[{name:'Skip stitch',qty:5},{name:'Dirty',qty:3},{name:'Broken',qty:1}]},{date:D,line:'Line 2',reportKind:'daily',inspected:900,rejected:9,defects:[{name:'Dirty',qty:9}]},{date:D,line:'Line 4',reportKind:'daily',inspected:800,rejected:96,defects:[{name:'Skip stitch',qty:60},{name:'Open seam',qty:36}]},{date:prev,line:'Line 1',reportKind:'daily',inspected:900,rejected:18,defects:[]});
  for(let k=1;k<=20;k++){const d=R.helpers.addDays(D,-k);needle.push({date:d,line:'Line 2',qty:1,reasonClass:'broken',needleType:'DB×1 14'},{date:d,line:'Line 1',qty:2,reasonClass:'changeover',needleType:'DB×1 14'})}
  needle.push({date:D,line:'Line 2',qty:6,reasonClass:'broken',needleType:'DB×1 14'},{date:D,line:'Line 1',qty:2,reasonClass:'changeover',needleType:'DB×1 11'});
  const ws=R.helpers.addDays(D,-R.helpers.dowMon0(D));ship.push({cust:'ACME',po:'PO-1',style:'ST1',orig:5000,shipped:5000,open:0,etd:ws,status:'shipped'},{cust:'ACME',po:'PO-2',style:'ST2',orig:3000,shipped:0,open:3000,etd:R.helpers.addDays(D,-1)<ws?ws:R.helpers.addDays(D,-1),status:'outstanding'},{cust:'BETA',po:'PO-3',style:'ST3',orig:2000,shipped:1000,open:1000,etd:R.helpers.addDays(ws,6),status:'outstanding'},{cust:'OLD',po:'PO-9',style:'ST9',orig:100,shipped:0,open:100,etd:'2020-01-01',status:'outstanding'});
  const styles=[{sk:'ST1',customer:'ACME',qty:10000,cutPcs:8000,sewPcs:6000,status:'sew'},{sk:'ST2',customer:'ACME',qty:5000,cutPcs:5000,sewPcs:5000,status:'done'},{sk:'ST3',customer:'BETA',qty:3000,cutPcs:1500,sewPcs:0,status:'cut'}];
  const custstats={snapshotDate:D,overall:{noFabric:1200,cuttingWip:3500},details:[{customer:'BETA',po:'PO-3',style:'ST3',noFabric:1200},{customer:'ACME',po:'PO-2',style:'ST2',noFabric:0}]};
  return {sewing:sew,cutting:cut,qc:{records:qc,kpi:[]},spareparts:{needle,part:[{date:D,line:'Line 3',qty:2,reasonClass:'damage',partType:'Looper'}]},shipping:ship,custstats,styles}}
(async()=>{
 await test('compute — real backups: sewing day = de-duplicated rows (norm > target > dpo), weighted efficiency formula, prev day / same weekday last week, cutting excludes ref rows',async()=>{
   const f=R.compute({sewing:SEW,cutting:CUT},{today:'2026-09-29'});assert.equal(f.date,'2026-09-28');
   const S=TGS.build('sewing',SEW,'day','2026-09-28').stats;assert.equal(f.sewing.pieces,S.pieces,'day pieces must equal the shared sewing builder');assert.equal(f.sewing.lines,S.lineCount);
   const P=TGS.build('sewing',SEW,'day',f.prevDay.date).stats;assert.equal(f.prevDay.pieces,P.pieces);assert.equal(f.lastWeek.date,'2026-09-21');
   const C=TGS.build('cutting',CUT,'day','2026-09-28').stats;assert.equal(f.cutting.pieces,C.pieces);
   // efficiency: Σ producedMinutes / Σ attendedMinutes when minutes exist, else worker-weighted; here the backup has no minutes → worker-weighted or null
   const dayRows=R.helpers.sewPick(SEW)['2026-09-28'];const att=dayRows.reduce((s,r)=>s+(Number(r.attendedMinutes)||0),0);if(att>0)assert.equal(Math.round(f.sewing.eff*10),Math.round(dayRows.reduce((s,r)=>s+(Number(r.producedMinutes)||0),0)/att*1000));
   assert.equal(f.wip.cutNotSewn,null,'no styles and no custstats → WIP left blank, never guessed');
   return 'D '+f.date+' pieces '+f.sewing.pieces+' (builder '+S.pieces+') · prev '+f.prevDay.date+' '+f.prevDay.pieces+' · cutting '+f.cutting.pieces+' · eff '+(f.sewing.eff==null?'—':f.sewing.eff.toFixed(1))}) ;
 await test('compute — synthetic full day: every number of the report is derived from the rows (checked by hand here) and the anomalies fire on the documented thresholds',async()=>{
   const D='2026-10-08';const d=synth(D);const f=R.compute(d,{date:D,today:'2026-10-09'});
   assert.equal(f.sewing.pieces,1000+1100+1200+1300);assert.equal(f.sewing.lines,4);const pm=(1000+1100+1200+1300)*5,am=7000*3+12000;assert.equal(Math.round(f.sewing.eff*100),Math.round(pm/am*10000));assert.equal(f.sewing.effBasis,'minutes');
   assert.equal(f.prevDay.pieces,900+1000+1100+1200);assert.equal(f.lastWeek.pieces,1200+1300+1400+1500);assert.equal(Math.round(f.compare.piecesVsPrev*10)/10,Math.round((4600/4200-1)*1000)/10);
   assert.equal(f.cutting.pieces,3000,'Weekly Report ref row must not count');assert.equal(f.cutting.prevPieces,2500);
   assert.equal(f.wip.cutNotSewn,2000+1500,'WIP = Σ (cut − sewn) over cut/sew styles (done styles excluded)');assert.equal(f.wip.basis,'styles');
   assert.equal(f.qc.inspected,2600);assert.equal(f.qc.rejected,114);assert.equal(Math.round(f.qc.rate*100),Math.round(114/2600*10000));assert.deepStrictEqual(f.qc.top.slice(0,3).map(x=>x.name),['Skip stitch','Open seam','Dirty']);assert.equal(f.qc.worstLines[0].line,'Line 4');assert.equal(Math.round(f.qc.prevRate*100),200);
   assert.equal(f.shipping.orig,10000);assert.equal(f.shipping.shipped,6000);assert.equal(f.shipping.open,4000);assert.equal(f.shipping.pct,60);assert.equal(f.shipping.overdueRows,1);assert.equal(f.shipping.overdue[0].po,'PO-2');
   assert.equal(f.fabric.noFabricPcs,1200);assert.equal(f.fabric.top[0].po,'PO-3');
   assert.equal(f.maint.needle.qty,8);assert.equal(f.maint.needle.unplanned,6);assert.equal(f.maint.needle.flag.length,1);assert.equal(f.maint.needle.flag[0].line,'Line 2');assert.equal(f.maint.part.qty,2);
   const kinds=f.anomalies.map(a=>a.kind);assert.deepStrictEqual(kinds,['ship','qc','needle','fabric'],'ranked: overdue shipping > QC line > needle > fabric (no line below 25% → no weak-line item)');assert(/Line 4/.test(f.anomalies[1].zh));assert.equal(f.anomalies[0].who.zh,'出貨／船務');
   assert.deepStrictEqual(f.rag,{capacity:'G',quality:'G',plan:null,shipping:'R',wip:'G'},JSON.stringify(f.rag));assert.equal(f.lines.find(x=>x.line==='Line 4').risk,'quality');assert(f.lines.every(x=>x.verdict==='ok'));
   return 'pieces 4600 · eff '+f.sewing.eff.toFixed(1)+'% · WIP 3500 · QC '+f.qc.rate.toFixed(2)+'% top '+f.qc.top.map(x=>x.name).join('/')+' · ship 60% overdue PO-2 · fabric 1200 · needle flag Line 2 · anomalies '+kinds.join(',')});
 await test('render — fixed bilingual layout (3 highlights, key-number table vs prev/last week, ≤3 issues with line/PO + who), about 250 Chinese characters; Telegram HTML escapes data; checkAiText accepts its own text and rejects changed numbers',async()=>{
   const D='2026-10-08';const f=R.compute(synth(D),{date:D,today:'2026-10-09'});const r=R.render(f);const t=r.text;
   assert(/^📰 VRT 生產日報 Daily Production Report · 2026-10-08（四 Thu）/.test(t));assert(/1️⃣ 今日重點 Highlights/.test(t)&&/2️⃣ 關鍵數字 Key numbers/.test(t)&&/3️⃣ 異常與建議 Issues & actions/.test(t));
   const hl=t.split('\n').filter(l=>/^• /.test(l));assert.equal(hl.length,3+Math.min(3,f.anomalies.length));const en=t.split('\n').filter(l=>/^  /.test(l));assert.equal(en.length,hl.length,'one English line per Chinese line');
   assert(/產量 Output: 4,600 pcs │ 4,200 \(\+9\.5%\) │ 5,400 \(−14\.8%\)/.test(t),t);assert(/退修率 Reject rate: 4\.38% \(114\/2,600\) │ 2\.00% \(\+2\.4 pt\)/.test(t),t);assert(/管理判定 Verdict: 產能 🟢 GREEN · 品質 🟢 GREEN · 排單 — · 出貨 🔴 RED · WIP 🟢 GREEN/.test(t),t);assert(/WIP 已裁未縫 Cut-not-sewn: 3,500 pcs/.test(t));assert(/出貨 Shipping（本週 week .*: 60% · 已出 shipped 6,000 \/ 計畫 plan 10,000 · 未出 open 4,000/.test(t));
   assert(/PO PO-2/.test(t)&&/→ 請 出貨／船務 處理/.test(t)&&/→ Shipping/.test(t));assert(r.zhChars<=300,'zh chars '+r.zhChars);
   assert(/<b>📰/.test(r.html)&&!/<script/.test(r.html));const h=R.render(R.compute(Object.assign(synth(D),{shipping:[{cust:'<b>X</b>',po:'P&1',style:'S',orig:10,shipped:0,open:10,etd:R.helpers.addDays(D,-1),status:'outstanding'}]}),{date:D,today:'2026-10-09'})).html;assert(/&lt;b&gt;X&lt;\/b&gt;/.test(h)&&/P&amp;1/.test(h),'html escaped');
   const ok=R.checkAiText(t,f);assert(ok.ok,'own text flagged: '+ok.bad.join(','));const bad=R.checkAiText(t.replace('4,600','4,650').replace('60%','61%'),f);assert(!bad.ok&&bad.bad.includes('4,650')&&bad.bad.includes('61'),JSON.stringify(bad));
   const p=R.aiPrompt(f);assert(/不能自己計算/.test(p.system)&&/never compute/.test(p.system)&&p.user.includes(t));
   const g=R.checkNumbersAgainstText('產出 4,600 pcs 效率 79%','產出 4,600 pcs 效率 78.5%');assert(!g.ok&&g.bad[0]==='79');
   assert(/先講管理判定與結論/.test(p.system),'style guide in the prompt');return 'zh '+r.zhChars+' chars · '+hl.length+' points · verdict line · html escaped · own text ok · altered numbers 4,650/61 rejected · prompt '+(p.system.length+p.user.length)+' chars'});
 await test('render — a date without data says so (no fake zeros as highlights); Word export is a self-contained HTML document with the numbers table',async()=>{
   const f=R.compute({sewing:[],cutting:[]},{date:'2026-10-05',today:'2026-10-09'});const r=R.render(f);assert(/沒有車縫／裁剪／QC 資料/.test(r.text));assert(!f.hasData);
   const D='2026-10-08';const f2=R.compute(synth(D),{date:D,today:'2026-10-09'});const doc=R.docHtml(f2,R.render(f2).text);assert(/<html/.test(doc)&&/WordDocument/.test(doc)&&/4,600/.test(doc)&&/<table/.test(doc)&&/生產日報 2026-10-08/.test(doc));return 'no-data message · doc '+doc.length+' chars'});
 await test('management-analysis layout — synthetic week with a dual-risk line and a month plan: RAG per area, line 判讀 (可接受/偏低/低效) + risk class (dual/quality/capacity), plan position (completion vs elapsed working days, required/day), per-day table, QC reconciliation, actions with owners, 資料口徑; Word doc carries KPI tiles, 管理結論, 9 sections and the action table',async()=>{
   const D='2026-10-08';const d=synth(D);
   // make Line 3 weak (eff ≈ 20%) with a high reject (dual risk) and give Line 3 a QC report; add a month plan
   d.sewing.forEach(r=>{if(r.lineNo==='Line 3'&&(r.date===D||r.date===R.helpers.addDays(D,-1))){r.attendedMinutes=30000}});d.qc.records.push({date:D,line:'Line 3',reportKind:'daily',inspected:500,rejected:70,defects:[{name:'Open seam',qty:70}]});
   d.prodplan=[{month:'2026-10',line:'L1',style:'ST1',sewingQty:60000},{month:'2026-10',line:'L2',style:'ST2',sewingQty:50000},{month:'2026-09',line:'L1',style:'OLD',sewingQty:99999}];
   const f=R.compute(d,{date:D,today:'2026-10-09',period:'week'});
   assert.equal(f.period,'week');assert.equal(f.date,'2026-W41');assert.equal(f.start,'2026-10-05');assert.equal(f.end,'2026-10-11');assert.equal(f.days.length,2,'two data days in the week (D and D-1)');assert.equal(f.sewing.pieces,4600+4200);assert.equal(f.sewing.dayCount,2);assert.equal(f.sewing.perDay,4400);
   assert.equal(f.prevDay.label,'前週 prev week 2026-W40');assert.equal(f.prevDay.pieces,5400,'previous week = the D-7 rows');
   const l3=f.lines.find(x=>x.line==='Line 3');assert(l3.eff<25&&l3.rejectRate>=10,JSON.stringify(l3));assert.equal(l3.verdict,'weak');assert.equal(l3.risk,'dual');assert.deepStrictEqual(f.riskLines.dual,['Line 3']);
   assert.equal(f.lines.find(x=>x.line==='Line 4').risk,'quality');
   assert.equal(f.plan.month,'2026-10');assert.equal(f.plan.planQty,110000,'only the 2026-10 plan rows');assert.equal(f.plan.mtd,4600+4200+5400,'month-to-date = all sewing days in October ≤ period end');assert.equal(f.plan.remaining,110000-14200);assert.equal(f.plan.totalWorkdays,27);assert.equal(f.plan.elapsedWorkdays,workdays('2026-10-01','2026-10-11'));assert.equal(f.plan.requiredPerDay,Math.round((110000-14200)/f.plan.workdaysLeft));
   assert.equal(f.rag.plan,f.plan.completion-f.plan.elapsedShare>=-5?'G':f.plan.completion-f.plan.elapsedShare>=-15?'A':'R');assert.equal(f.rag.quality,'A','reject '+f.qc.rate.toFixed(2)+'% → AMBER (5–10)');
   assert(f.qcReconcile&&f.qcReconcile.qcOutput===0||f.qcReconcile===null,'synthetic QC rows carry no output → no reconcile claim');
   const kinds=f.anomalies.map(a=>a.kind);assert(kinds.includes('dual')&&!kinds.includes('qc'),'dual-risk replaces the single QC item: '+kinds.join(','));assert(f.actions.some(a=>/雙重風險/.test(a.item)&&/IE/.test(a.owner)),JSON.stringify(f.actions));assert(f.actions.length<=8);
   assert(/管理判定：產能/.test(f.conclusion.zh)&&/Management verdict: capacity/.test(f.conclusion.en));assert(/雙重風險線（低效＋高退修）：Line 3/.test(f.conclusion.zh));assert(f.basis.zh.length===6&&f.basis.en.length===6);assert(/≥35% GREEN/.test(f.basis.zh[1]));
   const r=R.render(f);assert(/生產週報 Weekly Production Report · 2026-W41（10\/05–10\/11）/.test(r.text));assert(/日均 Daily avg: 4,400 pcs \(2 天 days\)/.test(r.text));assert(/日別 By day: 10\/07 4,200 \(\d+%\) · 10\/08 4,600 \(\d+%\)/.test(r.text),r.text);assert(/線別風險 Line risks: .*Line 3 \d+%\/\d+% 雙重 dual/.test(r.text),r.text);assert(r.zhChars<=450,'zh '+r.zhChars);assert(R.checkAiText(r.text,f).ok,JSON.stringify(R.checkAiText(r.text,f)));
   const doc=R.docHtml(f,r.text);for(const must of ['生產產能、計劃執行與品質關聯週報','Weekly Production Capacity, Plan Execution & Quality Correlation Report','管理結論 Management Conclusion','一、本週每日產能 | 1. Daily Capacity','二、生產計劃 vs 實績 | 2. Production Plan vs Actual','三、各組產能與品質','四、品質','五、出貨排程','六、WIP 與物料','七、換針與零件','八、管理結論與行動','九、資料口徑與分析限制','雙重風險 / Dual risk','AMBER','Required action','Appendix: Telegram summary'])assert(doc.includes(must),'doc missing: '+must);
   assert((doc.match(/<table/g)||[]).length>=10,'tables');assert(!/<script/.test(doc));
   return 'W41 · 2 days 8,800 pcs · Line 3 dual (eff '+l3.eff.toFixed(0)+'% / rej '+l3.rejectRate.toFixed(0)+'%) · plan 14,200/110,000 req '+f.plan.requiredPerDay+'/day RAG '+f.rag.plan+' · '+f.actions.length+' actions · doc '+doc.length+' chars, '+(doc.match(/<table/g)||[]).length+' tables'});
 await test('week report on the real backups: Mon–Sun window, previous week comparison, cutting per period, no plan/QC data → RAG — and plain statements, Telegram text under the limit',async()=>{
   const f=R.compute({sewing:SEW,cutting:CUT},{date:'2026-09-25',today:'2026-09-29',period:'week'});assert.equal(f.date,'2026-W39');assert.equal(f.start,'2026-09-21');assert.equal(f.end,'2026-09-27');
   const exp=TGS.build('sewing',SEW,'week','2026-09-25').stats;assert.equal(f.sewing.pieces,exp.pieces,'week pieces = shared builder');assert.equal(f.days.length,exp.dayCount);
   const prevExp=TGS.build('sewing',SEW,'week','2026-09-18').stats;assert.equal(f.prevDay.pieces,prevExp.pieces);const cutExp=TGS.build('cutting',CUT,'week','2026-09-25').stats;assert.equal(f.cutting.pieces,cutExp.pieces);
   assert.equal(f.plan,null);assert.equal(f.rag.plan,null);assert.equal(f.qc.rate,null);assert(f.actions.some(a=>/排單資料/.test(a.item)));const r=R.render(f);assert(r.text.length<4000);assert(/管理判定 Verdict: 產能 .* · 品質 — · 排單 — · 出貨 — · WIP —/.test(r.text));
   return 'W39 '+f.sewing.pieces+' pcs over '+f.days.length+' days (prev W38 '+f.prevDay.pieces+') · cutting '+f.cutting.pieces+' · text '+r.text.length+' chars'});
 /* ── page: production_v4 「📰 生產日報」 with the seeded mock cloud ── */
 const g=createGas();const seeded=await seedAll(g);
 await test('page — production_v4 pulls the cloud, auto-generates the latest day once (not sent), WIP equals the page KPI data (STYLES), sewing day total equals the sewing builder; regenerate overwrites; stored in its own DB; cloud copy saved',async()=>{
   const o=await runtime('production_v4.html',g);try{await o.ctx.vcPullAll();await wait(1500);const n=q(o,'[SEW.length,CUT.length,STYLES.length]');assert(n[0]>1000&&n[1]>1000&&n[2]>0,'page data '+n);
     await wait(1200); // hideL → drAutoGenerate
     const idx=[...(o.dbs.get('VRT_DailyReport')?.stores.get('reports')?.values.values()||[])];assert.equal(idx.length,1,'auto-generated exactly one report');const rep=idx[0];assert.equal(rep.source,'page');assert(!rep.sentAt);
     const dates=q(o,'Object.keys(VRTDailyReport.helpers.sewPick(SEW)).filter(d=>d<=TODAY).sort()');assert.equal(rep.date,dates[dates.length-1]);
     const wipPage=q(o,'STYLES.filter(s=>s.status==="cut"||s.status==="sew").reduce((s,x)=>s+Math.max(0,x.cutPcs-x.sewPcs),0)');assert.equal(rep.facts.wip.cutNotSewn,wipPage,'WIP must equal the page styles');
     const dayPieces=TGS.build('sewing',q(o,'SEW'),'day',rep.date).stats.pieces;assert.equal(rep.facts.sewing.pieces,dayPieces);
     const again=await o.ctx.drGenerate(rep.date,{});assert.equal(again.generatedAt,rep.generatedAt,'second generate without force must return the stored one');
     const forced=await o.ctx.drGenerate(rep.date,{force:true});assert.notEqual(forced.generatedAt,rep.generatedAt);await wait(300);
     const wk=await o.ctx.drGenerate('',{period:'week'});assert(/-W\d{2}$/.test(wk.date),'week key '+wk.date);assert.equal(wk.facts.period,'week');assert.equal(wk.facts.plan,null,'no Production Plan in this runtime\'s IndexedDB → plan position stays blank (the browser check covers the real plan)');const stored=[...(o.dbs.get('VRT_DailyReport').stores.get('reports').values.values())].map(x=>x.date);assert(stored.includes(wk.date)&&stored.includes(rep.date));
     const cloud=g.raw('daily_report_'+rep.date+'.json');assert(cloud,'cloud copy');const cj=JSON.parse(cloud.content);assert.equal(cj.date,rep.date);
     const txt=q(o,'document.getElementById("drText").innerHTML');assert(/生產(日|週)報/.test(txt),txt.slice(0,80));
     return 'auto date '+rep.date+' · pieces '+rep.facts.sewing.pieces+' · WIP '+rep.facts.wip.cutNotSewn+' = page · once per date · week '+wk.date+' · cloud daily_report_'+rep.date+'.json'}finally{o.close()}});
 await test('page — ✈️ Telegram uses the shared sendMessage proxy (HTML, audit daily_report) and records sentAt; AI button without CLAUDE_API_KEY reports "not configured" and keeps the rule text',async()=>{
   const o=await runtime('production_v4.html',g);try{await o.ctx.vcPullAll();await wait(1500);await wait(1200);const rep=[...(o.dbs.get('VRT_DailyReport').stores.get('reports').values.values())][0];await o.ctx.drShow(rep.date);
     const sent=[];g.ctx.UrlFetchApp={fetch(url,opt){const m=String(url).match(/\/bot[^/]+\/(\w+)/);let payload={};try{payload=JSON.parse(opt.payload)}catch(_){}sent.push({method:m?m[1]:url,payload});return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:{message_id:77}})}}};
     o.ctx.VRTDialog.confirm=async()=>true;await o.ctx.drSend();await wait(300);assert.equal(sent.length,1);assert.equal(sent[0].payload.parse_mode,'HTML');assert(/生產日報/.test(sent[0].payload.text));const after=[...(o.dbs.get('VRT_DailyReport').stores.get('reports').values.values())][0];assert(after.sentAt,'sentAt');
     const c0=g.calls.length;await o.ctx.drAi();await wait(200);const aiCall=g.calls.slice(c0).find(c=>c.p.action==='dailyReportAi');assert(aiCall&&aiCall.response.data.notConfigured,'notConfigured expected');const st=q(o,'document.getElementById("drStatus").textContent');assert(/CLAUDE_API_KEY/.test(st),st);
     return 'sent 1 HTML message (audit daily_report) · sentAt recorded · AI: '+st.slice(0,40)}finally{o.close()}});
 /* ── GAS job ── */
 await test('GAS — generateDailyReport reads the cloud buckets, saves daily_report_<date>.json + index, trigger is idempotent (second run: no new file, no second send), dailyReportList/Get answer; AI step: fake key + stubbed Claude → text with a wrong number is rejected, correct text accepted and cost logged',async()=>{
   const sent=[];let claudeReply=null;g.ctx.UrlFetchApp={fetch(url,opt){const u=String(url);if(/api\.telegram\.org/.test(u)){let p={};try{p=JSON.parse(opt.payload)}catch(_){}sent.push(p);return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:{message_id:sent.length}})}}
       if(/api\.anthropic\.com\/v1\/models/.test(u))return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({data:[{id:'claude-haiku-x'},{id:'claude-sonnet-x'}]})};
       if(/api\.anthropic\.com\/v1\/messages/.test(u)){const body=JSON.parse(opt.payload);assert.equal(opt.headers['x-api-key'],'sk-test');assert(/不能自己計算/.test(body.system));return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({content:[{type:'text',text:claudeReply(body)}],usage:{input_tokens:2400,output_tokens:500}})}}
       throw new Error('unexpected url '+u)}};
   g.ctx.ScriptApp={getService:()=>({getUrl:()=>'https://script.google.com/macros/s/MOCK_PROD/exec'}),getProjectTriggers:()=>[],newTrigger:()=>({timeBased:()=>({atHour:()=>({everyDays:()=>({inTimezone:()=>({create(){}})})})})})};
   // the page already generated + sent the latest day → the trigger must reuse it (shared once-per-date store) and not send again
   const t0=g.ctx.dailyReportTrigger();assert.equal(t0.source,'page');assert(t0.sentAt);assert.equal(sent.length,0,'trigger must not resend a report the page already sent');
   // an earlier data date (no report yet) → GAS computes from the cloud buckets, saves and sends once
   const rep=g.ctx.generateDailyReport('2026-09-25',{send:true});assert(rep&&rep.date==='2026-09-25','report');assert.equal(rep.source,'gas');assert(rep.sentAt,'sent by trigger');assert.equal(sent.length,1);assert(/生產日報/.test(sent[0].text));assert.equal(rep.facts.sewing.pieces,TGS.build('sewing',SEW,'day','2026-09-25').stats.pieces,'GAS numbers = same builder on the same rows');
   const files=g.files.filter(f=>!f.trashed&&/^daily_report_/.test(f.name)).map(f=>f.name);assert(files.includes('daily_report_'+rep.date+'.json')&&files.includes('daily_report_index.json'));
   const rep2=g.ctx.generateDailyReport('2026-09-25',{send:true});assert.equal(rep2.generatedAt,rep.generatedAt,'idempotent');assert.equal(sent.length,1,'no second send');
   const wk=g.ctx.generateDailyReport('2026-09-25',{period:'week',send:true});assert.equal(wk.date,'2026-W39');assert.equal(wk.period,'week');assert.equal(sent.length,2);assert(/生產週報/.test(sent[1].text));assert(g.raw('daily_report_2026-W39.json'),'week file');assert(wk.doc&&/Weekly Production Capacity/.test(wk.doc),'doc html stored with the GAS report');assert(wk.facts.plan&&wk.facts.plan.planQty>0,'prodplan buckets read for the plan position');const wk2=g.ctx.generateDailyReport('2026-09-25',{period:'week',send:true});assert.equal(wk2.generatedAt,wk.generatedAt);assert.equal(sent.length,2);
   const U=r=>r.data;const list=U(g.post({action:'dailyReportList'}));assert(list.ok&&list.index.some(x=>x.date===rep.date)&&list.index.some(x=>x.date===t0.date));const get=U(g.post({action:'dailyReportGet',date:rep.date}));assert(get.ok&&get.report.facts.sewing.pieces===rep.facts.sewing.pieces);
   assert.equal(rep.facts.wip.basis,rep.facts.wip.cutNotSewn==null?'none':'custstats','GAS WIP comes from the customer statistics snapshot, never from raw history');
   // AI
   const noKey=U(g.post({action:'dailyReportAi',date:rep.date}));assert(noKey.notConfigured);
   g.props.set('CLAUDE_API_KEY','sk-test');claudeReply=b=>b.messages[0].content.match(/【規則版日報[^\n]*\n([\s\S]*?)\n\n【要求/)[1].replace(/(產量 Output: )[\d,]+/,'$19,999');
   const bad=U(g.post({action:'dailyReportAi',date:rep.date}));assert.equal(bad.ok,false);assert(bad.ai&&bad.ai.badNumbers.length,'wrong number must be flagged: '+JSON.stringify(bad.ai&&bad.ai.badNumbers));
   claudeReply=b=>b.messages[0].content.match(/【規則版日報[^\n]*\n([\s\S]*?)\n\n【要求/)[1];const good=U(g.post({action:'dailyReportAi',date:rep.date}));assert(good.ok&&good.ai.ok&&good.ai.model==='claude-sonnet-x','model auto-picked from /v1/models');assert.equal(good.ai.usage.inTokens,2400);assert.equal(Math.round(good.ai.costUsd*1e4)/1e4,Math.round((2400*2+500*10)/1e6*1e4)/1e4);
   const usage=U(g.post({action:'dailyReportUsage'}));assert.equal(usage.usage.thisMonth.calls,2);assert.equal(g.props.get('CLAUDE_MODEL'),'claude-sonnet-x');
   const saved=JSON.parse(g.raw('daily_report_'+rep.date+'.json').content);assert(saved.ai&&saved.ai.ok,'AI text stored with the report');
   // D2 per-module summary: numbers must come from the given text
   claudeReply=b=>'• 產出 '+(b.messages[0].content.match(/產出 Output: <?b?>?([\d,]+)/)||[])[1]+' pcs 很好\n  Output ok';const sum=U(g.post({action:'aiSummary',kind:'sewing',text:'產出 Output: <b>1,234</b> pcs',period:'day'}));assert(sum.ok&&sum.ai.ok,JSON.stringify(sum).slice(0,200));
   claudeReply=b=>'• 產出 1,300 pcs';const sum2=U(g.post({action:'aiSummary',kind:'sewing',text:'產出 Output: <b>1,234</b> pcs',period:'day'}));assert.equal(sum2.ok,false);
   return 'trigger reused page report '+t0.date+' (no resend) · GAS '+rep.date+' saved+sent once · week '+wk.date+' saved+sent once (plan '+wk.facts.plan.planQty+') · list/get ok · WIP basis '+rep.facts.wip.basis+' · AI: no key → notConfigured, wrong number rejected ('+bad.ai.badNumbers.join(',')+'), good text accepted $'+good.ai.costUsd+' · usage 2 calls · D2 check ok'});
 const pass=out.filter(x=>x.status==='PASS').length;console.log(pass+'/'+out.length+' PASS');fs.writeFileSync(path.resolve(__dirname,'daily_report_results.json'),JSON.stringify(out,null,1));process.exit(pass===out.length?0:1);
})().catch(e=>{console.error(e);process.exit(1)});
