/* v4.16 C — Telegram group files → PROD_Inbox / import_queue (GAS, polling kept) → 「☁ 待匯入」 on the pages (vrt-inbox-v1.js).
   Telegram and Drive are stubbed; the file that "arrives in the group" is the real weekly order report from Downloads. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {runtime,wait,ROOT}=require('../v414/seed_gas');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
const SAMPLES=process.env.VRT_SAMPLES||path.resolve(ROOT,'../samples')+'/';const WEEKLY=SAMPLES+'VRT Weekly Open Order Summary as of February-16-2026.xlsx';
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
const q=(r,code)=>JSON.parse(r.run('JSON.stringify('+code+')'));const U=r=>r.data;
/* Telegram stub: getUpdates feed, getFile, file download, reactions, sendMessage — everything recorded */
function stubTelegram(g,files){const api=[];let updates=[];g.ctx.UrlFetchApp={fetch(url,o){const u=String(url);let payload={};try{payload=o&&o.payload?JSON.parse(o.payload):{}}catch(_){}
    const m=u.match(/\/bot[^/]+\/(\w+)/);const method=m?m[1]:'';api.push({method,url:u.replace(/bot[^/]+/,'bot***'),payload});
    const ok=r=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:r}),getBlob:()=>{throw new Error('no blob')}});
    if(/\/file\/bot/.test(u)){const p=u.split('/file/bot')[1].split('/').slice(1).join('/');const f=files[p];if(!f)return {getResponseCode:()=>404,getContentText:()=>'not found',getBlob:()=>null};return {getResponseCode:()=>200,getContentText:()=>'',getBlob:()=>g.ctx.Utilities.newBlob(f.bytes,f.mime,'x')}}
    if(method==='getUpdates'){const r=updates;updates=[];return ok(r)}
    if(method==='getFile'){const f=Object.entries(files).find(([p,f])=>f.file_id===payload.file_id);if(!f)return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:false,description:'file not found'})};return ok({file_id:payload.file_id,file_path:f[0],file_size:f[1].bytes.length})}
    if(method==='setMessageReaction')return ok(true);if(method==='sendMessage')return ok({message_id:api.length});if(method==='getMe')return ok({username:'vrt_prod_bot'});if(method==='getChat')return ok({title:'VRT Malen'});return ok({})}};
  return {api,push:u=>updates.push(u)}}
const doc=(id,name,size,unique)=>({message_id:id,date:Math.floor(Date.now()/1000),chat:{id:-1001234,title:'VRT Malen',type:'supergroup'},from:{first_name:'Malen',last_name:'K'},document:{file_id:'fid_'+id,file_unique_id:unique||'uq_'+id,file_name:name,file_size:size,mime_type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});
(async()=>{
 assert(fs.existsSync(WEEKLY),'missing sample '+WEEKLY);const bytes=fs.readFileSync(WEEKLY);
 const g=createGas();const X='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';const T=stubTelegram(g,{'documents/file_1.xlsx':{file_id:'fid_1',bytes,mime:X},'documents/file_4.xlsx':{file_id:'fid_4',bytes:Buffer.from('x'),mime:'text/plain'},'documents/file_6.xlsx':{file_id:'fid_6',bytes,mime:X},'documents/file_7.xlsx':{file_id:'fid_7',bytes,mime:X},'documents/file_8.xlsx':{file_id:'fid_8',bytes,mime:X}});
 g.ctx.ScriptApp={getService:()=>({getUrl:()=>'https://script.google.com/macros/s/MOCK_PROD/exec'}),getProjectTriggers:()=>[]};
 await test('GAS pollTelegram: a weekly order file posted in the group is downloaded (getFile → file URL), stored in Drive PROD_Inbox/<group>/<date>/, queued as pending for orders_v3, mirrored to the import_queue sheet, 👍 reaction sent; same file again = ignored; 25 MB file = skipped with note; unknown name = unrouted; text commands still answered',async()=>{
   T.push({update_id:900,message:doc(1,'VRT Weekly Open Order Summary as of February-16-2026.xlsx',bytes.length)});
   T.push({update_id:901,message:doc(2,'VRT Weekly Open Order Summary as of February-16-2026.xlsx',bytes.length,'uq_1')});   // duplicate (same file_unique_id)
   T.push({update_id:902,message:doc(3,'Jan_25Dec_25_Monthly_Statement.pdf',25*1024*1024)});
   T.push({update_id:903,message:doc(4,'random_notes.xlsx',1)});
   T.push({update_id:904,message:{message_id:5,date:1,chat:{id:-1001234,title:'VRT Malen'},from:{first_name:'Paul'},text:'/prod@vrt_prod_bot'}});
   g.ctx.pollTelegram();
   const qf=g.raw('inbox_queue.json');assert(qf,'inbox_queue.json');const queue=JSON.parse(qf.content);assert.equal(queue.length,3,'rows '+queue.length);
   const a=queue[0];assert.equal(a.module,'orders');assert.equal(a.page,'orders_v3.html');assert.equal(a.status,'pending');assert(a.driveId,'driveId');assert.equal(a.group,'VRT Malen');assert.equal(a.sender,'Malen K');assert.equal(a.fileUniqueId,'uq_1');
   const stored=g.files.find(f=>f.id===a.driveId);assert(stored&&stored.bytes&&stored.bytes.length===bytes.length,'stored bytes');
   const folders=g.events.filter(e=>e.op==='create-folder').map(e=>e.name);assert(folders.includes('PROD_Inbox')&&folders.includes('VRT Malen')&&folders.some(n=>/^\d{4}-\d{2}-\d{2}$/.test(n)),'folders '+folders.join(','));
   const big=queue[1];assert.equal(big.status,'skipped');assert(/20 MB/.test(big.note));assert.equal(big.module,'spareparts','statement → 機修零件（對帳單）');
   const un=queue[2];assert.equal(un.module,'unrouted');assert.equal(un.status,'pending');
   const sheet=g.sheets.get('import_queue');assert(sheet&&sheet.rows.length===4,'sheet rows '+(sheet&&sheet.rows.length));assert.equal(sheet.rows[1][4],a.fileName);assert.equal(sheet.rows[1][7],'orders');
   const reactions=T.api.filter(x=>x.method==='setMessageReaction');assert.equal(reactions.length,2,'reactions for the two pending files');assert.equal(reactions[0].payload.reaction[0].emoji,'👍');
   const menu=T.api.filter(x=>x.method==='sendMessage'&&x.payload.reply_markup);assert(menu.length>=1,'/prod menu still answered');assert.equal(g.props.get('tg_offset'),'905');
   return 'queue 3 (orders pending · statement skipped 20 MB · unrouted) · Drive '+folders.filter((v,i,a)=>a.indexOf(v)===i).join('/')+' · sheet 3 rows · 👍 ×2 · /prod ok · offset 905'});
 await test('GAS web actions: inboxList by module (counts), inboxFile returns the exact bytes (base64), inboxDone updates queue + sheet, reroute an unrouted file, inboxRoutes lists the table (+ INBOX_ROUTES_JSON extension)',async()=>{
   const list=U(g.post({action:'inboxList',module:'orders',includeUnrouted:true}));assert(list.ok);assert.equal(list.rows.length,2,'orders + unrouted');assert.equal(list.counts.orders,1);assert.equal(list.counts.unrouted,1);
   const id=list.rows.find(r=>r.module==='orders').id;const f=U(g.post({action:'inboxFile',id}));assert(f.ok);assert.equal(Buffer.from(f.base64,'base64').length,bytes.length);assert(Buffer.from(f.base64,'base64').equals(bytes),'bytes differ');assert.equal(f.fileName,'VRT Weekly Open Order Summary as of February-16-2026.xlsx');
   const d=U(g.post({action:'inboxDone',id,status:'done',by:'paul',note:'ok'}));assert(d.ok&&d.row.status==='done'&&d.row.doneBy==='paul');const sheet=g.sheets.get('import_queue');assert.equal(sheet.rows[1][9],'done');assert.equal(sheet.rows[1][11],'paul');
   const un=list.rows.find(r=>r.module==='unrouted');const rr=U(g.post({action:'inboxDone',id:un.id,status:'pending',module:'custstats',by:'paul'}));assert(rr.ok&&rr.row.module==='custstats'&&rr.row.page==='vrt_customer_statistics_control_center_v1.html');
   const after=U(g.post({action:'inboxList',module:'orders'}));assert.equal(after.rows.length,0);assert.equal(U(g.post({action:'inboxList',module:'custstats'})).rows.length,1);
   g.props.set('INBOX_ROUTES_JSON',JSON.stringify([{re:'^MY SPECIAL',module:'fg',zh:'自訂'}]));/* names are matched with _ and - turned into spaces */const routes=U(g.post({action:'inboxRoutes'}));assert(routes.routes[0].custom&&routes.routes[0].module==='fg');assert(routes.routes.length>15);assert.equal(g.ctx.inboxRoute_('MY-SPECIAL-list.xlsx').module,'fg');assert.equal(g.ctx.inboxRoute_('Daily Needle Change Report 24 to 28 Sept.xlsx').module,'spareparts');assert.equal(g.ctx.inboxRoute_('1-VRT MONTHLY SHIPPING SCHEDULE.xlsx').module,'monthship');assert.equal(g.ctx.inboxRoute_('VRT - ALL CUSTOMER STATISTICS REPORT.xlsx').module,'custstats');assert.equal(g.ctx.inboxRoute_('greige inventory 2026-10.xlsx').module,'fabricdelivery');assert.equal(g.ctx.inboxRoute_('Final Qc Inspection Report 09-Oct.xls').module,'qc');g.props.delete('INBOX_ROUTES_JSON');
   return 'list/counts ok · bytes identical · done → sheet updated · unrouted → custstats · routes '+routes.routes.length+' (custom first)'});
 await test('page orders_v3: 「☁ 待匯入」 shows the file routed to it, Import downloads it and runs the page\'s own importer (weekly rows appear), then marks it done in the queue',async()=>{
   T.push({update_id:905,message:doc(6,'VRT Weekly Open Order Summary as of February-16-2026.xlsx',bytes.length,'uq_6')});g.ctx.pollTelegram();
   const a=await runtime('orders_v3.html',g);try{a.run("window.File=class File extends Blob{constructor(parts,name,opts){super(parts,opts);this.name=name;this.lastModified=(opts&&opts.lastModified)||Date.now()}}");a.run('delete window.VRTInbox');a.run(fs.readFileSync(ROOT+'/vrt-inbox-v1.js','utf8'));a.ctx.VRTInbox.init({module:'orders',feed:f=>a.ctx.importQueue([f]),autoDone:true});await wait(400);
     const rows=a.ctx.VRTInbox.rows;assert.equal(rows.length,1,'rows '+rows.length);assert.equal(q(a,'document.getElementById("vrtInboxN").textContent'),'1','badge');
     const n0=q(a,'APP.weekly.length');await a.ctx.VRTInbox.importRow(rows[0].id);await wait(600);const n1=q(a,'APP.weekly.length');assert(n1>n0,'weekly rows '+n0+' → '+n1);
     const done=U(g.post({action:'inboxList',module:'orders',status:'all'})).rows.find(r=>r.fileUniqueId==='uq_6');assert.equal(done.status,'done');assert.equal(a.ctx.VRTInbox.rows.length,0);
     return 'badge 1 → import → weekly rows '+n0+' → '+n1+' · queue row done · badge 0'}finally{a.close()}});
 await test('auto-import: with the per-page switch on, a file whose importer asks a question stays pending with the question as note; a file that imports without questions is marked done by "auto"',async()=>{
   T.push({update_id:906,message:doc(7,'VRT Weekly Open Order Summary as of June-15-2026.xlsx',bytes.length,'uq_7')});T.push({update_id:907,message:doc(8,'VRT Weekly Open Order Summary as of September-07-2026.xlsx',bytes.length,'uq_8')});g.ctx.pollTelegram();
   const a=await runtime('orders_v3.html',g);try{a.run("window.File=class File extends Blob{constructor(parts,name,opts){super(parts,opts);this.name=name}}");a.run('delete window.VRTInbox');a.run(fs.readFileSync(ROOT+'/vrt-inbox-v1.js','utf8'));a.ctx.localStorage.setItem('vrt:inbox:auto:orders','1');
     let n=0;a.ctx.VRTInbox.init({module:'orders',feed:async f=>{n++;if(/June/.test(f.name)){const ok=await a.ctx.VRTDialog.confirm('這份週報比現有的舊，仍要匯入？');return ok}return true}});await wait(900);
     const all=U(g.post({action:'inboxList',module:'orders',status:'all'})).rows;const j=all.find(r=>r.fileUniqueId==='uq_7'),s=all.find(r=>r.fileUniqueId==='uq_8');assert.equal(n,2,'feed calls '+n);
     assert.equal(j.status,'pending');assert(/需人工確認/.test(j.note),j.note);assert.equal(s.status,'done');assert.equal(s.doneBy,'auto');return 'June (asked) → pending "'+j.note.slice(0,30)+'…" · September → done by auto'}finally{a.close()}});
 await test('multi-bot intake (GA Purchase Order bot already in the production groups): inboxPollBots polls each extra bot with ITS token, downloads with that token, ignores non-document updates, skips documents older than INBOX_MAX_AGE_DAYS, keeps a per-bot offset; a bot that has a webhook (owned by another system) is skipped without deleteWebhook; PROD bot untouched; underscore file names routed',async()=>{
   const g2=createGas();g2.ctx.ScriptApp={getService:()=>({getUrl:()=>'x'}),getProjectTriggers:()=>[]};const calls=[];const updB=[{update_id:10,message:doc(21,'Daily_Spare_Part_Change_Report.xlsx',bytes.length,'uqB1')},{update_id:11,message:{message_id:22,date:Math.floor(Date.now()/1000),chat:{id:-9,title:'VRT - IE Management'},from:{first_name:'KIM'},text:'Hello Sir'}},{update_id:12,message:Object.assign(doc(23,'VRT_IE_Weekly_SMV_Update_Report_CN_EN_Approved_20260930.xlsx',bytes.length,'uqB2'),{chat:{id:-9,title:'VRT - IE Management'}})},{update_id:13,message:Object.assign(doc(24,'Pending - OBD-4559V.xls',bytes.length,'uqB3'),{date:Math.floor(Date.now()/1000)-10*86400})}];
   g2.ctx.UrlFetchApp={fetch(url,o){const u=String(url);const tok=(u.match(/\/bot([^/]+)\//)||[])[1];const m=u.match(/\/bot[^/]+\/(\w+)/);const method=m?m[1]:'';let payload={};try{payload=o&&o.payload?JSON.parse(o.payload):{}}catch(_){}calls.push({tok,method,payload});const ok=r=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:r})});
     if(/\/file\/bot/.test(u))return {getResponseCode:()=>200,getContentText:()=>'',getBlob:()=>g2.ctx.Utilities.newBlob(bytes,'application/octet-stream','x')};
     if(method==='getWebhookInfo')return ok({url:tok==='C:tokC'?'https://other-system.example/hook':'',pending_update_count:0});
     if(method==='getUpdates'){if(tok==='B:tokB'){const off=Number(payload.offset||0);return ok(updB.filter(u=>u.update_id>=off))}return ok([])}
     if(method==='getFile')return ok({file_id:payload.file_id,file_path:'documents/'+payload.file_id+'.bin'});if(method==='getMe')return ok({username:tok==='B:tokB'?'ga_po_adminpw_bot':'vrt_prod_bot'});return ok({})}};
   g2.run("CFG.INBOX_BOTS=[{id:'gapo',name:'GA PO bot',token:'B:tokB'},{id:'other',name:'Other bot',token:'C:tokC'}]");
   const rep=g2.ctx.inboxPollBots();assert.equal(rep.gapo.files,2,JSON.stringify(rep));assert.equal(rep.gapo.skipped,1,'old document skipped');assert.equal(rep.gapo.updates,4);assert.equal(rep.gapo.offset,14);assert(rep.other.webhook&&!rep.other.offset,'webhook bot skipped');
   assert(!calls.some(c=>c.method==='deleteWebhook'),'never deleteWebhook');assert(!calls.some(c=>c.tok&&c.tok.startsWith('8663')&&c.method==='getUpdates'),'PROD bot not polled here');
   const dl=calls.filter(c=>c.tok==='B:tokB'&&c.method==='getFile');assert.equal(dl.length,2);assert(calls.some(c=>c.tok==='B:tokB'&&c.method==='setMessageReaction'),'reaction with the GA PO bot');
   const q=JSON.parse(g2.raw('inbox_queue.json').content);assert.equal(q.length,2);assert.deepStrictEqual(q.map(e=>e.module),['spareparts','ie']);assert(q.every(e=>e.bot==='GA PO bot'&&e.driveId));assert.equal(q[1].group,'VRT - IE Management');
   assert.equal(g2.props.get('inbox_tg_offset_gapo'),'14');const again=g2.ctx.inboxPollBots();assert.equal(again.gapo.files,0,'second poll: nothing new');
   assert.equal(g2.ctx.inboxRoute_('Pending - OBD-4559V.xls').module,'ie');assert.equal(g2.ctx.inboxRoute_('Daily_Needles_Change_Report_24_to28_Sept.xlsx').module,'spareparts');assert.equal(g2.ctx.inboxRoute_('Jan_\'24Dec_\'24_Monthly_StatementSewing_machine_spareparts.pdf').module,'spareparts');
   const chk=g2.ctx.checkInboxBots();assert.equal(chk.length,3);assert.equal(chk[1].username,'ga_po_adminpw_bot');assert.equal(chk[2].webhook,'https://other-system.example/hook');
   return 'GA PO bot: 2 files (spare parts + IE) via its own token, 1 old skipped, text ignored, offset 14 · webhook bot skipped (no deleteWebhook) · PROD bot untouched · checkInboxBots 3 bots'});
 const pass=out.filter(x=>x.status==='PASS').length;console.log(pass+'/'+out.length+' PASS');fs.writeFileSync(path.resolve(__dirname,'inbox_results.json'),JSON.stringify(out,null,1));process.exit(pass===out.length?0:1);
})().catch(e=>{console.error(e);process.exit(1)});
