/* Seed one mock GAS with the real datasets (sewing, cutting, orders, plan, spare parts, QC) and dump a
   sample row per bucket family so the Telegram summaries can be written against real cloud shapes.
   Exports seedAll(gasFactory) for the Telegram tests. */
const fs=require('fs'),path=require('path');
const ROOT=process.env.VRT_ROOT||path.resolve(__dirname,'../..'),DL='/mnt/user-data/uploads/Downloads/',UP='/root/.claude/uploads/a1424a09-4f2e-5b2d-a6d0-9096ee09ab3e/',url='https://script.google.com/macros/s/MOCK_PROD/exec';
const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');
const jfile=(p,name)=>{const b=fs.readFileSync(p);return{name:name||path.basename(p),text:async()=>b.toString('utf8'),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
const ev=f=>({target:{files:[f],value:''}});
const wait=ms=>new Promise(res=>setTimeout(res,ms));
async function runtime(html,gas,opts){opts=opts||{};const root=opts.root||ROOT;const r=createRuntime(root+'/'+html);if(gas){r.ctx.fetch=gas.fetch;r.ctx.localStorage.setItem('vrt_portal_gas_url',url)}r.ctx.confirm=()=>true;r.ctx.alert=()=>{};r.ctx.pdfjsLib={GlobalWorkerOptions:{},getDocument:()=>({promise:Promise.reject(new Error('no pdf in harness'))})};r.saved=[];r.load();try{const proto=Object.getPrototypeOf(r.document.body);if(!proto.insertAdjacentHTML)proto.insertAdjacentHTML=function(pos,html){this.innerHTML=(pos==='afterbegin'||pos==='beforebegin')?html+this.innerHTML:this.innerHTML+html}}catch(_){}try{const X=r.ctx.XLSX;if(X)X.writeFile=(wb,name)=>{r.saved.push({name,sheets:wb.SheetNames.slice()})}}catch(_){}await wait(200);if(r.ctx.VRT_LOCAL_READY)await r.ctx.VRT_LOCAL_READY;if(gas){r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(root+'/vrt-smart-sync-v3.js','utf8'))}await wait(300);return r}
async function seedAll(g,opts){opts=opts||{};const done={};
  // sewing
  {const a=await runtime('sewing_v5.html',g);try{await a.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await wait(400);await a.ctx.vcPush();done.sewing=JSON.parse(a.run('JSON.stringify(DB.length)'))}finally{a.close()}}
  // cutting
  if(!opts.skipCutting){const a=await runtime('cutting_v3.html',g);try{await a.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')));await wait(400);await a.ctx.vcPush();done.cutting=JSON.parse(a.run('JSON.stringify(CUT.length)'))}finally{a.close()}}
  // orders
  {const a=await runtime('orders_v3.html',g);try{await a.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400);await a.ctx.ordCloudPush();done.orders=JSON.parse(a.run('JSON.stringify((APP.orders||[]).length)'))}finally{a.close()}}
  // plan
  {const a=await runtime('production_plan_capacity_v1.html',g);try{await a.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx'));await wait(500);await a.ctx.confirmPlanImport512();await wait(200);await a.ctx.cloudPush(true);done.prodplan=JSON.parse(a.run('JSON.stringify(DATA.records.length)'))}finally{a.close()}}
  // spare parts (needle + part change reports)
  {const r=createRuntime(ROOT+'/vrt_spare_parts_v2.html');r.ctx.fetch=g.fetch;r.load();await wait(150);await r.ctx.VRT_LOCAL_READY;r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(ROOT+'/vrt-smart-sync-v3.js','utf8'));try{for(const [f,n] of [[UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'],[UP+'2127d3e5-Daily_Spare_Part_Change_Report.xlsx','Daily Spare Part Change Report.xlsx']]){await r.ctx.importExcel(jfile(f,n));await r.ctx.VRTParts39.commit()}const res=await r.ctx.cloudUpload(true);if(!res||!res.ok)throw new Error('parts upload '+JSON.stringify(res));const m=r.ctx.VRTParts39.getState().maintenance;done.spareparts={needle:m.needleChanges.length,part:m.partChanges.length,stock:m.stockReports.length}}finally{r.close()}}
  // QC: KPI + daily + weekly
  {const r=createRuntime(ROOT+'/vrt_final_qc_v1.html');r.ctx.fetch=g.fetch;r.load();await r.ctx.VRT_LOCAL_READY;r.ctx.VRTPlatform.setGasUrl(url);r.run(fs.readFileSync(ROOT+'/vrt-smart-sync-v3.js','utf8'));try{const kpi={name:'VRT_Weekly_Top_3_defect_KPI_每周质量会议报告_21_25_SEP_2026.xlsx',arrayBuffer:async()=>fs.readFileSync(UP+'a727f1ff-VRT_Weekly_Top_3_defect_KPI__________21_25_SEP_2026.xlsx')},daily={name:'Final_QC_20260919.xlsx',arrayBuffer:async()=>fs.readFileSync(ROOT+'/release_sources/Final_QC_20260919.xlsx')},weekly={name:'QC_Weekly_20260914_19.xlsx',arrayBuffer:async()=>fs.readFileSync(ROOT+'/release_sources/QC_Weekly_20260914_19.xlsx')};await r.ctx.QC.importFiles([kpi,daily,weekly]);await r.ctx.QC.commit();const push=await r.ctx.QC.sync('push');if(!push.ok)throw new Error('qc push '+JSON.stringify(push));const s=r.ctx.QC.getState();done.qc={records:s.records.length,kpi:s.kpi.length}}finally{r.close()}}
  return done}
module.exports={seedAll,runtime,jfile,ev,wait,ROOT,DL,UP,url};
if(require.main===module)(async()=>{const {createGas}=require(ROOT+'/qa/v41/gas_harness');const g=createGas();const done=await seedAll(g);console.log('seeded',JSON.stringify(done));
  const dump={};for(const tool of ['sewing','cutting','orders','prodplan','spareparts','qc']){const m=g.ctx.readSmartManifest_(tool);if(!m){dump[tool]='NO MANIFEST';continue}const fam={};for(const k of Object.keys(m.buckets)){const rows=JSON.parse(g.raw(g.ctx.smartBucketName_(tool,m.buckets[k].source,k)).content);const key=k.replace(/\d{4}-(\d{2}|W\d{2})/,'YYYY-MM').replace(/_\d+$/,'_NN');if(!fam[key])fam[key]={buckets:0,rows:0,sample:rows[0],entities:{}};fam[key].buckets++;fam[key].rows+=rows.length;for(const r of rows){const e=r._vrtEntity||'(plain)';fam[key].entities[e]=(fam[key].entities[e]||0)+1;if(r._vrtEntity&&!fam[key]['sample_'+e])fam[key]['sample_'+e]=r}}dump[tool]={recordCount:m.recordCount,meta:Object.keys(m.meta||{}),summary:m.summary,families:fam}}
  fs.writeFileSync(path.resolve(__dirname,'gas_seed_dump.json'),JSON.stringify(dump,null,1));console.log('dump written');})().catch(e=>{console.error(e);process.exit(1)});
