/* v4.14 sync fixes (§3.2 of the v4.13 report): orders cloud layout, cutting-plan meta parity, shipping/FG summary without
   "today", startup pulls, portal QC read/write, custstats source, fabric-delivery resume key, ?v= tags. Real data + mock GAS. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {runtime,jfile,ev,wait,ROOT,DL,UP,url}=require('./seed_gas');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
const BASE=path.resolve(__dirname,'../../../baseline/vrt-prod-main');
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
const smartCalls=(g,from)=>g.calls.slice(from).filter(c=>c.p&&/^smart(Bucket|Commit)$/.test(c.p.action));
const q=(r,expr)=>JSON.parse(r.run('JSON.stringify('+expr+')'));
(async()=>{
 await test('Orders: side stores travel as month buckets, meta shrinks, Gemini apiKey never leaves the browser, second device gets PO + weekly + headers, unchanged re-sync transfers nothing',async()=>{const g=createGas(),a=await runtime('orders_v3.html',g),b=await runtime('orders_v3.html',g);try{await a.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400);a.run('APP.sets.apiKey="SECRET-KEY";localStorage.setItem("orderSetsV3",JSON.stringify(APP.sets))');
   const c0=g.calls.length;await a.ctx.ordCloudPush();const m=g.ctx.readSmartManifest_('orders');assert(m,'manifest');const keys=Object.keys(m.buckets);const weekly=keys.filter(k=>/^p:weekly_\d{4}-\d{2}$/.test(k)),hdr=keys.filter(k=>k==='p:headers');assert(weekly.length>=3,'weekly buckets '+weekly.join(','));assert.equal(hdr.length,1);
   const metaStr=JSON.stringify(m.meta);assert(metaStr.length<2000,'meta too big '+metaStr.length);assert(!/SECRET-KEY/.test(metaStr),'apiKey leaked into meta');assert(!g.files.some(f=>/SECRET-KEY/.test(f.content)),'apiKey leaked into a bucket');assert.equal(m.meta.summary.totalPOs,549);
   await b.ctx.ordCloudPull();await wait(600);const nb=q(b,'[APP.orders.length,APP.weekly.length,APP.headers.length,APP.imports.length]'),na=q(a,'[APP.orders.length,APP.weekly.length,APP.headers.length,APP.imports.length]');assert.deepStrictEqual(nb,na,'B '+nb+' vs A '+na);assert.equal(q(b,'APP.sets.apiKey||""'),'','B must not receive the key');
   const c1=g.calls.length;await a.ctx.ordCloudPush();await b.ctx.ordCloudPull();const extra=smartCalls(g,c1);assert.equal(extra.length,0,'re-sync transferred '+extra.map(x=>x.p.action+':'+x.p.bucket).join(','));
   return 'buckets '+keys.length+' (weekly '+weekly.length+') · meta '+metaStr.length+' ch · B '+nb.join('/')+' · re-sync 0 transfers'}finally{a.close();b.close()}});
 await test('Orders migration: cloud written by the 4.13 page (meta idbData layout) → 4.14 page pulls everything, pushes the new layout, third device matches',async()=>{const g=createGas();const old=await runtime('orders_v3.html',g,{root:BASE});try{await old.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400);await old.ctx.ordCloudPush();assert(g.ctx.readSmartManifest_('orders').meta.idbData,'old layout has idbData')}finally{old.close()}
   const b=await runtime('orders_v3.html',g),c=await runtime('orders_v3.html',g);try{await b.ctx.ordCloudPull();await wait(600);const nb=q(b,'[APP.orders.length,APP.weekly.length,APP.headers.length]');assert.equal(nb[0],549);assert(nb[1]>3000&&nb[2]>0,'weekly/headers restored from old meta: '+nb);await b.ctx.ordCloudPush();const m=g.ctx.readSmartManifest_('orders');assert(!m.meta.idbData,'new layout must not carry idbData');assert(Object.keys(m.buckets).some(k=>/^p:weekly_/.test(k)));await c.ctx.ordCloudPull();await wait(600);assert.deepStrictEqual(q(c,'[APP.orders.length,APP.weekly.length,APP.headers.length]'),nb);return 'old→new: '+nb.join('/')+' · third device identical'}finally{b.close();c.close()}});

 async function parity(name,html,tool,seed,pushFn,pullFn){return test(name,async()=>{const g=createGas(),a=await runtime(html,g),b=await runtime(html,g);try{await seed(a);await wait(300);await pushFn(a);assert(g.ctx.readSmartManifest_(tool),'no manifest');await pullFn(b);await wait(500);await pullFn(a);await wait(300);const c0=g.calls.length;await pushFn(a);await pushFn(b);await pullFn(b);const extra=smartCalls(g,c0);assert.equal(extra.length,0,'transfers after pull: '+extra.map(x=>x.p.action+':'+(x.p.bucket||'')).join(','));const st=await a.ctx.VRTSmartSync.stateGet(tool);assert.equal(st.remoteMetaHash,st.localMetaHash,'meta hash differs after pull');const meta=g.ctx.readSmartManifest_(tool).meta||{};assert(!/"(today|fileDate)"/.test(JSON.stringify(meta)),'meta still carries today: '+JSON.stringify(meta).slice(0,120));return 'push→pull→push/pull: 0 transfers · meta '+JSON.stringify(meta).slice(0,90)}finally{a.close();b.close()}})}
 await parity('Cutting plan: push/pull meta identical (summary HTML removed) → no phantom commit',"cutting_plan_v2.html",'cuttingplan',async a=>{a.run('DB=Array.from({length:40},(_,i)=>({id:"cp"+i,date:"2026-09-"+String(1+i%28).padStart(2,"0"),po:"PO"+i,selfKey:"",style:"S"+(i%5),color:"WHITE",size:"M",erpFab:"F",planQty:100+i,actualQty:i%2?100+i:0}))');await a.ctx.saveDB()},a=>a.ctx.vcPush(),a=>a.ctx.vcPull());
 await parity('Shipping: meta derived from data only (no fileDate = today) and identical on pull',"shipping_v2.html",'shipping',async a=>{a.run('ALL='+JSON.stringify(Array.from({length:50},(_,i)=>({id:'s'+i,item:'I'+i,cust:i%2?'ADI':'WPL',po:'P'+i,style:'S',orig:100,shipped:i%2?100:0,open:i%2?0:100,etd:'2026-10-'+String(1+i%20).padStart(2,'0'),status:i%2?'shipped':'outstanding'}))));await a.ctx.shipSave('seed.xlsx')},a=>a.ctx.syncToGas(),a=>a.ctx.pullFromGas());
 await parity('FG: meta derived from data (last receive / shipment dates) instead of today\'s figures; identical on pull',"VRT_FG_Inventory_Management_v1.html",'fg',async a=>{a.run('FG=Array.from({length:30},(_,i)=>({id:"fg"+i,receiveDate:"2026-09-"+String(1+i%20).padStart(2,"0"),shipmentDate:i%3?"":"2026-09-25",customer:"ADI",style:"S"+(i%4),color:"WHITE",size:"M",pcs:24+i,cartons:1,status:"ready"}))');await a.ctx.saveFG()},a=>a.ctx.vcPush(),a=>a.ctx.vcPull());
 await parity('PO delivery: pull carries the same meta as push; fabric-PO pull no longer races 1.2 s after load',"VRT_PO_Delivery_Control_Center.html",'podelivery',async a=>{a.run('DATA=Array.from({length:20},(_,i)=>({id:"po"+i,po:"PO"+i,customer:"ADI",style:"S",qty:100,poDate:"2026-09-01",custShip:"2026-10-"+String(1+i).padStart(2,"0"),completed:null,risk:i%4?"ok":"risk"}))');await a.ctx.dbSaveAll(JSON.parse(a.run('JSON.stringify(DATA)')))},a=>a.ctx.vcPush?a.ctx.vcPush():a.elements.get('vcPushBtn2').onclick(),a=>a.ctx.vcPull?a.ctx.vcPull():a.elements.get('vcPullBtn2').onclick());
 await test('Customer statistics: pulled snapshot keeps the cloud source name (no "Cloud" stamp) → B\'s next push transfers nothing',async()=>{const g=createGas(),a=await runtime('vrt_customer_statistics_control_center_v1.html',g),b=await runtime('vrt_customer_statistics_control_center_v1.html',g);try{a.run('DATA={overall:{poCount:2,orderQty:300,completedQty:100,balanceQty:200},customers:[{customer:"ADI",orderQty:300,balanceQty:200}],products:[],details:[{id:"d1",customer:"ADI",po:"P1",orderQty:100,completedQty:50,balanceQty:50,etd:"2026-10-01"},{id:"d2",customer:"ADI",po:"P2",orderQty:200,completedQty:50,balanceQty:150,etd:"2026-10-02"}],source:"Customer_Stats_2026-09-30.xlsx",snapshotDate:"2026-09-30"}');await a.ctx.save();await a.ctx.cloudPush(true);await b.ctx.cloudPull();await wait(300);assert.equal(q(b,'DATA.source'),'Customer_Stats_2026-09-30.xlsx');const c0=g.calls.length;await b.ctx.cloudPush(true);assert.equal(smartCalls(g,c0).length,0,'B re-pushed after pull');return 'source kept · B push after pull: 0 transfers'}finally{a.close();b.close()}});
 await test('Portal QC: portal push sends KPI rows + source metadata only (no base64); QC module pull gets records + KPI; module push → portal pull keeps the local attachment',async()=>{const g=createGas();const qcr=async()=>{const r=createRuntimeQC(g);return r};function createRuntimeQC(gas){const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');const r=createRuntime(ROOT+'/vrt_final_qc_v1.html');r.ctx.fetch=gas.fetch;r.load();return r}
   const m=await qcr();await m.ctx.VRT_LOCAL_READY;m.ctx.VRTPlatform.setGasUrl(url);m.run(fs.readFileSync(ROOT+'/vrt-smart-sync-v3.js','utf8'));const f=(p,n)=>({name:n,arrayBuffer:async()=>fs.readFileSync(p)});await m.ctx.QC.importFiles([f(UP+'a727f1ff-VRT_Weekly_Top_3_defect_KPI__________21_25_SEP_2026.xlsx','VRT_Weekly_Top_3_defect_KPI_每周质量会议报告_21_25_SEP_2026.xlsx'),f(ROOT+'/release_sources/Final_QC_20260919.xlsx','Final_QC_20260919.xlsx')]);await m.ctx.QC.commit();const st=m.ctx.QC.getState();assert(st.kpi.length===54&&st.records.length>0);
   // the portal in the SAME browser (same IndexedDB in this runtime) pushes
   const dbs=m.dbs;m.run('window.__keep=1');const p=await runtime('portal_v2.html',g);try{p.dbs.clear();for(const [k,v] of dbs)p.dbs.set(k,v);p.ctx.gasUrl=url;await p.ctx.push('qc');const man=g.ctx.readSmartManifest_('qc');assert(man,'portal push');const keys=Object.keys(man.buckets);assert(keys.includes('p:kpi_2026-09'),'kpi bucket from portal: '+keys.join(','));assert(!g.files.some(x=>x.name.startsWith('smart_qc_')&&/"base64"/.test(x.content)),'base64 leaked to cloud');assert.deepStrictEqual(man.meta,{schemaVersion:413,sourceAttachmentPolicy:'metadata-only'});
     const m2=await qcr();await m2.ctx.VRT_LOCAL_READY;m2.ctx.VRTPlatform.setGasUrl(url);m2.run(fs.readFileSync(ROOT+'/vrt-smart-sync-v3.js','utf8'));const pull=await m2.ctx.QC.sync('pull');assert(pull&&pull.ok,JSON.stringify(pull).slice(0,200));const s2=m2.ctx.QC.getState();assert.equal(s2.kpi.length,54);assert.equal(s2.records.length,st.records.length);
     // module edits + pushes; portal (with local base64 sources) pulls → attachments remain
     await m2.ctx.QC.sync('push');const before=(await p.ctx.VRTProdStorage.all('VRT_FinalQC','sources',{keyPath:'id'})).filter(s=>s.base64).length;assert(before>0,'no local attachments to protect');await p.ctx.pull('qc');const after=(await p.ctx.VRTProdStorage.all('VRT_FinalQC','sources',{keyPath:'id'})).filter(s=>s.base64).length;assert.equal(after,before,'portal pull dropped attachments');const kpiLocal=await p.ctx.VRTProdStorage.all('VRT_FinalQC','kpi',{keyPath:'id'});assert.equal(kpiLocal.length,54);m2.close();return 'portal push: '+keys.length+' buckets incl. kpi_2026-09, no base64 · module pull: '+s2.records.length+' records + 54 KPI · portal pull keeps '+after+' attachments'}finally{p.close();m.close()}});

 await test('PO delivery demo rows: a fresh browser with the shared GAS URL starts empty (no SEED saved, nothing pushed); without a GAS URL the sample shows but is never persisted',async()=>{const g=createGas(),a=await runtime('VRT_PO_Delivery_Control_Center.html',g);try{await wait(300);assert.equal(q(a,'DATA.length'),0,'seed persisted with GAS URL');const stored=await a.ctx.dbLoadAll();assert.equal((stored||[]).length,0)}finally{a.close()}
   const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');const b=createRuntime(ROOT+'/VRT_PO_Delivery_Control_Center.html');b.ctx.alert=()=>{};b.load();await wait(600);try{const n=q(b,'DATA.length'),demo=q(b,'DATA.filter(r=>r._demo).length');assert(n>0&&demo===n,'sample rows should be marked _demo: '+n+'/'+demo);const stored=await b.ctx.dbLoadAll();assert.equal((stored||[]).length,0,'sample must not be saved');return 'with GAS URL: 0 rows · offline: '+n+' sample rows, all _demo, 0 saved'}finally{b.close()}});
 await test('Production overview: pulls the v4.14 orders layout into FactoryDB correctly (plain PO lines only; weekly/headers into their stores) and skips a tool whose owner tab holds the sync lock',async()=>{const g=createGas(),a=await runtime('orders_v3.html',g);try{await a.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400);await a.ctx.ordCloudPush()}finally{a.close()}
   const o=await runtime('production_v4.html',g);try{o.run('delete window.VRTProdAutoSync');o.run(fs.readFileSync(ROOT+'/vrt-auto-sync-v3.js','utf8'));assert(typeof o.ctx.VRTProdAutoSync.lock==='function','real auto-sync loaded');o.run('gasUrl="'+url+'"');const ok=await o.ctx.vcAutoPullOverview();assert(ok,'overview pull');const lines=await o.ctx.idbGetAll?o.ctx.idbGetAll('FactoryDB',15,'po_lines'):null;
     const db=o.dbs.get('FactoryDB');assert(db,'FactoryDB');const po=[...db.stores.get('po_lines').values.values()],wk=[...db.stores.get('weekly_snapshots').values.values()],hd=[...db.stores.get('po_headers').values.values()];assert.equal(po.length,549);assert(po.every(r=>!r._vrtEntity),'envelope rows leaked into po_lines');assert.equal(wk.length,3602);assert.equal(hd.length,11);
     // owner lock held by another tab → overview skips that tool
     o.ctx.localStorage.setItem('vrt:prod:auto37:lock:orders',JSON.stringify({at:Date.now(),tab:'other-tab'}));const c0=g.calls.length;await o.ctx.vcAutoPullOverview();const ordersCalls=g.calls.slice(c0).filter(c=>c.p&&c.p.tool==='orders').length;assert.equal(ordersCalls,0,'orders pulled despite lock');return 'po_lines 549 plain · weekly 3602 · headers 11 · locked tool skipped'}finally{o.close()}});
 fs.writeFileSync(path.resolve(__dirname,'sync_fixes_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})().catch(e=>{console.error(e);process.exit(1)});
