/* v4.14 portal overview: reads every module's own IndexedDB read-only (real Downloads data), freshness cards for all modules,
   period comparator (same numbers as the Telegram builders), plan vs actual, cut vs sew, digest text; never writes/creates DBs. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {runtime,jfile,ev,wait,ROOT,DL,UP,url}=require('./seed_gas');const {createRuntime}=require(ROOT+'/qa/v39/runtime_harness');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
const q=(r,expr)=>JSON.parse(r.run('JSON.stringify('+expr+')'));
async function seedMaster(){const master=new Map();const add=r=>{for(const [k,v] of r.dbs)if(!master.has(k))master.set(k,v)};
  let r=await runtime('sewing_v5.html');await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await wait(400);add(r);r.close();
  r=await runtime('cutting_v3.html');await r.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')));await wait(400);add(r);r.close();
  r=await runtime('orders_v3.html');await r.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400);add(r);r.close();
  r=await runtime('production_plan_capacity_v1.html');await r.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx'));await wait(500);await r.ctx.confirmPlanImport512();await wait(200);add(r);r.close();
  r=createRuntime(ROOT+'/vrt_spare_parts_v2.html');r.load();await wait(150);await r.ctx.VRT_LOCAL_READY;await r.ctx.importExcel(jfile(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'));await r.ctx.VRTParts39.commit();add(r);r.close();
  r=createRuntime(ROOT+'/vrt_final_qc_v1.html');r.load();await r.ctx.VRT_LOCAL_READY;const f=(p,n)=>({name:n,arrayBuffer:async()=>fs.readFileSync(p)});await r.ctx.QC.importFiles([f(UP+'a727f1ff-VRT_Weekly_Top_3_defect_KPI__________21_25_SEP_2026.xlsx','VRT_Weekly_Top_3_defect_KPI_每周质量会议报告_21_25_SEP_2026.xlsx'),f(ROOT+'/release_sources/Final_QC_20260919.xlsx','Final_QC_20260919.xlsx')]);await r.ctx.QC.commit();add(r);r.close();
  r=await runtime('ie_smv_report_v2_1.html');const app=r.ctx.VRT_IE_SMV_APP;const jf=p=>({name:path.basename(p),arrayBuffer:async()=>fs.readFileSync(p)});await app.importCandidates(await app.parseFile(jf(DL+'VRT_IE_Weekly_SMV_Update_Report_CN_EN_Approved_20260930.xlsx')));await wait(300);add(r);r.close();
  return master}
async function portal(master,gas){const p=await runtime('portal_v2.html',gas);p.dbs.clear();for(const [k,v] of master)p.dbs.set(k,v);await p.ctx.VRTPortalOverview.refresh();return p}
(async()=>{
 const master=await seedMaster();const dbNames=[...master.keys()];
 await test('Freshness: 17 module cards, counts match the modules (sewing 5,009 · cutting daily rows · orders 549 · plan 705 · needles 453 · QC 13+54 · IE updates); latest dates + colours; no database created or upgraded',async()=>{const p=await portal(master);try{const st=p.ctx.VRTPortalOverview.state,d=st.data;assert.equal(d.sewing.count,5009);assert.equal(d.orders.count,549);assert.equal(d.prodplan.count,705);assert.equal(d.spareparts.needle.length,453);assert.equal(d.qc.records.length,13);assert.equal(d.qc.kpi.length,54);assert(d.ie.count>70,'ie '+d.ie.count);assert(d.cutting.count>0&&d.cutting.count<18663,'cutting daily-only '+d.cutting.count);assert.equal(d.sewing.latest,'2026-09-28');assert.equal(d.qc.latest,'2026-09-25');
   const html=p.elements.get('vrtOverview').innerHTML;const cards=(html.match(/class="fc /g)||[]).length;assert.equal(cards,17);assert(/DATA FRESHNESS/.test(html)&&/PERIOD COMPARISON/.test(html)&&/PLAN vs ACTUAL/.test(html)&&/CUT vs SEW/.test(html));
   const after=[...p.dbs.keys()].filter(k=>!dbNames.includes(k));const written=after.filter(k=>{const d=p.dbs.get(k);return d&&[...d.stores.values()].some(s=>s.values.size)});assert.deepStrictEqual(written,[],'overview wrote into databases: '+written.join(','));   // the simulated IndexedDB cannot abort a create; real browsers verified with Playwright
   return 'cards 17 · sewing '+d.sewing.count+' latest '+d.sewing.latest+' · cutting daily '+d.cutting.count+' · qc '+d.qc.records.length+'+'+d.qc.kpi.length+' · ie '+d.ie.count+' · nothing written'}finally{p.close()}});
 await test('Period comparator: week/month numbers equal the shared Telegram builders (sewing pieces, cutting pieces, QC reject rate, needle qty); prev period + Δ present; anchor options only with data',async()=>{const p=await portal(master);try{const O=p.ctx.VRTPortalOverview,S=p.ctx.VRTTgSummary;O.setPeriod('month');O.setAnchor('2026-09-01');const m=O.metrics();const row=n=>m.rows.find(r=>r[0].includes(n));const sewRow=row('Sewing output'),cutRow=row('Cut pieces'),qcRow=row('Reject rate'),ndl=row('Needle changes');
   const sew=S.build('sewing',p.ctx.VRTPortalOverview.state.data.sewing.rows,'month','2026-09-01',{}).stats;assert.equal(sewRow[1],sew.pieces);assert.equal(sewRow[1],8013);const cut=S.build('cutting',O.state.data.cutting.rows,'month','2026-09-01',{}).stats;assert.equal(cutRow[1],cut.pieces);const qcExp=S.build('qc',{records:O.state.data.qc.records,kpi:O.state.data.qc.kpi},'month','2026-09-01',{}).stats.qc.rate;assert(Math.abs(qcRow[1]-qcExp)<1e-9,'qc rate '+qcRow[1]+' vs '+qcExp);assert.equal(ndl[1],1170);assert(sewRow[2]>0,'prev month sewing');
   const html=p.elements.get('vrtOverview').innerHTML;assert(/▲|▼/.test(html),'delta arrows');assert(/2026-09/.test(html)&&/2026-08/.test(html));return 'Sep sewing '+sewRow[1]+' (prev '+sewRow[2]+') · cut '+cutRow[1]+' · reject '+qcRow[1].toFixed(2)+'% · needles '+ndl[1]}finally{p.close()}});
 await test('Plan vs actual: September plan rows matched to sewing by style (line + all lines) and cutting; flags for no-output / low; unplanned styles listed',async()=>{const p=await portal(master);try{const O=p.ctx.VRTPortalOverview;O.setPeriod('month');O.setAnchor('2026-09-01');const c=O.planCheck();assert(c.rows.length>100,'plan rows '+c.rows.length);const withOutput=c.rows.filter(r=>r.sewnAll>0).length,bad=c.rows.filter(r=>r.flag==='bad').length;assert(c.rows.every(r=>r.planned>=0&&typeof r.line==='string'));assert(Array.isArray(c.unplanned));const html=p.elements.get('vrtOverview').innerHTML;assert(/no output/.test(html));return 'plan rows '+c.rows.length+' · with sewing output '+withOutput+' · no-output flags '+bad+' · unplanned styles '+c.unplanned.length}finally{p.close()}});
 await test('Cut vs sew: cumulative cut before + in period vs sewn per style; sewn > cut flagged; daily totals use cutting detail rows only',async()=>{const p=await portal(master);try{const O=p.ctx.VRTPortalOverview;O.setPeriod('month');O.setAnchor('2026-09-01');const c=O.cutSewCheck();assert(c.rows.length>0);const bad=c.rows.filter(r=>r.flag==='bad'),ok=c.rows.filter(r=>r.flag==='ok');assert(c.rows.every(r=>r.avail===r.cutBefore+r.cutPeriod&&r.gap===r.avail-r.sewn));const cutSum=c.days.reduce((s,d)=>s+d.cut,0);const cutBuild=p.ctx.VRTTgSummary.build('cutting',O.state.data.cutting.rows,'month','2026-09-01',{}).stats.pieces;assert.equal(cutSum,cutBuild,'daily cut totals must equal the cutting builder');return 'styles '+c.rows.length+' · sewn>cut '+bad.length+' · ok '+ok.length+' · days '+c.days.length+' · Sep cut '+cutSum}finally{p.close()}});
 await test('Digest → Telegram from the portal: same 5-department text shape as the bot, sent through the GAS proxy',async()=>{const g=createGas({gsPath:path.resolve(__dirname,'../../AppsScript/VRT_Production_v4.4.gs')});const p=await portal(master,g);try{const O=p.ctx.VRTPortalOverview;O.setPeriod('week');const text=O.digestText('week','2026-09-21');for(const k of ['車縫','裁剪','Final QC','機針','排單'])assert(text.includes(k),k);assert(text.length<4000);const sent=[];g.ctx.UrlFetchApp={fetch(u,o){sent.push(JSON.parse(o.payload));return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:{message_id:1}})}}};p.ctx.confirm=()=>true;p.ctx.alert=()=>{};await O.sendDigest();assert.equal(sent.length,1);assert.equal(sent[0].parse_mode,'HTML');assert(sent[0].text.includes('digest'));return 'digest '+text.length+' ch → sendMessage HTML to '+sent[0].chat_id}finally{p.close()}});
 fs.writeFileSync(path.resolve(__dirname,'portal_overview_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})().catch(e=>{console.error(e);process.exit(1)});
