/* v4.14 shared language layer (vrt-i18n-v1.js + vrt-i18n-en.js / vrt-i18n-km.js), Node-only checks:
   - every page loads the layer inside <head> before its own scripts
   - every Chinese UI string found in the pages / shared JS has an English and a Khmer entry with the same {n} placeholders
   - the translator handles exact, numeric, template, bilingual, segment and run fallbacks; 中文 mode changes nothing
   - one language key drives every module's legacy key (incl. JSON-encoded costing key and PO settings)
   The rendered-page check (no Chinese left in EN / KM on all 21 pages) is qa/v414/browser_i18n_check.js (needs Playwright). */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=process.env.VRT_ROOT||path.resolve(__dirname,'../..');
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
function layer(store,page){const ctx={console,setTimeout,clearTimeout,setInterval:()=>0,location:{pathname:'/'+(page||'x.html')},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}},document:{readyState:'complete',documentElement:{},getElementsByTagName:()=>[],addEventListener(){},head:{appendChild(){}},body:null,getElementById:()=>null,createElement:()=>({style:{},setAttribute(){},addEventListener(){},appendChild(){}})},CustomEvent:function(){},dispatchEvent(){},addEventListener(){},alert(m){ctx._alerts.push(m)},confirm(m){ctx._alerts.push(m);return true},prompt(){return ''},_alerts:[]};ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(ROOT+'/vrt-i18n-en.js','utf8'),ctx);vm.runInContext(fs.readFileSync(ROOT+'/vrt-i18n-km.js','utf8'),ctx);vm.runInContext(fs.readFileSync(ROOT+'/vrt-i18n-v1.js','utf8'),ctx);return ctx}
(async()=>{
 const pages=fs.readdirSync(ROOT).filter(f=>/\.html$/.test(f));
 await test('Every page loads vrt-i18n-v1.js inside <head>, before any inline script',async()=>{const bad=[];for(const f of pages){const s=fs.readFileSync(path.join(ROOT,f),'utf8'),i=s.indexOf('src="vrt-i18n-v1.js'),h=s.search(/<\/head>/i),firstInline=s.search(/<script>(?!\s*<\/script>)/i);if(!(i>0&&i<h&&(firstInline<0||i<firstInline)))bad.push(f)}assert.deepStrictEqual(bad,[]);return pages.length+' pages'});
 await test('Dictionary: every extracted Chinese UI string has en + km with identical {n} placeholders; no Chinese left in the translations (file names excepted)',async()=>{const en=layer({}).VRT_I18N_EN,km=layer({}).VRT_I18N_KM;const keys=Object.keys(en);assert.equal(keys.length,Object.keys(km).length);let ph=0,cjk=0;for(const k of keys){const c=s=>(String(s).match(/\{n\}/g)||[]).length;if(c(k)!==c(en[k])||c(k)!==c(km[k]))ph++;if(/[一-鿿]/.test(en[k])&&!/xlsx|工作表|「|“|款式 \/ Style|簽核狀態/.test(en[k]))cjk++}assert.equal(ph,0,'placeholder mismatches');assert(cjk<=10,'Chinese left in '+cjk+' English values');
   const keyFile=path.resolve(__dirname,'i18n_keys.json');try{require('child_process').execFileSync(process.execPath,[path.resolve(__dirname,'i18n_extract.js')],{stdio:'ignore'})}catch(_){}if(fs.existsSync(keyFile)){const need=Object.keys(require(keyFile));const miss=need.filter(k=>en[k]==null);assert.equal(miss.length,0,'missing: '+miss.slice(0,5).join(' | '))}return keys.length+' entries · placeholders consistent'});
 await test('Translator: exact, numbers, template values, bilingual pairs, segments, runs, punctuation tidy; KM from the Khmer file',async()=>{const c=layer({vrt_ui_lang:'en'});await c.VRTI18n.load('en');const T=s=>c.VRTI18n.translate(s);
   const cases=[['已儲存','Saved'],['確定刪除這筆 Production Plan？','Delete this Production Plan?'],['2026-10 記錄','2026-10 Records'],['上傳：Portal 待機 · 各模組自動同步','Upload: Portal idle · each module syncs automatically'],['(sewn, not yet in FG): 177289（欠 744）、4661（欠 1,428）','(sewn, not yet in FG): 177289 (short 744), 4661 (short 1,428)'],['目前無 Sewing 待同步標記','No Sewing pending-sync flags']];
   for(const [zh,en] of cases)assert.equal(T(zh),en,zh);assert.equal(T('  已儲存  '),'  Saved  ','keeps surrounding whitespace');assert.equal(T('ADI'),null,'no Chinese → untouched');
   const k=layer({vrt_ui_lang:'km'});await k.VRTI18n.load('km');await k.VRTI18n.load('en');const kmSaved=k.VRTI18n.translate('已儲存');assert(/[ក-៿]/.test(kmSaved),'khmer '+kmSaved);
   const z=layer({vrt_ui_lang:'zh'});assert.equal(z.VRTI18n.translate('已儲存'),null,'中文 mode must not translate');assert.equal(typeof z.VRT_I18N_EN,'object');
   return cases.length+' EN cases · KM "已儲存" → '+kmSaved});
 await test('One language key: vrt_ui_lang=km is copied into every module\'s legacy key (costing key JSON-encoded, PO settings.lang updated); an old module key is honoured when the shared key is missing',async()=>{const st={vrt_ui_lang:'km',vrt_pocc_settings:JSON.stringify({lang:'zh',x:1})};layer(st,'sewing_v5.html');for(const k of ['vrt_lang','cut_lang','vrt_bom2_lang','vrt_pocc_lang','vrt_ie_smv_lang','vrt_fabric_lang','vrt_sp_lang'])assert.equal(st[k],'km',k);assert.equal(st['vrt-cost-lang'],'"km"');assert.equal(JSON.parse(st.vrt_pocc_settings).lang,'km');assert.equal(JSON.parse(st.vrt_pocc_settings).x,1);
   const st2={vrt_sp_lang:'en'};const c2=layer(st2,'portal_v2.html');assert.equal(c2.VRTI18n.lang,'en');assert.equal(st2.vrt_ui_lang,'en');assert.equal(st2.cut_lang,'en');return 'legacy keys synced · fallback from vrt_sp_lang works'});
 await test('alert / confirm messages are translated line by line (EN)',async()=>{const c=layer({vrt_ui_lang:'en'});await c.VRTI18n.load('en');c.alert('已儲存');c.confirm('確定刪除這筆 Production Plan？\n已儲存');assert.deepStrictEqual(c._alerts,['Saved','Delete this Production Plan?\nSaved']);return JSON.stringify(c._alerts)});
 await test('Fixed page bugs: sewing km reads data-km, production plan button uses the shared layer, PO header language wins over old settings, IE km has chineseNote',async()=>{const sw=fs.readFileSync(ROOT+'/sewing_v5.html','utf8'),pp=fs.readFileSync(ROOT+'/production_plan_capacity_v1.html','utf8'),po=fs.readFileSync(ROOT+'/VRT_PO_Delivery_Control_Center.html','utf8'),ie=fs.readFileSync(ROOT+'/ie_smv_report_v2_1.html','utf8');assert.equal((sw.match(/_lang==='km' \? \(el\.dataset\.km\|\|el\.dataset\.en\)/g)||[]).length,2);assert(/function toggleLang\(\)\{if\(window\.VRTI18n\)\{LANG=VRTI18n\.cycle\(\)/.test(pp));assert(/LANG=localStorage\.getItem\('vrt_pocc_lang'\)\|\|SET\.lang\|\|LANG/.test(po));assert(/km:\{chineseNote:"/.test(ie));return 'ok'});
 fs.writeFileSync(path.resolve(__dirname,'i18n_layer_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})();
