/* v4.14 per-page Telegram sender: every module's ✈️ button builds the same text as the bot, lists only periods with data,
   sends through the GAS proxy (HTML, default group), falls back to plain text, and the shared builders are HTML-safe. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {seedAll,runtime,jfile,ev,wait,ROOT,DL,UP,url}=require('./seed_gas');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
const GS=path.resolve(__dirname,'../../AppsScript/VRT_Production_v4.4.gs');
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
function htmlOk(t){const s=t.replace(/<\/?b>/g,'');assert(!/[<>]/.test(s.replace(/&lt;|&gt;/g,'')),'stray tag: '+(s.match(/.{0,30}[<>].{0,30}/)||[])[0]);assert.equal((t.match(/<b>/g)||[]).length,(t.match(/<\/b>/g)||[]).length,'unbalanced <b>');assert(t.length<=4096)}
const hasZhEn=t=>/[一-鿿]/.test(t)&&/[A-Za-z]{3,}/.test(t);
function captureTelegram(g){const sent=[];g.ctx.UrlFetchApp={fetch(u,o){let p={};try{p=JSON.parse(o.payload)}catch(_){}sent.push(p);if(sent.rejectHtml&&p.parse_mode==='HTML')return {getResponseCode:()=>400,getContentText:()=>JSON.stringify({ok:false,description:"Bad Request: can't parse entities"})};return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:{message_id:1}})}}};return sent}
(async()=>{
 const g=createGas({gsPath:GS});
 await test('Sewing page: ✈️ button + modal; period list only holds periods with data (newest first, with counts); preview = shared builder text',async()=>{const r=await runtime('sewing_v5.html',g);try{await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await wait(400);assert(r.ctx.VRTTelegram&&r.ctx.VRTTgSummary,'scripts loaded');assert(r.elements.get('vrtTgFab'),'floating button');
   const months=await r.ctx.VRTTelegram.options('month');assert(months.length>10,'months '+months.length);assert(months[0].anchor>months[1].anchor,'newest first');assert(months.every(o=>o.count>0));const sep=months.find(o=>o.key==='2026-09');assert(sep,'2026-09 present');
   await r.ctx.VRTTelegram.open('month');const pv=r.elements.get('vrtTgPreview').textContent;assert(/車縫 Sewing/.test(pv)&&/Output/.test(pv),pv.slice(0,120));
   const b=await r.ctx.VRTTelegram.text('month','2026-09-01');const direct=r.ctx.VRTTgSummary.build('sewing',JSON.parse(r.run('JSON.stringify(DB)')),'month','2026-09-01',{metaLine:''});assert.equal(b.body,direct.body);htmlOk(b.text);assert(hasZhEn(b.text));
   return 'months with data '+months.length+' · 2026-09 rows '+sep.count+' · month body '+b.body.length+' ch identical to direct build'}finally{r.close()}});
 await test('Page text == bot text: the same September sewing summary from the page and from GAS /sum buttons (bucket data) is identical',async()=>{const seeded=await seedAll(g,{skipCutting:true});const r=await runtime('sewing_v5.html',g);try{await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await wait(300);const page=await r.ctx.VRTTelegram.text('month','2026-09-01');const bot=g.ctx.periodSummary_('sew','month','2026-09-01').built;assert.equal(page.body,bot.body);const w=await r.ctx.VRTTelegram.text('week','2026-09-21'),wb=g.ctx.periodSummary_('sew','week','2026-09-21').built;assert.equal(w.body,wb.body);return 'month + week bodies identical ('+page.body.length+' / '+w.body.length+' ch) · seeded '+JSON.stringify(seeded).slice(0,80)}finally{r.close()}});
 await test('Send from the page: GAS proxy receives HTML + default group; HTML rejected → resent as plain text; missing GAS URL → clear error',async()=>{const r=await runtime('sewing_v5.html',g);try{await r.ctx.restoreData(ev(jfile(DL+'sewing_backup_2026-09-28.json')));await wait(300);const sent=captureTelegram(g);const b=await r.ctx.VRTTelegram.text('week','');const res=await r.ctx.VRTTelegram.send(b.text,'');assert(res.ok&&!res.plain);assert.equal(sent.length,1);assert.equal(sent[0].parse_mode,'HTML');assert.equal(String(sent[0].chat_id),'-5221939558');assert(sent[0].text.includes('車縫'));
   sent.length=0;sent.rejectHtml=true;const res2=await r.ctx.VRTTelegram.send(b.text,'-100999');assert(res2.ok&&res2.plain);assert.equal(sent.length,2);assert(!sent[1].parse_mode&&!/<b>/.test(sent[1].text)&&String(sent[1].chat_id)==='-100999');
   r.ctx.localStorage.removeItem('vrt_portal_gas_url');r.ctx.VRTPlatform.getGasUrl=()=>'';let err='';try{await r.ctx.VRTTelegram.send(b.text,'')}catch(e){err=e.message}assert(/GAS/.test(err),err);return 'HTML to default group ok · plain-text fallback ok · no-URL error: '+err.slice(0,40)}finally{r.close()}});
 const cases=[
  ['cutting_v3.html','cutting',async r=>{await r.ctx.restoreCutJSON(ev(jfile(DL+'cutting_backup_2026-09-30.json')));await wait(400)}],
  ['vrt_final_qc_v1.html','qc',async r=>{const f=(p,n)=>({name:n,arrayBuffer:async()=>fs.readFileSync(p)});await r.ctx.QC.importFiles([f(UP+'a727f1ff-VRT_Weekly_Top_3_defect_KPI__________21_25_SEP_2026.xlsx','VRT_Weekly_Top_3_defect_KPI_每周质量会议报告_21_25_SEP_2026.xlsx'),f(ROOT+'/release_sources/Final_QC_20260919.xlsx','Final_QC_20260919.xlsx')]);await r.ctx.QC.commit()}],
  ['vrt_spare_parts_v2.html','spareparts',async r=>{await r.ctx.importExcel(jfile(UP+'91490ff4-Daily_Needles_Change_Report_24_to28_Sept.xlsx','Daily Needles Change Report 24 to28 Sept.xlsx'));await r.ctx.VRTParts39.commit()}],
  ['production_plan_capacity_v1.html','prodplan',async r=>{await r.ctx.importFile(jfile(DL+'Production  Plan From July Until  Dec_2026 (1).xlsx'));await wait(500);await r.ctx.confirmPlanImport512()}],
  ['orders_v3.html','orders',async r=>{await r.ctx.restore(ev(jfile(DL+'orders_v3_backup_2026-09-30.json')));await wait(400)}],
  ['shipping_v2.html','shipping',async r=>{r.run('ALL='+JSON.stringify(Array.from({length:30},(_,i)=>({id:'s'+i,item:'I'+i,cust:i%2?'ADI':'WPL',po:'P'+i,style:'S',orig:100,shipped:i%2?100:0,open:i%2?0:100,etd:'2026-10-'+String(1+i%20).padStart(2,'0'),status:i%2?'shipped':'outstanding'}))));await r.ctx.shipSave('seed.xlsx')}],
  ['vrt_monthly_shipping_control_center_v1.html','monthship',async r=>{r.run('DATA.records=Array.from({length:20},(_,i)=>({id:"m"+i,month:"2026-10",date:"2026-10-"+String(1+i).padStart(2,"0"),customer:"ADI",size:"M",mode:"SEA",pieces:100+i,cartons:4,status:"PLAN"}))');await r.ctx.save()}],
  ['vrt_customer_statistics_control_center_v1.html','custstats',async r=>{r.run('DATA={overall:{poCount:2,orderQty:300,completedQty:100,balanceQty:200,completion:0.33,cuttingWip:10,fgPcs:5,fgCtn:1,actualNotSewn:3,noFabric:0},customers:[{customer:"ADI",balanceQty:200}],products:[],details:[{id:"d1",customer:"ADI",po:"P1",orderQty:300,etd:"2026-10-05"}],snapshotDate:"2026-09-30"}');await r.ctx.save()}],
  ['vrt_fabric_stock_control_v1.html','fabricstock',async r=>{r.run('DB.current=[{snapshotDate:"2026-09-29",itemCode:"TCF1",lotNumber:"L1",quantity:120,location:"A",unit:"YD"},{snapshotDate:"2026-09-29",itemCode:"TCF2",lotNumber:"L2",quantity:80,location:"A",unit:"YD"}];DB.old=[{useDate:"2026-09-10",itemCode:"TCF1",quantity:10,po:"P",style:"S"}];DB.accessory=[]');await r.ctx.save(true)}],
  ['ie_smv_report_v2_1.html','ie',async r=>{const app=r.ctx.VRT_IE_SMV_APP;const jf=p=>({name:path.basename(p),arrayBuffer:async()=>fs.readFileSync(p)});const cands=await app.parseFile(jf(DL+'VRT_IE_Weekly_SMV_Update_Report_CN_EN_Approved_20260930.xlsx'));await app.importCandidates(cands)}],
 ];
 for(const [html,kind,seed] of cases)await test(kind+' page ('+html+'): button present, options with data, 日/週/月/年 texts bilingual + HTML-safe',async()=>{const r=await runtime(html,g);try{await seed(r);await wait(300);assert(r.ctx.VRTTelegram,'no VRTTelegram');assert.equal(r.ctx.VRTTelegram.cfg.kind,kind);assert(r.elements.get('vrtTgFab'),'button');const res=[];for(const p of ['day','week','month','year']){const opts=await r.ctx.VRTTelegram.options(p);assert(opts.length>=1,p+' no options');const b=await r.ctx.VRTTelegram.text(p,opts[0].anchor);htmlOk(b.text);assert(hasZhEn(b.text),p+' not bilingual');assert(!b.empty,p+' empty: '+b.text.slice(0,200));res.push(p+':'+opts.length+'/'+b.text.length)}return res.join(' · ')}finally{r.close()}});
 fs.writeFileSync(path.resolve(__dirname,'tg_page_results.json'),JSON.stringify(out,null,2));const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
})().catch(e=>{console.error(e);process.exit(1)});
