/* GAS v4.4 Telegram checks against real cloud data (seeded through the real modules into a mock GAS):
   /prod /prod2 /sum menus in a group, /day /week /month /year digests, per-department 日/週/月/年 summaries with prev/next,
   bilingual + HTML-safe text, 4096 guard, plain-text fallback, polling loop, and number cross-checks against the source backups. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const {seedAll,ROOT,DL}=require('./seed_gas');const {createGas}=require(ROOT+'/qa/v41/gas_harness');
const GS=path.resolve(__dirname,'../../AppsScript/VRT_Production_v4.4.gs'),GROUP='-5221939558';
const out=[];async function test(name,fn){try{out.push({name,status:'PASS',detail:await fn()});console.log('PASS',name,'·',out.at(-1).detail)}catch(e){out.push({name,status:'FAIL',detail:e.stack});console.log('FAIL',name,'·',e.message)}}
function stubTelegram(g,opts){opts=opts||{};const sent=[];let updates=opts.updates||[];g.ctx.UrlFetchApp={fetch(url,o){const m=String(url).match(/\/bot[^/]+\/(\w+)/);const method=m?m[1]:url;let payload={};try{payload=o&&o.payload?JSON.parse(o.payload):{}}catch(_){}
  if(method==='getUpdates'){const r=updates;updates=[];return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:r})}}
  if(opts.rejectHtml&&(method==='sendMessage'||method==='editMessageText')&&payload.parse_mode==='HTML'){sent.push({method,payload,rejected:true});return {getResponseCode:()=>400,getContentText:()=>JSON.stringify({ok:false,description:"Bad Request: can't parse entities"})}}
  sent.push({method,payload});return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:{message_id:100+sent.length}})}}};return sent}
const msg=(text,chat)=>({message_id:1,text,chat:{id:Number(chat||GROUP),type:'supergroup'},from:{id:1}});
const cbq=(data,mid)=>({id:'cb'+Math.random(),data,message:{message_id:mid||55,chat:{id:Number(GROUP),type:'supergroup'}}});
const hasZhEn=t=>/[\u4e00-\u9fff]/.test(t)&&/[A-Za-z]{3,}/.test(t);
function htmlOk(t){ // only <b> tags, balanced; no stray < >
  const stripped=t.replace(/<\/?b>/g,'');assert(!/[<>]/.test(stripped.replace(/&lt;|&gt;/g,'')),'stray < or > in: '+stripped.match(/.{0,30}[<>].{0,30}/));const o=(t.match(/<b>/g)||[]).length,c=(t.match(/<\/b>/g)||[]).length;assert.equal(o,c,'unbalanced <b>');assert(t.length<=4096,'too long '+t.length)}
(async()=>{
 const g=createGas({gsPath:GS});const seeded=await seedAll(g);console.log('seeded',JSON.stringify(seeded));
 const sent=stubTelegram(g);const last=()=>sent[sent.length-1];const kb=m=>{const rm=m.payload.reply_markup;const k=typeof rm==='string'?JSON.parse(rm):rm;return k.inline_keyboard};
 // fix "today" for deterministic periods: the mock formatDate uses real clock; data ends 2026-09-28 (sewing) / 2026-09-30 (cutting)
 await test('/prod in the group (with @bot suffix) → menu with every production tool URL + jump buttons',async()=>{sent.length=0;g.ctx.handleMsg(msg('/prod@VRT_Prod_bot'));const m=last();assert.equal(m.method,'sendMessage');assert.equal(String(m.payload.chat_id),GROUP);const rows=kb(m);const urls=rows.flat().filter(b=>b.url&&!/spreadsheet/.test(b.url)).map(b=>b.url);const items=g.run('MENUS').prod.items;assert.equal(urls.length,items.length);assert(rows.flat().some(b=>b.url&&/spreadsheet/.test(b.url)),'Google Sheets button');for(const it of items)assert(urls.includes(g.run('BASE')+'/'+it.f),'missing '+it.f);const jumps=rows.flat().filter(b=>/^m:/.test(b.callback_data||'')).map(b=>b.callback_data);assert(jumps.includes('m:prod2:0')&&jumps.includes('m:sum:0'));assert(/Choose a tool/.test(m.payload.text)&&/選擇/.test(m.payload.text));return items.length+' tool buttons · jumps '+jumps.join(',')+' · balancing button: '+(items.find(i=>/ie_smv_report/.test(i.f))||{}).t});
 await test('/prod2 and /sum menus render; /sum has Day/Week/Month/Year digest buttons first',async()=>{sent.length=0;g.ctx.handleMsg(msg('/prod2'));const p2=kb(last());assert.equal(p2.flat().filter(b=>b.url&&!/spreadsheet/.test(b.url)).length,g.run('MENUS').prod2.items.length);g.ctx.handleMsg(msg('/sum'));const s=kb(last());const cbs=s.flat().map(b=>b.callback_data).filter(Boolean);assert.deepStrictEqual(cbs.slice(0,4),['d:day','d:week','d:month','d:year']);assert(s.flat().some(b=>b.text.includes('Menu')===false));return 'prod2 '+p2.flat().filter(b=>b.url&&!/spreadsheet/.test(b.url)).length+' urls · sum buttons '+cbs.length+' (pages: '+s.filter(r=>r.some(b=>/^m:sum:/.test(b.callback_data||''))).length+')'});
 await test('Menu paging: /sum has more than 8 rows → page 2 reachable and returns to page 1 in place (editMessageText)',async()=>{sent.length=0;g.ctx.handleMsg(msg('/sum'));const s1=kb(last());const next=s1.flat().find(b=>b.text.includes('下一頁'));assert(next,'no next page button');g.ctx.handleCbq(cbq(next.callback_data,77));const e=last();assert.equal(e.method,'editMessageText');assert.equal(e.payload.message_id,77);const s2=kb(e);assert(s2.flat().some(b=>b.text.includes('上一頁')));return 'page1 rows '+s1.length+' → '+next.callback_data+' → page2 rows '+s2.length});
 await test('/day /week /month /year (and /today) → bilingual all-department digest, HTML-safe, ≤4096, with department + period buttons',async()=>{const res=[];for(const c of ['/day','/week','/month','/year','/today']){sent.length=0;g.ctx.handleMsg(msg(c));const m=last();assert.equal(m.method,'sendMessage');assert.equal(m.payload.parse_mode,'HTML');htmlOk(m.payload.text);assert(hasZhEn(m.payload.text),'not bilingual');for(const T of ['車縫','裁剪','Final QC','機針','排單'])assert(m.payload.text.includes(T),c+' missing '+T);const rows=kb(m);const deps=rows.flat().filter(b=>/^s:/.test(b.callback_data)).length,per=rows.flat().filter(b=>/^d:(day|week|month|year):/.test(b.callback_data)).length;assert.equal(deps,5);assert.equal(per,4+3);res.push(c+' '+m.payload.text.length+'ch')}return res.join(' · ')});
 const periodsFor=async(cb)=>{const r={};for(const p of ['day','week','month','year']){const m=g.ctx.periodSummary_(cb,p,'');htmlOk(m.text);assert(hasZhEn(m.text),cb+' '+p+' not bilingual');assert(!/本期沒有資料/.test(m.text),cb+' '+p+' empty: '+m.text.slice(0,200));r[p]=m}return r};
 let sew;await test('Sewing 日/週/月/年 all have data (anchored on the latest data day, not "today"), bilingual, cross-checked against the backup',async()=>{sew=await periodsFor('sew');const bk=JSON.parse(fs.readFileSync(DL+'sewing_backup_2026-09-28.json','utf8')).daily;
   // independent computation: latest date ≤ today; per-day source rule norm>target>dpo
   const latest=bk.map(r=>r.date).filter(d=>d<=g.ctx.todayYmd_()).sort().pop();assert(sew.day.text.includes(latest),'day summary should be for '+latest+': '+sew.day.text.slice(0,120));
   const dayRows=bk.filter(r=>r.date===latest);const src=dayRows.some(r=>!r.tSrc||r.tSrc==='norm')?'norm':dayRows.some(r=>r.tSrc==='target')?'target':'dpo';const use=dayRows.filter(r=>(r.tSrc==='target'?'target':r.tSrc==='dpo'?'dpo':'norm')===src);const pcs=use.reduce((s,r)=>s+(Number(r.pieces)||0),0);
   assert(sew.day.text.includes('<b>'+pcs.toLocaleString()+'</b> pcs'),'day pieces '+pcs+' not in: '+sew.day.text.slice(0,300));
   // month: sum of the month with the same rule
   const mm=latest.slice(0,7),byDay={};bk.filter(r=>r.date.startsWith(mm)).forEach(r=>{const s=r.tSrc==='target'?'target':r.tSrc==='dpo'?'dpo':'norm';(byDay[r.date]=byDay[r.date]||{norm:0,target:0,dpo:0})[s]+=Number(r.pieces)||0});const mpcs=Object.values(byDay).reduce((s,x)=>s+(x.norm||x.target||x.dpo),0);
   assert(sew.month.text.includes('<b>'+mpcs.toLocaleString()+'</b> pcs'),'month pieces '+mpcs+' not in: '+sew.month.text.slice(0,300));
   return 'day '+latest+' = '+pcs+' pcs ('+src+') · month '+mm+' = '+mpcs+' pcs · week label '+(sew.week.text.match(/W\d\d[^<\n]*/)||[''])[0]});
 await test('Cutting 日/週/月/年: only daily detail rows counted (Weekly Report / Summary rows excluded), cross-checked against the backup',async()=>{const cut=await periodsFor('cut');const bk=JSON.parse(fs.readFileSync(DL+'cutting_backup_2026-09-30.json','utf8')).cutting;const isDaily=r=>r.src!=='ref'&&r.src!=='summary'&&r.lineNo!=='Weekly Report'&&r.lineNo!=='Monthly Summary'&&r.lineNo!=='Summary'&&r.pieces>0;const latest=bk.map(r=>r.date).filter(d=>d<=g.ctx.todayYmd_()).sort().pop();const mm=latest.slice(0,7);const mpcs=bk.filter(r=>r.date.startsWith(mm)&&isDaily(r)).reduce((s,r)=>s+r.pieces,0);const all=bk.filter(r=>r.date.startsWith(mm)).reduce((s,r)=>s+(r.pieces||0),0);assert(cut.month.text.includes('<b>'+mpcs.toLocaleString()+'</b> pcs'),'month cut '+mpcs+' not in: '+cut.month.text.slice(0,300));assert(mpcs<all,'exclusion should reduce the total');const ypcs=bk.filter(r=>r.date.startsWith(latest.slice(0,4))&&isDaily(r)).reduce((s,r)=>s+r.pieces,0);assert(cut.year.text.includes('<b>'+ypcs.toLocaleString()+'</b> pcs'),'year cut '+ypcs);return 'latest '+latest+' · month daily-only '+mpcs+' (all rows would be '+all+') · year '+ypcs});
 await test('QC 日/週/月/年: Final QC + sewing defect KPI both present in the month; reject rate and KPI rate cross-checked',async()=>{const qc=await periodsFor('qcsum');const m=qc.month.text;assert(/Final QC/.test(m)&&/Sewing defect KPI/.test(m),'both sections');const manifest=g.ctx.readSmartManifest_('qc');let rows=[];for(const k of Object.keys(manifest.buckets)){if(!/^(m:2026-09|p:kpi_2026-09)$/.test(k))continue;rows=rows.concat(JSON.parse(g.raw(g.ctx.smartBucketName_('qc',manifest.buckets[k].source,k)).content))}const fq=rows.filter(r=>!r._vrtEntity),ins=fq.reduce((s,r)=>s+r.inspected,0),rej=fq.reduce((s,r)=>s+r.rejected,0);assert(m.includes('<b>'+ins.toLocaleString()+'</b>'),'inspected '+ins);assert(m.includes(pct(rej/ins*100,2)),'rate '+pct(rej/ins*100,2));const kp=rows.filter(r=>r._vrtEntity==='qc.kpi').map(r=>r._vrtValue||r),ko=kp.reduce((s,v)=>s+v.sewingOutput,0),kd=kp.reduce((s,v)=>s+v.totalDefect,0);assert(m.includes(pct(kd/ko*100,2)),'kpi rate '+pct(kd/ko*100,2));return 'Sep inspected '+ins+' reject '+rej+' ('+pct(rej/ins*100,2)+') · KPI output '+ko+' defects '+kd+' ('+pct(kd/ko*100,2)+') · Top defects present: '+/Top 3 缺點/.test(m)});
 await test('Spare parts 日/週/月/年: needle changes with planned vs unplanned split, part changes, reasons bilingual; totals match the cloud rows',async()=>{const sp=await periodsFor('sp');const m=sp.month.text;const manifest=g.ctx.readSmartManifest_('spareparts');const nb=JSON.parse(g.raw(g.ctx.smartBucketName_('spareparts',manifest.buckets['p:maint_needle_2026-09'].source,'p:maint_needle_2026-09')).content).map(r=>r._vrtValue);const tot=nb.reduce((s,v)=>s+(v.qty||0),0),plan=nb.filter(v=>v.reasonClass==='changeover').reduce((s,v)=>s+(v.qty||0),0),unp=nb.filter(v=>/^(damage|broken|lost)$/.test(v.reasonClass)).reduce((s,v)=>s+(v.qty||0),0);assert(m.includes('<b>'+tot.toLocaleString()+'</b> 支 pcs'),'needle total '+tot);assert(m.includes('Planned: '+plan.toLocaleString()),'planned '+plan);assert(m.includes('<b>'+unp.toLocaleString()+'</b>'),'unplanned '+unp);assert(/Change style \(planned\)/.test(m)&&/換款/.test(m));assert(/Spare-part changes/.test(m));return 'Sep needles '+tot+' (planned '+plan+' / unplanned '+unp+') · day text: '+sp.day.text.split('\n')[0].replace(/<[^>]+>/g,'')});
 await test('Production plan 日/週/月/年 anchored on today: styles overlapping the period, load by line, starting list',async()=>{const pl={};for(const p of ['day','week','month','year']){const m=g.ctx.periodSummary_('plansum',p,'');htmlOk(m.text);assert(hasZhEn(m.text));pl[p]=m}const month=pl.month.text;assert(/Scheduled styles: <b>\d/.test(month),month.slice(0,200));assert(/Load by line/.test(month));const today=g.ctx.todayYmd_();assert(pl.day.text.includes(today));return 'today '+today+' · month: '+(month.match(/Scheduled styles: <b>[\d,]+<\/b>[^\n]*/)||[''])[0].replace(/<[^>]+>/g,'')});
 await test('Summary buttons: tapping 週 edits the same message in place; ◀ 上期 goes to the previous week; 📍 最新 returns to latest',async()=>{sent.length=0;g.ctx.handleCbq(cbq('sew',55));const first=last();assert.equal(first.method,'sendMessage');const rows=kb(first);const week=rows[0].find(b=>/^s:sew:week:/.test(b.callback_data));g.ctx.handleCbq(cbq(week.callback_data,first.payload.message_id||55));const e1=last();assert.equal(e1.method,'editMessageText');assert(/週 Week/.test(e1.payload.text));const prev=kb(e1)[1].find(b=>/Prev/.test(b.text));g.ctx.handleCbq(cbq(prev.callback_data,55));const e2=last();assert.equal(e2.method,'editMessageText');const w1=(e1.payload.text.match(/(\d{4}-W\d\d)/)||[])[1],w2=(e2.payload.text.match(/(\d{4}-W\d\d)/)||[])[1];assert(w1&&w2&&w2<w1,'prev week '+w2+' should be before '+w1);const latest=kb(e2)[1].find(b=>/Latest/.test(b.text));g.ctx.handleCbq(cbq(latest.callback_data,55));const e3=last();assert.equal((e3.payload.text.match(/(\d{4}-W\d\d)/)||[])[1],w1);return w1+' → prev '+w2+' → latest '+w1+' · answerCallbackQuery calls '+sent.filter(s=>s.method==='answerCallbackQuery').length});
 await test('Every period button of every department can be pressed without error (60 edits) and the ▶ next of a future period says "no data" instead of crashing',async()=>{let n=0;for(const cb of Object.keys(g.run('PERIOD_TOOLS')))for(const p of ['day','week','month','year']){const m=g.ctx.periodSummary_(cb,p,'');for(const b of kb({payload:{reply_markup:m.markup}}).flat()){if(!/^s:/.test(b.callback_data))continue;sent.length=0;g.ctx.handleCbq(cbq(b.callback_data,9));assert.equal(last().method,'editMessageText',b.callback_data);htmlOk(last().payload.text);n++}}const fut=g.ctx.periodSummary_('sew','month','2030-01-15');assert(/本期沒有資料|No data/.test(fut.text));return n+' button presses ok · future month → '+fut.text.split('\n').filter(l=>/No data/.test(l))[0]});
 await test('Legacy /sum summaries (orders, shipping, BOM, FG, PO, cut plan, fabric, SMV, customers, status) are bilingual HTML and escape customer names',async()=>{const res=[];for(const key of ['ord','ship','bom','fg','pod','cutplan','fstock','smvsum','custsum','mshipsum','fabdel','stat']){sent.length=0;g.ctx.handleCbq(cbq(key,5));const m=last();assert.equal(m.method,'sendMessage',key);assert.equal(m.payload.parse_mode,'HTML',key);htmlOk(m.payload.text);assert(hasZhEn(m.payload.text),key+' not bilingual: '+m.payload.text.slice(0,80));res.push(key)}const escp=g.run('VRTTgSummary').build('orders',{lines:[{po_number:'P<1',customer:'A<B & C_D*E',qty:5,cancel_date:'10-FEB-26'}]},'month','2026-02-10').text;assert(escp.includes('A&lt;B &amp; C_D*E')&&!/<[^b/]/.test(escp.replace(/<\/?b>/g,'')),escp);sent.length=0;g.ctx.handleCbq(cbq('ord',5));assert(/訂單 Orders/.test(last().payload.text)&&/AMERICAN DAWN/.test(last().payload.text),'orders period summary from buckets');return res.join(',')+' · escaped customer ok · orders summary now period-based (PO '+(last().payload.text.match(/PO: <b>([\d,]+)/)||[])[1]+')'});
 await test('If Telegram rejects the HTML, the same content is re-sent as plain text (message always goes out)',async()=>{const s2=stubTelegram(g,{rejectHtml:true});g.ctx.handleMsg(msg('/day'));const rej=s2.filter(x=>x.rejected).length,ok=s2.filter(x=>x.method==='sendMessage'&&!x.rejected);assert.equal(rej,1);assert.equal(ok.length,1);assert(!ok[0].payload.parse_mode&&!/<b>/.test(ok[0].payload.text)&&/車縫/.test(ok[0].payload.text));stubTelegram(g);return 'HTML rejected once → plain text sent ('+ok[0].payload.text.length+' ch)'});
 await test('4096 guard: an oversized summary is clipped at a line break with a truncation note',async()=>{const big=Array.from({length:400},(_,i)=>'<b>line '+i+'</b> 資料 data').join('\n');const t=g.ctx.tgClip_(big);assert(t.length<=4096&&/truncated/.test(t));htmlOk(t);return big.length+' → '+t.length});
 await test('pollTelegram: getUpdates with a group /prod, a /week and a callback are all handled and the offset advances',async()=>{const s3=stubTelegram(g,{updates:[{update_id:900,message:msg('/prod@VRT_Prod_bot')},{update_id:901,message:msg('/week')},{update_id:902,callback_query:cbq('s:cut:month:latest',12)},{update_id:903,message:{message_id:9,chat:{id:Number(GROUP)},photo:[{file_id:'x'}]}}]});g.ctx.pollTelegram();const methods=s3.map(x=>x.method);assert.deepStrictEqual(methods.filter(m=>m!=='getUpdates'),['sendMessage','sendMessage','answerCallbackQuery','editMessageText']);assert.equal(g.ctx.PropertiesService.getScriptProperties().getProperty('tg_offset'),'904');return methods.join(',')+' · offset 904'});
 await test('Manual senders for time triggers: sendDigest / sendPeriodSummary / sendWeeklyDigest post to CFG.CHAT_ID',async()=>{const s4=stubTelegram(g);g.ctx.sendDigest('day');g.ctx.sendPeriodSummary('qcsum','week');g.ctx.sendWeeklyDigest();assert.equal(s4.filter(x=>x.method==='sendMessage').length,3);assert(s4.every(x=>String(x.payload.chat_id)===GROUP));return '3 messages to '+GROUP});
 await test('Setup helpers: checkTelegramSetup reports missing trigger; ensurePollingTrigger creates it once',async()=>{const created=[];let triggers=[];g.ctx.ScriptApp={getService:()=>({getUrl:()=>'https://script.google.com/macros/s/MOCK_PROD/exec'}),getProjectTriggers:()=>triggers.map(h=>({getHandlerFunction:()=>h})),newTrigger:h=>({timeBased:()=>({everyMinutes:n=>({create:()=>{created.push(h+'@'+n);triggers.push(h)}})})})};const s5=stubTelegram(g);g.ctx.UrlFetchApp.fetch=(url,o)=>{const m=String(url).match(/\/(getMe|getChat)$/);if(m)return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,result:m[1]==='getMe'?{username:'VRT_Prod_bot'}:{title:'VRT 生產群'}})};return {getResponseCode:()=>200,getContentText:()=>'{"ok":true,"result":{}}'}};const before=g.ctx.checkTelegramSetup();assert.equal(before.pollTrigger,false);assert.equal(before.bot,'@VRT_Prod_bot');const r1=g.ctx.ensurePollingTrigger(),r2=g.ctx.ensurePollingTrigger();assert(r1.created&&!r2.created);assert.deepStrictEqual(created,['pollTelegram@1']);const after=g.ctx.checkTelegramSetup();assert(after.pollTrigger);return 'before: '+before.hint+' → created '+created[0]+' → after: '+after.hint});
 await test('Existing sync API unchanged in v4.4: ping/capabilities, smartManifest, pull compat all still answer; backendVersion 4.4.0',async()=>{const cap=g.get({action:'capabilities'});assert.equal(cap.data.backendVersion,'4.4.0');assert(cap.data.bilingualSummaries);const mf=g.get({action:'smartManifest',tool:'sewing'});assert(mf.ok&&mf.data.exists);const pull=g.get({action:'pull',tool:'cutting'});assert(pull.ok&&pull.data.smart);return 'capabilities '+JSON.stringify(cap.data.periodSummaries)+' · sewing buckets '+Object.keys(mf.data.hashes).length});
 fs.writeFileSync(path.resolve(__dirname,'telegram_results.json'),JSON.stringify(out,null,2));
 // save sample texts for the report
 const samples={};for(const cb of Object.keys(g.run('PERIOD_TOOLS')))for(const p of ['day','week','month','year'])samples[cb+':'+p]=g.ctx.periodSummary_(cb,p,'').text;for(const p of ['day','week','month','year'])samples['digest:'+p]=g.ctx.digestSummary_(p,'').text;fs.writeFileSync(path.resolve(__dirname,'telegram_samples.json'),JSON.stringify(samples,null,2));
 const f=out.filter(x=>x.status==='FAIL').length;console.log((out.length-f)+'/'+out.length+' PASS');process.exitCode=f?1:0;
 function pct(v,d){return v.toFixed(d)+'%'}
})().catch(e=>{console.error(e);process.exit(1)});
